examples/scripts/dlDemo.script

I fixed what I think is some bad syntax.

Fix ArrayIndexOutOfBoundsException

---

core/src/main/scala/org/apache/spark/h2o/DefaultSource.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/H2ORelation.scala
core/src/main/scala/org/apache/spark/rdd/H2ORDD.scala
core/src/main/scala/org/apache/spark/rdd/H2ORDDLike.scala
core/src/main/scala/org/apache/spark/rdd/H2OSchemaRDD.scala
core/src/main/scala/org/apache/spark/sql/H2OSQLContextUtils.scala

The fix introduces `H2OFrameRelation` implementing `BaseRelation` and additional releation
to allow column filtering. The H2OFrameRelation is used instead of H2ORelation which was removed.

[SW-170] Unification of the API for H2OFrame data source and asDataFrame transformation

---

core/src/main/scala/org/apache/spark/h2o/utils/NodeDesc.scala
core/src/main/scala/water/fvec/FrameUtils.scala

NodeDesc are interned from cache based on H2ONode key.
SW-172 #resolve #comment This also resolve SW-171
SW-171 #resolve

[SW-172] NodeDesc interned in global cache.

---

core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalReadConverterContext.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/ReadConverterContext.scala

This is needed for @vpatryshev dataset PR and also it's easier to read solution
I'll do corresponding change in https://github.com/h2oai/sparkling-water/pull/49, this should be merge to unblock Vlad and merging of Dataset branch

[SW-186] Hide checks whether incoming data is NA into convertorCtx

---

README.md
core/src/main/scala/org/apache/spark/h2o/DefaultSource.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/JavaH2OContext.java
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalReadConverterContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterContext.scala
core/src/main/scala/org/apache/spark/h2o/converters/ConverterUtils.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDDLike.scala
core/src/main/scala/org/apache/spark/h2o/converters/ProductRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SupportedDataset.scala
core/src/main/scala/org/apache/spark/h2o/converters/SupportedRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/package.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OTypeUtils.scala
core/src/main/scala/org/apache/spark/h2o/utils/ReflectionUtils.scala
core/src/main/scala/water/api/RDDs/RDDsHandler.scala
core/src/main/scala/water/fvec/FrameUtils.scala
core/src/test/scala/org/apache/spark/h2o/H2OConfTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/H2ODatasetTest.scala
core/src/test/scala/org/apache/spark/h2o/H2OFrameToRDDTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/converters/ConvertersTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/utils/SharedSparkTestContext.scala
core/src/test/scala/org/apache/spark/h2o/utils/TestBase.scala
core/src/test/scala/org/apache/spark/h2o/utils/TestData.scala
core/src/test/scala/water/api/ScalaCodeHandlerSuite.scala
gradle/spark.gradle
ml/src/main/scala/org/apache/spark/ml/h2o/features/DatasetSplitter.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OAlgo.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OModel.scala

This stuff is working; I'll need to work on code deduplication, can be done later.

[SW-158] Support for Spark DataSet

---

py/README.rst
py/pysparkling/context.py

Just a couple of small things in py directory

Slightly improved the README; added a better context error reporting.

---

core/src/main/scala/water/api/RestAPIManager.scala

We had this workaround before, but it somehow got lost in rel-1.6 branch.
This workaround should be only temporary - we need to back port repl from spark 2.0 and support both repl versions ( because cdh 5.7 is using new repl version ), but other spark distribution are using the one shipped with spark.

Don't use repl on CDH 5.7

---

py/build.gradle

Includes:
- fix of path issues (wrong file references)
- cleanup

[SW-242] Fix build process

---

py/examples/notebooks/TensorFlowDeepLearning.ipynb
py/pysparkling/conf.py
py/pysparkling/context.py
py/tests/test_utils.py

Fixes:
* Links to Sparkling Water and PySparkling (used links to 2.0 now)
* Fixed some print statements in PySparkling
* Fixed some Python3 incompatibilities in the tensorflow demo, should be still ok with Python2

[SW-248] Python 3 incompatibilities

---

repl/src/main/scala/org/apache/spark/repl/h2o/BaseH2OInterpreter.scala
repl/src/main/scala/org/apache/spark/repl/h2o/InterpreterClassLoader.scala
repl/src/main/scala_2.10/org/apache/spark/repl/h2o/H2OIMain.scala
repl/src/main/scala_2.11/org/apache/spark/repl/h2o/H2OIMain.scala

(cherry picked from commit e5990f271949e35a4eb82080d5c2f2235e9c14e0)

[SW-237] Fix classloading issues in repl - for rel-2.0

---

core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala

Fixed spark version extraction

---

r/rsparkling/R/h2o_context.R

* This PR makes `strict_version_check` a parameter for `h2o_context`.

Add option to check H2O version with h2o_context()

---

core/src/main/scala/org/apache/spark/h2o/converters/ConverterUtils.scala
core/src/test/scala/org/apache/spark/h2o/utils/SharedSparkTestContext.scala
core/src/test/scala/water/api/SupportAPISuite.scala
examples/src/integTest/scala/water/sparkling/itest/IntegTestHelper.scala
examples/src/scriptsTest/scala/water/sparkling/scripts/ScriptTestHelper.scala
gradle.properties
py/tests/conf/pyunit/spark-defaults.conf
py/tests/test_utils.py

Also includes upgrade of Spark build dependency to Spark2.0.1 and fix of API.

[SW-245] Upgrade of H2O dependency to 3.10.0.8

---

r/examples/nycflights13.R

*This demo demonstrates the following:
- How to set up your R environment for RSparkling
- Sparklyr/Spark for data munging
- H2O for model building
- Bunding the previous two together in a Shiny Application

Add walkthrough of rsparkling

---

r/examples/nycflights13.R

* This PR updates the demo to now convert character variables to factors before model build and also render a better data table in the Shiny application.

Update demo for NYCFlights13

---

core/src/main/resources/META-INF/services/org.apache.spark.h2o.AnnouncementProvider
core/src/main/scala/org/apache/spark/h2o/AnnouncementService.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

The fix includes:
- announcement service to notify about SW events
- announcement provider API which should be implemented to provide notification mechanism
- REST API based notification

[SW-325] A generic announcement subsystem

---

examples/README.md

This pull requests updates the example in the examples/README.md file.

Updated examples README file

---

README.md
bin/libsw.cmd
bin/run-example2.cmd
bin/run-sparkling.cmd
bin/run-sparkling2.cmd
bin/sparkling-env.cmd
bin/sparkling-shell2.cmd

[SW-350] Fixes Windows shell scripts problems

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala

Since the web was disabled, the jetty wasn't even started and thus JAAS module wasn't loaded

[SW-353] Fix loading of JAAS module

---

assembly-h2o/build.gradle
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
py/pysparkling/conf.py

Plus some stylistic changes to pysparkling conf

[SW-377] Implement stopping of external H2O cluster in external backend

---

examples/README.md
examples/src/main/scala/org/apache/spark/examples/h2o/AirlinesWithWeatherDemo2.scala

* Updated R code in `residualPlotRCode` function.
* Added h2oContext to the `residualPlotRCode` arguments in the readme example.

[SW-385] Small fix to residualPlotRCode

---

README.md
core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/test/scala/org/apache/spark/h2o/H2OConfTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/utils/SparkTestContext.scala
dist/index.html
doc/backends.md
py/README.rst
py/pysparkling/conf.py
py/pysparkling/context.py

<s>TODO: Documentation changes<s>

[SW-265] Use Spark Session in public API instead of Spark Context

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

The delete was marking Yarn job as failed, since we deleted yarn temporary files.

[SW-421] Skip yarn files delete

---

Jenkinsfile

[SW-380] Minor Jenkinsfile update

---

py/pysparkling/initializer.py

Also remove the if condition handling the old egg files.

[SW-436] Remove cache for extracted sparkling water jar.

---

core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala

Running sparkling water on large datasets (100+gb) noticed it spends a lot of time on figuring out feature vector size: [![SW.png](https://s24.postimg.org/gpt1ui4w5/image.png)](https://postimg.org/image/5dggcpw75/). If feature vector was created by Spark's VectorAssembler it would have array size [inside metadata](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/feature/VectorAssembler.scala#L88). So what it does - it iterates for all vector/array indicies in metadata and if for all of them there's size in metadata - it can return result in a constant time.

[SW-442] Get array size from metadata

---

assembly/build.gradle
py/build.gradle

Only task and project dependencies are allowed for projects to be decoupled. We were using configuration dependency

[SW-263] Allow running build in parallel

---

assembly/build.gradle
build.gradle
core/build.gradle
core/src/main/resources/META-INF/services/water.api.Schema
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/main/scala/water/api/RestAPIManager.scala
core/src/main/scala/water/util/LogBridge.scala
gradle.properties
ml/src/main/resources/META-INF/services/water.api.RestApi
ml/src/main/resources/META-INF/services/water.api.Schema
ml/src/main/scala/hex/SVMModelRestAPI.scala

Integrates sparkling water with the latest sparkling water ( so we can release sw quickly )

[SW-447] Upgrade H2O to 3.10.5.1

---

dist/index.html

Edited the installation instructions on the DOWNLOAD, RUN ON HADOOP, and RUN ON STANDALONE CLUSTER tabs. Changed
`val h2oContext = H2OContext.getOrCreate(sparkSession)`
to
`val h2oContext = H2OContext.getOrCreate(spark)`

[SW-450] Edits to the Installation instructions

---

DEVEL.md
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
py/pysparkling/conf.py

[SW-460] Add public flow dir configuration property

---

core/src/main/scala/water/api/CoreRestAPI.scala
core/src/main/scala/water/api/DataFrames/DataFramesHandler.scala
core/src/main/scala/water/api/H2OFrames/H2OFramesHandler.scala
core/src/main/scala/water/api/RDDs/RDDsHandler.scala
core/src/main/scala/water/api/RestApi.scala
core/src/main/scala/water/api/scalaInt/ScalaCodeHandler.scala
ml/src/main/scala/hex/SVMModelRestAPI.scala

And use RestApiContext for registering endpoints

[SW-494] Remove hard dependency on RequestServer by using RestApiContext

---

assembly/build.gradle
dist/index.html
make-dist.sh

Also remove dead code in `./make-dist` script

[SW-355] Put latest rsparkling into the distribution package

---

Jenkinsfile
assembly-h2o/build.gradle
core/build.gradle
core/src/test/scala/org/apache/spark/h2o/utils/ExternalBackendTestHelper.scala
examples/build.gradle
gradle/sparkTest.gradle
gradle/utils.gradle
py/build.gradle

This change fixes the environment for external tests.

[SW-423] Tests of External Cluster mode fails when starting H2O locally

---

Jenkinsfile
assembly-h2o/build.gradle

Also fix several issues in assembly-h2o build

[SW-536] Allow to test sparkling water against specific h2o branch

---

bin/libsw.cmd
bin/sparkling-env.sh

Implemented in both python and unix scripts

[SW-420] Check java availability first before checking spark version

---

py/build.gradle
py/tests/tests_unit_conf.py
py/tests/tests_unit_conversions.py

It's workaround on the Gradle level

[SW-320] Unblock H2OConf test

---

examples/build.gradle
jenkins/sparklingWaterPipeline.groovy
ml/build.gradle

- Remove duplicite artifact dependency in examples build gradle
- Remove unnecessary sources setting in ml build gradle
- Report ml test reports in jenkins file

[SW-596] Minor build improvements

---

ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2ODeepLearning.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGBM.scala
py/build.gradle
py/examples/pipelines/ham_or_spam_deep_learning.py
py/examples/pipelines/ham_or_spam_gbm.py
py/pysparkling/context.py
py/pysparkling/ml/__init__.py
py/pysparkling/ml/algo.py
py/pysparkling/ml/feature.py
py/pysparkling/ml/params.py
py/tests/tests_integ_local.py

ColumnPruner, H2OGBM and H2ODeepLearning ( H2OGBM backed by mojo, H2ODeepLearning backed by binary model ) can now be used in PySpark pipelines.

[SW-519] Introduce SW Models into Spark python pipelines

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/test/scala/org/apache/spark/h2o/converters/SW516StandaloneApp.scala
core/src/test/scala/org/apache/spark/h2o/utils/ExternalBackendManualTestStarter.scala
doc/tutorials/backends.rst
py/tests/external_backend_manual_test_starter.py

Depends on https://github.com/h2oai/h2o-3/pull/1569 ( Already in H2O master and rel branch)

[SW-547] Don't use md5skip

---

doc/configuration/internal_backend_tuning.rst

[DOC][HOTFIX][SW-613] Append option to disable dynamic allocation into tuning

---

py/pysparkling/context.py
py/tests/tests_unit_conversions.py

There is a corresponding PR in H2O-3: https://github.com/h2oai/h2o-3/pull/1788

[SW-602] Modification of internal call to get smaller frame preview

---

build.gradle
gradle/release.gradle
jenkins/Jenkinsfile-release

(cherry picked from commit d01b73bdfb84ef7a856fcd476fcd6fe6b3f93916)
(cherry picked from commit 65862dbe1e93373ffd75743e4e261df238c67b29)
(cherry picked from commit d9aac7ff01179375577042c68a12015bb124959c)

[SW-638] Port release script into pipeline in the repo with code for rel-1.6

---

build.gradle
gradle/release.gradle
jenkins/Jenkinsfile-release

(cherry picked from commit d01b73bdfb84ef7a856fcd476fcd6fe6b3f93916)
(cherry picked from commit 65862dbe1e93373ffd75743e4e261df238c67b29)

[SW-638] Port release script into pipeline in the repo with code for rel-2.0

---

build.gradle
gradle/release.gradle
jenkins/Jenkinsfile-release

(cherry picked from commit d01b73bdfb84ef7a856fcd476fcd6fe6b3f93916)

[SW-638] Port release script into pipeline in the repo with code for rel-2.1

---

core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala

[SW-637] Create new DataFrame with new schema when it actually contains dot

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

Note: This will still fail as this depends on this H2O change https://github.com/h2oai/h2o-3/pull/1919

[SW-551] Remove hotfix introduced by [SW-541] and implement proper fix

---

examples/pipelines/hamOrSpamAutoMLMojo.script
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParamsHelper.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OModelParams.scala
py/examples/pipelines/ham_or_spam_automl.py
py/pysparkling/ml/__init__.py
py/pysparkling/ml/algo.py
py/pysparkling/ml/params.py

Still work in progress, this is really just init phase

[SW-702] Initial implementation of H2OAutoML pipeline step

---

examples/pipelines/hamOrSpamGridGBM.script
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala

This is a simplified version of H2OGridSearch pipeline step for GBM

[SW-745] Implement GridSearch for GBM in the Scala API

---

examples/src/integTest/scala/water/sparkling/itest/local/PubDev928Suite.scala

My Bad, I was too quick and sure with previous change

[SW-768] Add missing import

---

doc/build.gradle
doc/src/site/sphinx/devel/build.rst
doc/src/site/sphinx/requirements.rst
doc/src/site/sphinx/tutorials/pysparkling_azure_dbc.rst
doc/src/site/sphinx/tutorials/rsparkling_azure_dbc.rst
doc/src/site/sphinx/tutorials/sw_azure_dbc.rst
doc/src/site/sphinx/tutorials/use_as_spark_package.rst
doc/src/site/sphinx/tutorials/use_on_zeppelin.rst

(cherry picked from commit 0d88cff40cfa1f00bb0796f37cbf890c998d391a)

[SW-787] Several Technical Documentation fixes

---

README.rst

(cherry picked from commit 250950ee3cd858c1b8d137903aba14b529bf7516)

[SW-794] Point to proper web-based docs and add docs badge (#661)

---

bin/libsw.cmd

[SW-XXX] programmer error:  " is lost

---

core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2OFrameFromRDDProductBuilder.scala
core/src/main/scala/org/apache/spark/h2o/converters/LabeledPointConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/MLLibVectorConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/PrimitiveRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala

(cherry picked from commit bb4e8e36864f0b2c6ecf74e8b4e36bbf74602557)

[SW-832] Small refactoring in identifiers

---

gradle.properties
ml/build.gradle
py/build.gradle

(cherry picked from commit b6548ac4a6796b91fb3c5c9f5211c47d7d47e805)

[SW-838] Upgrade Mojo pipeline dependency

---

dist/index.html

(cherry picked from commit b15784ce41e6f08b16bb218c5a3cd33ebf63f103)

[SW-849] Update use from maven on sparkling water download page

---

ml/src/test/scala/org/apache/spark/ml/spark/models/H2OMOJOPipelineModelTest.scala

This reverts commit 12e8356965ff0ee42ab7cee505df2e35c56fa094.

[SW-864] Revert "[SW-864] Fix & more readable test (#743)"

---

gradle.properties
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
py/examples/pipelines/ham_or_spam_multi_algo.py
py/py_sparkling/ml/algos.py
py/pysparkling/ml/params.py

- Expose Sort Metric in AutoML
- Expose new distribution families
- Expose newly added automl arguments

[SW-873] Upgrade to H2O 3.20.0.1

---

jenkins/Dockerfile

(cherry picked from commit 0e82a58a31d21c15bbf522cb5d0d73c1b0eaaadb)

[SW-895] Put data files into docker (not that much in SW case)

---

jenkins/Dockerfile

(cherry picked from commit 7ca5d1529ac214cfc92978b9c2126dccb6c839d0)

[SW-895] Put data into dockerfile

---

gradle/publish.gradle

(cherry picked from commit fe65a9ba18fbc76a00c39a7d42b726de9642dd1c)

[SW-918] Fail in releasing to github

---

doc/src/site/sphinx/tutorials/use_as_spark_package.rst

(cherry picked from commit 808845ddb6f94ba4319fbc7c5d3997d501cdef1d)

[SW-911] You can't run sparkling water with the current documentation

---

gradle/wrapper/gradle-wrapper.properties

[SW-1027] Revert Upgrade to Gradle 4.10.1(bug in Gradle) and upgrade to Gradle 4.0

[SW-XXX] This reverts commit 324e207b1fe05eb1e75c0f9204dc1f918451e33e.

---

bin/sparkling-env.sh

(cherry picked from commit ddd2f468daf75f74cef099a49a23ded8033f4297)

[SW-1042] More robust check for python package in PySparkling shell

---

jenkins/Jenkinsfile-release
r/for_release/utils.R

(cherry picked from commit e79bfd00dcf940a4a87de5ea607fde3964d873d1)

[SW-XXX] [HOTFIX] Fixes to release pipeline

---

jenkins/Jenkinsfile-release
py/conda/h2o_pysparkling_2.2/bld.bat
py/conda/h2o_pysparkling_2.2/build.sh

(cherry picked from commit 319c640414572268bb8c50f004e09f1ed2c6da50)

[SW-464] Enable relase of PySparkling conda packages

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalReadConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2OFrameFromRDDProductBuilder.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDDLike.scala
core/src/main/scala/org/apache/spark/h2o/converters/LabeledPointConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/MLLibVectorConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/PrimitiveRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/ReadConverterCtxUtils.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala

This requires https://github.com/h2oai/h2o-3/pull/3194 change in H2O first

[SW-1107] Fix NPE in external backend

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2OFrameFromRDDProductBuilder.scala
core/src/main/scala/org/apache/spark/h2o/converters/LabeledPointConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/MLLibVectorConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/PrimitiveRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/ProductRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala
core/src/main/scala/water/fvec/FrameUtils.scala
gradle/conf/scalastyle-config.xml

Currently only available for internal backend & requires new H2O release

[SW-1135] Use sparse new chunk for storing data from Spark sparse vectors

---

assembly/build.gradle
core/build.gradle
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala
doc/src/site/sphinx/tutorials/hive_support.rst
doc/src/site/sphinx/tutorials/tutorials.rst

TODO:
Waits on 3.24.0.1 release

[SW-1175] Integrate with H2O native hive support

---

gradle.properties

[SW-1195] Disable gradle daemon

---

gradle.properties
jenkins/Jenkinsfile-release

[SW-1195][rel-2.4] Disable gradle daemon

---

gradle.properties
jenkins/Jenkinsfile-release

[SW-1195][rel-2.3] Disable gradle daemon

---

gradle.properties
jenkins/Jenkinsfile-release

[SW-1195][rel-2.2] Disable gradle daemon

---

gradle.properties
jenkins/Jenkinsfile-release

[SW-1195][rel-2.1] Disable gradle daemon

---

.travis.yml
doc/src/site/sphinx/FAQ.rst
jenkins/Dockerfile
ml/src/test/scala/org/apache/spark/ml/spark/models/PipelinePredictionTest.scala

This PR fixes all tests in ```PipelinePredictionTest``` under the circumstances when a user uses non-native language to his country.
The PR also contains few small refactoring changes.

[SW-1196] Fix PipelinePredictionTest when a user uses non-native language to his country

---

core/src/main/scala/water/util/DeprecatedMethodMacro.scala
core/src/test/scala/water/util/DeprecatedMethodMacroSuite.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2ODeepLearning.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGBM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGLM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OXGBoost.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParamsHelper.scala
py/py_sparkling/ml/algos.py
py/pysparkling/ml/params.py

The PR propagates changes from #1132 to rel-2.1 branch.

[SW-1193][rel-2.1] Expose 'weightCol' parameter for DL, GBM, GLM, XGBoost (#1132)

---

ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParamsHelper.scala
py/py_sparkling/ml/algos.py
py/pysparkling/ml/params.py

Also remove comments which are not used anywhere

[SW-1210] Add fold column to python and scala pipelines

---

ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAlgorithm.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAlgorithmCommons.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OCommonParams.scala
py/py_sparkling/ml/algos.py
py/pysparkling/ml/params.py

The PR contains:
* Introduction of feature columns on GridSearch and AutoML
* Separation of common parameters to a dedicated trait 
* Introduction of a weight column on GridSearch

[SW-1248][FOLLOWUP] Introduce feature columns on GridSearch and AutoML

---

doc/src/site/sphinx/devel/integ_tests.rst
doc/src/site/sphinx/tutorials/spark_h2o_conversions.rst
doc/src/site/sphinx/tutorials/sw_xgboost.rst
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAlgorithm.scala

(cherry picked from commit 28ad5a22714cf91d7dcb7aab2fc2ecc114e9ec16)

[SW-1290] Fix doc

---

py/pysparkling/initializer.py

Going to manually test on Databricks Cloud(DBC)

[SW-1301] Fix class-loading for Sparkling Water assembly JAR in PySparkling

---

doc/src/site/sphinx/deployment/load_mojo.rst
doc/src/site/sphinx/deployment/scoring_mojo_pipeline.rst
py/py_sparkling/ml/models.py
py/tests/tests_unit_conversions.py
py/tests/tests_unit_mojo_pipeline.py
py/tests/tests_unit_mojo_predictions.py

The method is a member of `H2OMOJOModel` and `H2OMOJOPipelineModel` python classes.

[SW-1313] Rename the 'create_from_mojo' method to 'createFromMojo'

---

doc/src/site/sphinx/tutorials/sw_xgboost.rst
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OMOJOModelParams.scala
py/py_sparkling/ml/models.py

Second iteration -> return JSON with raw model details as that will meet the requirement and is, at least a bit cleaner than returning directly H2O's java object. We can make it nicer in the future and parse internally the json and provide more fine-grained methods

[SW-1307] Expose model details

---

core/src/main/scala/org/apache/spark/h2o/package.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAlgorithm.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2ODeepLearning.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGBM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGLM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OXGBoost.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/test/scala/org/apache/spark/ml/spark/models/H2OAlgoTest.scala
py/py_sparkling/ml/algos.py
py/pysparkling/ml/params.py

The 'modelId' parameter will be exposed on:
* H2OGBM
* H2OGLM
* H2OXGBoost
* H2ODeepLearning

[SW-1323] Expose 'modelId' as a parameter of H2O algorithms

---

dist/build.gradle
jenkins/sparklingWaterPipeline.groovy

(cherry picked from commit 9b76f60fea3cd7a857c13b43606fac79454f51f1)

[SW-1339] Use s3-cli instead of s3cmd because of performance reasons on nightlies

---

ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala

This a really minor change that should improve code readability a bit.

[SW-1349] Use withColumn instead of select in the MOJO models

---

jenkins/Jenkinsfile-external
jenkins/Jenkinsfile-internal

First contact with jenkins pipeliens :)

[SW-1365] Run only last build in jenkins

---

dist/src/index.html

@mn-mikke adding you as reviewer just for you to know where to change stuff on our download page

[SW-1369] Download page is missing one step on RSparkling tab -> library(rsparkling)

---

build.gradle
core/build.gradle
core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/deployment/backends.rst
examples/src/integTest/scala/water/sparkling/itest/IntegTestHelper.scala
examples/src/scriptsTest/scala/water/sparkling/scripts/ScriptTestHelper.scala
macros/build.gradle
macros/src/main/scala/ai/h2o/sparkling/macros/DeprecatedMethodMacro.scala
macros/src/test/scala/ai/h2o/sparkling/macros/DeprecatedMethodMacroSuite.scala
ml/build.gradle
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OMOJOModelParams.scala
py/pysparkling/conf.py
settings.gradle

I also did a bit of deprecations as the original name was way too long

[SW-1383] Fix cloud up in external backend manual mode

---

core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala

This PR should fix the build of rel-2.1, rel-2.2 and rel-2.3.

[SW-1386][FOLLOWUP] Replace df.isEmpty with df.take(1).headOption

---

doc/src/site/sphinx/tutorials/sw_xgboost.rst

The PR also updates the documentation.

[SW-1394] Modify sw_xgboost.rst to use tabs for Python and Scala code

---

ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOReader.scala

@mn-mikke this PR should address last  comments on https://github.com/h2oai/sparkling-water/pull/1310

[SW-1395] ML Code simplifications & improvements

---

core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala

This PR should fix failing build of rel-2.1

[SW-1400] Nullability tests in DataFrameConverterTest should use data frames with an explicit schema

---

doc/src/site/sphinx/CHANGELOG.rst
jenkins/Jenkinsfile-release

(cherry picked from commit e2c6d419e8910334d12db5d6c8558761d1009833)

[SW-1401] Change log unification across branches

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoCommonParams.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoParamsHelper.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoSharedTreeParams.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoSupervisedParams.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoUnsupervisedParams.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonSupervisedParams.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonUnsupervisedParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAlgorithm.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2ODeepLearning.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGBM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGLM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OXGBoost.scala
ml/src/test/scala/org/apache/spark/ml/h2o/param/H2OAlgoParamsHelperTest.scala

This is just refactoring in order to be able to implement `H2OSupervisedAlgorithm` and `H2OUnsupervisedAlgorithm`

[SW-1448] Refactor parameters into supervised & unsupervised

---

benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/BenchmarkBase.scala
benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/Runner.scala
benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/SampleBenchmark.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OSupervisedAlgorithm.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OUnsupervisedAlgorithm.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2ODeepLearning.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGBM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGLM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OXGBoost.scala
ml/src/test/scala/org/apache/spark/ml/spark/models/H2OAlgoTest.scala

Required for https://github.com/h2oai/sparkling-water/pull/1364

[SW-1449] Create Supervised & Unsupervised Algorithm

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModelBase.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOSettings.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OMOJOModelParams.scala
py/py_sparkling/ml/algos.py
py/py_sparkling/ml/models.py
py/pysparkling/ml/params.py
py/tests/tests_unit_conf.py

The goal is to have single prediction value in prediction column.
As we are introducing new algo -> H2OKmeans, I wanted to have this algorithm implemented with the new approach

[SW-1460] Infrastructure for prediction column with a simple prediction value

---

ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoder.scala
ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoderBase.scala
ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoderModelUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala

MOJO model was referencing `Frame`

[SW-1368] Preparation for the MOJO scoring package

---

ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OAutoML.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2ODeepLearning.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGBM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGLM.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala
ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OXGBoost.scala
ml/src/main/scala/org/apache/spark/ml/h2o/features/ColumnPruner.scala

Depends on https://github.com/h2oai/sparkling-water/pull/1410

[SW-1483][Step-3] Put back wrappers for algos in deprecated package

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala

This PR tries to fix failing `LocalIntegTestSuite.test_pipeline_automl`.

[SW-1485][FOLLOWUP] Fixing Local Integration Test

---

doc/src/site/sphinx/devel/running_examples.rst
examples/README.rst
examples/src/main/scala/org/apache/spark/examples/h2o/AirlinesWithWeatherDemo2.scala

Fix links on the examples/Readme file to point to built documentation.
Also when doing the README update, updated quickly the example script so it can run again

[SW-1487] Update examples/README file

---

core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/deployment/aws_emr_edge_node.rst
py/ai/h2o/sparkling/H2OConf.py

As we don't need this configuration, I would like to remove it so it is easier for users start using Sparkling Water

[SW-1523] Fix IP based cloud-up on client side

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalReadConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDDLike.scala
core/src/main/scala/org/apache/spark/h2o/converters/ReadConverterCtxUtils.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
py/src/ai/h2o/sparkling/H2OConf.py

Can be merged after we integrate SW with H2O 3.26.0.3

[SW-1540] Remove unnecessary read confirmation timeout

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
settings.gradle

First step is to use the init and finalize methods on the remote backend side

[SW-1530] Conversion to H2OFrame needs to work without running H2O client

---

py/tests/unit/with_runtime_sparkling/algo_test_utils.py
py/tests/unit/with_runtime_sparkling/test_automl.py
py/tests/unit/with_runtime_sparkling/test_deeplearning.py
py/tests/unit/with_runtime_sparkling/test_drf.py
py/tests/unit/with_runtime_sparkling/test_gbm.py
py/tests/unit/with_runtime_sparkling/test_glm.py
py/tests/unit/with_runtime_sparkling/test_gridsearch.py
py/tests/unit/with_runtime_sparkling/test_kmeans.py
py/tests/unit/with_runtime_sparkling/test_xgboost.py

Requires jh/sw-1585 to be merged first

[SW-1577] Generic logic to test parametr passing to algo wrappers on PySParkling

---

bin/run-example.sh
bin/run-example2.cmd
bin/run-python-script.sh
bin/run-sparkling.sh
bin/run-sparkling2.cmd
bin/sparkling-env.cmd
bin/sparkling-env.sh
bin/sparkling-shell
bin/sparkling-shell2.cmd
build.gradle
examples/build.gradle
gradle-spark2.1.properties
gradle-spark2.2.properties
gradle-spark2.3.properties
gradle-spark2.4.properties
gradle/bench.gradle
gradle/itest.gradle
gradle/sparkTest.gradle
py/build.gradle

Driven by this H2O's change which removes support for Java 1.7 https://github.com/h2oai/h2o-3/pull/3783

[SW-1492][Spark-2.1] Switch minimal java version for Java 1.8

---

examples/pipelines/hamOrSpamMultiAlgo.script.scala
examples/src/scriptsTest/scala/water/sparkling/scripts/ScriptsTestSuite.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
py/examples/pipelines/ham_or_spam_multi_algo.py
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala

@mn-mikke I will wait for the tests to finish, but this change should be final.
What we need to do is to store the names of the original features, but after the "flattening" of structs

[SW-1618] Correctly handle feature names during prediction time

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
doc/src/site/sphinx/configuration/configuration_properties.rst

This reverts commit 2f02ad8e3c7cbd2ffeeae6a3f6eb5b806acd4526.

[SW-1645] Allow to specify kill on unhealthy cloud in case of manual cluster start of external backend

---

jenkins/Jenkinsfile-release

This change should help us with failing uploads to conda in our release pipeline

[SW-1662] Retry for conda upload in release pipeline

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

See https://0xdata.atlassian.net/browse/SW-1698

[SW-1698] Remove unnecessary Log level change

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

Depends on https://github.com/h2oai/h2o-3/pull/4044/files

[SW-1695][Separation] In Rest API based context, we take H2O build info from H2O object, we need to use rest api

---

gradle/wrapper/gradle-wrapper.properties

https://github.com/gradle/gradle/releases Gradle community strongly suggests to upgrade to this fix release

[SW-1702] Upgrade to Gradle 5.6.4

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

Ensure we have consistent naming -> we should not use word `extended` for the name of env variable in automatic mode to store the driver jar as it is no longer extended

[SW-1725] Change name of ENV property using in automatic mode to pass h2o driver

---

jenkins/Jenkinsfile-from-h2o-branch

I've only set `buildAgainstH2OBranch` to `true`, otherwise the configuration files is the same as `Jenkins.file`

[SW-1734] Configuration File for Tests against H2O Branch

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala
doc/src/site/sphinx/deployment/backends.rst
doc/src/site/sphinx/migration_guide.rst

Depends on release of H2O 3.26.0.11 with this change https://github.com/h2oai/h2o-3/pull/4056/files

[SW-1710] Enable client mode in Sparkling Water

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendConf.scala
core/src/main/scala/org/apache/spark/network/Security.scala
doc/src/site/sphinx/configuration/configuration_properties.rst

Depends on https://github.com/h2oai/h2o-3/pull/4073

[SW-1711] Fix propagation of internal security conf in Sparkling Water

---

py/src/ai/h2o/sparkling/H2OContext.py

All the information about state should be stored on the backend. The stopped field is already available on the backend & this PR makes use of it

[SW-1758] Reuse stopped field from scala backend

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

Depends on https://github.com/h2oai/h2o-3/pull/4111

[SW-1737] Ensure the client has full flatfile in external backend

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

[SW-1765] Hide internal fields in H2OContext

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala

We now require web enabled on external backend and this simplifies a code a little bit

[SW-1787] Obtaining nodes can be done via rest API in all cases on External backend

---

core/build.gradle
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalReadConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/RestApiUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/RestCommunication.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2OSparkEntity.scala
core/src/main/scala/org/apache/spark/h2o/converters/ReadConverterCtxUtils.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ChunkServlet.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/ChunkAutoBufferReader.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/ChunkAutoBufferWriter.scala
utils/src/main/scala/ai/h2o/sparkling/utils/Base64Encoding.scala

Related PR: https://github.com/h2oai/h2o-3/pull/4217

[SW-1840] Read Chunks via REST API

---

ml/src/test/scala/ai/h2o/sparkling/ml/algos/MultinomialPredictionTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/OrdinalPredictionTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionOrdinal.scala

Depends on https://github.com/h2oai/sparkling-water/pull/1817/files

[SW-1897] In prediction which do classification, be more explicit about relations about class and probabilities

---

jenkins/build.gradle

The reason was that Spark in local-cluster mode tried to create directory $SPARK_HOME/work but it did not have correct rights, that is why the tests in local-cluster were failing.

[SW-1963] Fix execution of tests using local-cluster

---

gradle.properties

Note: requires some fixes on Mojo side first

[SW-1862] Upgrade MOJOv2 to 2.2.0

---

core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConverter.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/ChunkAutoBufferReader.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/SerdeUtils.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/Utils.scala

We were still referencing one class from H2O

[SW-2008] Fix compile after removing code for external backend from H2O

---

benchmarks/build.gradle
benchmarks/src/main/terraform/aws/main.tf
benchmarks/src/main/terraform/aws/variables.tf

I had to create a new VPC with a subnet, the current one didn't work

[SW-1996] Benchmarks are Failing on Exception "VpcLimitExceeded"

---

gradle.properties

For more details, see the JIRA ticket https://0xdata.atlassian.net/browse/SW-2065.

[SW-2065] Fix Deployment of Artifacts to Maven Central

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
ml/src/main/scala/ai/h2o/sparkling/ml/internals/H2OModel.scala
ml/src/test/scala/ai/h2o/sparkling/ml/backend/H2OModelTestSuite.scala

While ago I have promised to write tests for getCurrentMetrics. I have tried to improve it a bit as well ( this code hasn't been released, so we can afford it)

[SW-2061] Improve and test getCurrentMetrics on H2OModel

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

Also internal backend can run in rest api mode, ensure this is reflected in this method

[SW-2112] Update getOrCreate method after enabling rest api in py/r as well

---

core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OClientUtils.scala
core/src/main/scala/water/support/H2OFrameSupport.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/SupportedRDDConverterTest.scala
core/src/test/scala/ai/h2o/sparkling/frame/H2OFrameTestSuite.scala
doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala

JIRA for removal in 3.32 is here https://0xdata.atlassian.net/browse/SW-2134

[SW-2092] Switch H2OFrameSupport methods to use rest api

---

dist/build.gradle

This PR  reverts commit 02735ca9

Revert "[SW-2119] Make SW Compatible with Older Versions of Steam (#1989)"

---

assembly/build.gradle
extensions/build.gradle

`scala.concurrent.Future` can't be shadowed since sparkling water calls `org.apache.spark.rpc.RpcEndpointRef.ask`.
Shadowing causing exceptions like:
```
Error: java.lang.NoSuchMethodError: org.apache.spark.rpc.RpcEndpointRef.ask(Ljava/lang/Object;Lscala/reflect/ClassTag;)Lai/h2o/scala/concurrent/Future;: at org.apache.spark.h2o.backends.internal.InternalH2OBackend$$anonfun$org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OWorkers$1.apply(InternalH2OBackend.scala:161): at org.apache.spark.h2o.backends.internal.InternalH2OBackend$$anonfun$org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OWorkers$1.apply(InternalH2OBackend.scala:160): at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234): at …
```

[SW-2172][FOLLOWUP] shadow only scala.compat.java8 and scala.concurrent.java8

---

py/src/ai/h2o/sparkling/H2OConf.py
py/src/ai/h2o/sparkling/H2OContext.py

[SW-2200] Ensure H2OContext can be created in PySparkling without numpy installed

---

ci/sparklingWaterPipeline.groovy

As long as the pipeline is green, I think we are good to go

[SW-2239] Use parallel build for H2O in the test pipeline

---

bin/build-kubernetes-images.sh
ci/Jenkinsfile-kubernetes
doc/src/site/sphinx/deployment/kubernetes.rst
kubernetes/build.gradle

This PR is base for implementing SW tests on K8s in External backend.

[SW-2261] Start External H2O Cluster within Kubernetes tests

---

ci/Jenkinsfile-kubernetes
doc/src/site/sphinx/deployment/kubernetes.rst
kubernetes/src/r/initTest.R

Waiting for k8s tests to pass https://sparkling-jenkins.h2o.ai/job/TESTS_KUBERNETES/job/jh%2FSW-2292/4/, otherwise the change is final

[SW-2292] Kubernetes tests in External backend, cluster & client mode

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala

Gave @pastx custom build with this change and waiting for confirmation whether it helped or not

[SW-2302] Fix org.apache.hadoop.fs.FsUrlConnection cannot be cast to java.net.HttpURLConnection

---

core/src/main/scala/ai/h2o/sparkling/backend/api/ServletRegister.scala
core/src/main/scala/ai/h2o/sparkling/backend/api/ShutdownServlet.scala
core/src/main/scala/ai/h2o/sparkling/backend/api/dataframes/DataFramesServlet.scala
core/src/main/scala/ai/h2o/sparkling/backend/api/h2oframes/H2OFramesServlet.scala
core/src/main/scala/ai/h2o/sparkling/backend/api/rdds/RDDsServlet.scala
core/src/main/scala/ai/h2o/sparkling/backend/api/scalainterpreter/ScalaInterpreterServlet.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/ProxyStarter.scala

This is to allow Steam to properly stop Sparkling Water when calling shutdown endpoint

[SW-2305] Ensure that call /3/Shutdown handles H2OContext stop in case of Sparkling Water ( via Flow Proxy)

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OAutoMLTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2ODRFTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OGridSearchTestSuite.scala

I was able to reproduce the issue just on grid search, but added tests for Automl and one algo based on H2OAlgorithm just to be sure

[SW-2312] JsonSyntaxException when using setNfolds() on algorithm

---

bin/sparkling-env.sh

See https://0xdata.atlassian.net/browse/SW-1510

[SW-1510] Fix misleading error message from incompatible Java version

---

build.gradle
core/build.gradle

We shouldn't anyway include transitive dependencies of h2o-hive project, thanks @honzasterba for pointing that out!

[SW-2355] Fix build after hive changes on H2O side

---

booklet/src/SparklingWaterBooklet.tex
booklet/src/sections/what_is_h2o.tex

I will probably create PR for each section so it is easier to review.
At this stage, I'm updating the booklet so it is valid on our release branch

[SW-2375] Update what is H2O section in Booklet and main tex document

---

core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
core/src/test/scala/ai/h2o/sparkling/H2OFrameTestSuite.scala

(cherry picked from commit 3f4522cdd313d7ac9d345054e836ad73fd36efa3)

[SW-2407] Add renameCol method to H2OFrame Scala API

---

ci/Jenkinsfile-kubernetes

Kubernetes tests keep the resources on-line in case some tests fails

[SW-2416] Kubernetes tests should clean up the environment in case of an error

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AlgorithmConfigurations.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AutoMLConfiguration.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/GridSearchConfiguration.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/ParameterSubstitutionContext.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/AlgorithmTemplateBase.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/ParametersTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/ParametersTemplate.scala
doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/DeprecatedWeightCol.scala
py/src/ai/h2o/sparkling/ml/params/DeprecatedWeightCol.py

The parameter is not supported by the implementation of KMeans in H2O-3 and won't be implemented in near future.

[SW-2434] Deprecate 'weightCol' Parameter on H2OKmeans

---

py/src/ai/h2o/sparkling/ml/params/H2OGridSearchParams.py
py/tests/unit/with_runtime_sparkling/test_gridsearch.py

https://0xdata.atlassian.net/browse/SW-2448

[SW-2448] The Method `getAlgo()` on H2OGridSearch Supports only a Subset of Algorithms

---

core/build.gradle
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterFullCategoricalTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterLimitedCategoricalTestSuite.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/CategoricalConstants.java
extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/CollectCategoricalDomainsTask.java
extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ImportFrameHandler.scala

https://h2oai.atlassian.net/browse/SW-2476

[SW-2476] asH2OFrame Could Fail on ArrayIndexOutOfBoundsException

---

py/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
py/tests/unit/with_runtime_sparkling/test_xgboost.py
scoring/src/main/scala/ai/h2o/sparkling/ml/params/NullableStringArrayArrayParam.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/ParameterConstructorMethods.scala

Related H2O PR (it broke SW build): https://github.com/h2oai/h2o-3/pull/5102

[SW-2482] Expose Interaction Constraints on H2OXGBoost

---

doc/src/site/sphinx/deployment/load_mojo.rst
doc/src/site/sphinx/deployment/load_mojo_pipeline.rst

https://h2oai.atlassian.net/browse/SW-2473

[SW-2473] Update Sparkling Water MOJO Deployment Documentation

---

assembly/build.gradle
build.gradle

[SW-2488] Enable Generation of Dependency License Report as CSV

---

py/tests/unit/with_runtime_sparkling/test_gam.py
py/tests/unit/with_runtime_sparkling/test_glm.py
py/tests/unit/with_runtime_sparkling/test_mojo.py

https://h2oai.atlassian.net/browse/SW-2500

[SW-2500] Temporarily Disable Beta Constraints Tests

---

booklet/src/sections/kubernetes.tex
ci/Jenkinsfile-kubernetes
doc/src/site/sphinx/deployment/kubernetes.rst
kubernetes/build.gradle
kubernetes/src/r/initTest.R

Sparklyr 1.5.1 with the fix for SW has been released. I've tested the effect of changes manually.

[SW-2489] Revert Sparklyr  Downgrade to 1.3.1

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/MOJOModelTemplate.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/MOJOParameterTestSuite.scala
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py
scoring/src/main/scala/ai/h2o/sparkling/ml/params/NullableFloatArrayParam.scala

Jira: https://h2oai.atlassian.net/browse/SW-2501
Reported issue: https://github.com/h2oai/sparkling-water/issues/2418

[SW-2501] The "classSamplingFactors" Parameter Throws Exception During Deserialization

---

doc/src/site/sphinx/configuration/internal_backend_tuning.rst
doc/src/site/sphinx/deployment/aws_emr.rst

JIRA ticket: https://h2oai.atlassian.net/jira/software/c/projects/SW/issues/SW-2499
Answer from AWS team: https://forums.aws.amazon.com/thread.jspa?threadID=332806

[SW-2499] Document Properties for running SW on EMR 5.32

---

doc/src/site/sphinx/about.rst

See https://h2oai.atlassian.net/browse/SW-2522.

[SW-2522] Docs: Add licensing information

---

ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoder.scala
ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala
py-scoring/src/ai/h2o/sparkling/ml/params/H2OTargetEncoderMOJOParams.py
py-scoring/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
py/src/ai/h2o/sparkling/ml/features/H2OTargetEncoder.py
py/tests/unit/with_runtime_sparkling/test_target_encoder.py
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderBase.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderMOJOModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OTargetEncoderMOJOParams.scala

The pr depends on https://github.com/h2oai/h2o-3/pull/5231

[SW-2525] Expose Interactions on Target Encoder

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/AlgorithmTemplateBase.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/HasGamCols.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OGAMTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/MOJOParameterTestSuite.scala
py-scoring/src/ai/h2o/sparkling/ml/params/HasGamCols.py
py-scoring/src/ai/h2o/sparkling/ml/params/HasGamColsOnMOJO.py
py/src/ai/h2o/sparkling/ml/algos/H2OAlgorithm.py
py/tests/unit/with_runtime_sparkling/test_gam.py
py/tests/unit/with_runtime_sparkling/test_gridsearch.py
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py
scoring/src/main/scala/ai/h2o/sparkling/ml/params/HasGamColsOnMOJO.scala

Related H2O PR: https://github.com/h2oai/h2o-3/pull/5254

[SW-2542] Reflect Changes on GAM According to PUBDEV-7860

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AlgorithmConfigurations.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/DeprecatedDistribution.scala
py/src/ai/h2o/sparkling/ml/params/DeprecatedDistribution.py

This PR reverts commit 3ce0a2ab in rel-3.32.1 (forked from master)

Revert "[SW-2451] Remove Deprecated Parameter `distribution` on H2OGLM (#2366)"

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AlgorithmConfigurations.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/DeprecatedWeightCol.scala
py/src/ai/h2o/sparkling/ml/params/DeprecatedWeightCol.py

This reverts commit 432b3768 in rel-3.32.1 (forked from master)

Revert "[SW-2446] Remove Deprecated  Parameter `weightCol` on H2OKmeans (#2365)"

---

ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OAutoMLTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/RegressionPredictionTestSuite.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAnomaly.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala

https://h2oai.atlassian.net/browse/SW-2528

[SW-2528] GLM Model Trained via AutoML Throws Exception when Contributions Enabled

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
py/src/ai/h2o/sparkling/H2OContext.py
r/src/R/ai/h2o/sparkling/H2OContext.R

(for PySparkling and RSparkling client)

[SW-2551] Introduce Configuration Property for Setting CA Certificate(s)

---

core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala

The problem description in https://h2oai.atlassian.net/browse/SW-2550

[SW-2550] Expose SW Property Allowing for Deployment to All Discovered Executors

---

doc/src/site/sphinx/ml/ml.rst
doc/src/site/sphinx/ml/sw_deep_learning.rst

A simple tutorial proving that SW is able to train DL models (checklist item).

[SW-2547] Add Simple Tutorial for H2ODeepLearning

---

extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ImportFrameHandler.scala

[SW-2553] FinalizeFrame should log information about Frame

---

bin/sparkling-env.sh
booklet/src/sections/deployment.tex
booklet/src/sections/starting.tex
doc/src/site/sphinx/deployment/sw_google_cloud_dataproc.rst
doc/src/site/sphinx/pysparkling.rst
py/build.gradle
py/conda/h2o_pysparkling_SUBST_SPARK_MAJOR_VERSION/meta.yaml
py/src/setup.py
templates/src/aws/install_sparkling_water.sh
templates/src/terraform/aws/modules/emr_deployment/main.tf

This PR is related to https://github.com/h2oai/h2o-3/pull/5500

[SW-2574] Remove Python Dependency on Colorama

---

examples/README.rst

https://h2oai.atlassian.net/browse/SW-2578

[SW-2578] Fix Link in Overview of Examples

---

py-scoring/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py

The method was returning `None`.

[SW-2572] Fix getMonotoneConstraints() on H2OGBM and H2OXGBoost MOJO model

---

doc/build.gradle
doc/src/site/sphinx/deployment/load_mojo.rst
doc/src/site/sphinx/deployment/load_mojo_pipeline.rst
gradle/utils.gradle

Documentation for Spark 2.1 - 2.3:
Documentation for Spark 2.4+:

[SW-2604] Mention Workaround for SPARK-21945 in SW Documentation

---

.gitignore
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/EntitySubstitutionContext.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/MetricsConfigurations.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/ModelMetricsTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/ScalaEntityTemplate.scala
doc/build.gradle
doc/src/main/scala/ai/h2o/sparkling/doc/generation/MetricsTemplate.scala
doc/src/main/scala/ai/h2o/sparkling/doc/generation/MetricsTocTreeTemplate.scala
doc/src/main/scala/ai/h2o/sparkling/doc/generation/Runner.scala
doc/src/site/sphinx/deployment/load_mojo.rst
doc/src/site/sphinx/index.rst
scoring/src/main/scala/ai/h2o/sparkling/ml/metrics/MetricsDescription.java

Generated documentation:
[metrics_H2OAnomalyMetrics.rst.txt](https://github.com/h2oai/sparkling-water/files/7078219/metrics_H2OAnomalyMetrics.rst.txt)
[metrics_H2OAutoEncoderMetrics.rst.txt](https://github.com/h2oai/sparkling-water/files/7078220/metrics_H2OAutoEncoderMetrics.rst.txt)
[metrics_H2OBinomialGLMMetrics.rst.txt](https://github.com/h2oai/sparkling-water/files/7078221/metrics_H2OBinomialGLMMetrics.rst.txt)
[metrics_H2OBinomialMetrics.rst.txt](https://github.com/h2oai/sparkling-water/files/7078222/metrics_H2OBinomialMetrics.rst.txt)
[metrics_H2OClusteringMetrics.rst.txt](https://github.com/h2oai/sparkling-water/files/7078223/metrics_H2OClusteringMetrics.rst.txt)
[metrics_H2OCommonMetrics.rst.txt](https://github.com/h2oai/sparkling-water/files/7078224/metrics_H2OCommonMetrics.rst.tx …

[SW-2587] Generate Documentation for All Possible Metrics Classes on H2OMOJOModel

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/MOJOModelAPIRunner.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/MetricsFactoryTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/r/MetricsFactoryTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/r/ModelMetricsTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/r/REntityTemplate.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
py/tests/unit/with_runtime_sparkling/test_mojo.py
r/build.gradle
r/src/R/ai/h2o/sparkling/ml/metrics/H2OMetrics.R
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModel.R
r/src/tests/testthat/testMojo.R
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala

Generated files:
[H2OAnomalyMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091751/H2OAnomalyMetrics.R.txt)
[H2OAutoEncoderMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091753/H2OAutoEncoderMetrics.R.txt)
[H2OBinomialGLMMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091754/H2OBinomialGLMMetrics.R.txt)
[H2OBinomialMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091755/H2OBinomialMetrics.R.txt)
[H2OClusteringMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091756/H2OClusteringMetrics.R.txt)
[H2OCommonMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091757/H2OCommonMetrics.R.txt)
[H2OGLRMMetrics.R.txt](https://github.com/h2oai/sparkling-water/files/7091758/H2OGLRMMetrics.R.txt) …

[SW-2589] Expose Model Metrics as Objects on H2OMOJOModel in R API

---

.github/workflows/snyk-scan.yml

This is done as a part of [standardizing/Restructuring the Snyk security vulnerability scanning process](https://github.com/h2oai/h2o-infra/issues/49) across all the products and their main components. GH actions are used for this
**Main Requirements:**
- Run local `Snyk tests` for PRs
- Run `Snyk monitor` for all the main branches/release branches/tags and users can explore the Snyk reports in Snyk UI using provided links in Workflow logs
- Group the components related to one main product (**SPARKLING-WATER**) in [Snyk UI ](https://app.snyk.io/org/h2oai/projects) 
Please refer to the main issue **https://github.com/h2oai/h2o-infra/issues/49** for more details 
**Note:** Please note that the existing integrations will be removed once this is merged Since this new integration is required …

[SW-2653] Snyk Security Vulnerability Scanning Integration

---

ml/src/main/scala/ai/h2o/sparkling/ml/utils/EstimatorCommonUtils.scala

I was trying to replicate the h2o python client behavior but I'm not sure if that's enough

[SW-2634] Display Warnings Coming from ModelBuilders

---

py-scoring/build.gradle
py/build.gradle

Version 1.7.2 fixes support for python 2.7.

[SW-2667] Remove pypandoc Version Fix

---

gradle.properties

Related issue: https://github.com/h2oai/mojo2/issues/1510

[SW-2716] Upgrade MOJO runtime to 2.7.8

---

kubernetes/build.gradle

During the last fix release, I had to do build docker images manually. I had to change Docker-R image in the same way as proposed by this PR.

[SW-2719] Fix Building of RSparkling Docker Images

---

ci/Jenkinsfile
ci/Jenkinsfile-benchmarks
ci/Jenkinsfile-databricks
ci/Jenkinsfile-from-h2o-branch
ci/Jenkinsfile-kubernetes
ci/Jenkinsfile-nightly-from-h2o-branch
ci/docker/Jenkinsfile-build-docker

Number of kept builds increased from 10 to 30.

[SW-2712] Increase the number of builds kept in Jenkins build history

---

ci/Jenkinsfile-databricks
ci/Jenkinsfile-kubernetes

The same problem as in [#2804](https://github.com/h2oai/sparkling-water/pull/2804)

[SW-2726][FOLLOWUP] Fix K8s and DBC tests after jenkins migration

---

core/src/main/scala/ai/h2o/sparkling/H2OColumn.scala
core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
core/src/main/scala/ai/h2o/sparkling/backend/H2OFrameRelation.scala
core/src/test/scala/ai/h2o/sparkling/backend/api/dataframes/DataFramesServletTestSuite.scala
py/tests/unit/with_runtime_sparkling/test_mojo.py

see [SW-2736](https://h2oai.atlassian.net/browse/SW-2736) and https://github.com/h2oai/sparkling-water/issues/2811

[SW-2736] Frame Metadata Retrieval Downloads Unnecessary Information

---

bin/sparkling-env.cmd

Fixed reference to Scala version (in gradle) and provided binaries.

[SW-2732] Fix startup scripts for Windows environment

---

gradle.properties

After merging this PR, we will create branch rel-3.40.

[SW-2771] Upgrade to H2O 3.40.0.1

---

.github/CODEOWNERS
.github/pull_request_template.md

**Requirement**
- There is a requirement by Michal on mandatory rules and settings that should be configured in GH repos to cater to the SOC2 compliance requirements.
- The document below covers an overview of the suggested and recommended Github Repository Baseline Settings;
- https://h2oai.atlassian.net/wiki/spaces/DEVOPS/pages/3921739777/GitHub+Repository+Baseline+Settings
- [Software Development-1.pdf](https://github.com/h2oai/sparkling-water/files/11731926/Software.Development-1.pdf)
**Issues**
- Default branch should be the main branch.
- Snyk scan should be required.
- Following branch rules to be enforced as per the document;
- https://h2oai.atlassian.net/wiki/spaces/DEVOPS/pages/3921739777/GitHub+Repository+Baseline+Settings
**Changed**
- Have added a CODEOWNERS file & PR …

[DevOps] SOC2 Compliance Requirements

---

ci/docker/Jenkinsfile-build-docker
gradle-spark3.2.properties
gradle-spark3.4.properties
gradle.properties

[GH-5648] Upgrade Spark in Testing Image to 3.4.1 and 3.2.4

---

gradle.properties

[GH-5651] Upgrade to H2O 3.42.0.2

---

README.rst
ci/Jenkinsfile-release
gradle/publish.gradle
r-cran/src/DESCRIPTION
r/src/DESCRIPTION

Part 1/2, part 2 will introduce a new solution for release notes

[GW-5650] Remove text mentioning JIRA

---

build.gradle
gradle/publish/uploadToNexus.sh

[GH-5684] Revert "Fix release process ignoring Nexus upload errors"

---

gradle.properties

Closes https://github.com/h2oai/sparkling-water/issues/5748

[GH-5748] Upgrade H2O to 3.46.0.6

---

extensions/src/main/scala/water/fvec/H2OFrame.scala

fix parse setup
