h2oai/sparkling-water

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/H2OSchemaUtils.scala

This fixes an apparent bug when converting SchemaRDDs with more than 128 columns to DataFrames.
The code in H2OSchemaUtils seems to convert column indexes to Bytes (from Ints), which overflows if there are more than 128 columns. This eventually resulted in an ArrayIndexOutOfBoundsException when getting the column value.
I haven't tested this extensively -- I just changed everything I could see in H2OSchemaUtils that looked like an index from a Byte to Int and verified that it fixed the error, so it certainly needs somebody who knows the code better to check it.

Fix overflow problem with converting SchemaRDD with more than 128 cols

---

examples/README.md

Corrected the erroneous import statements of Scala. ( in /examples/README.md)
validated in sparkling-water-1.3.5.
if you encounter any problems please contact me.

fix Wrong Scala import sentence

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

A small PR to enable the use of Sparkling Water with the Spark 1.4.0. The PR will work with Spark 1.3 though.
The key 'problem' is that a separation has been made between internal and external data types as of Spark 1.4. Using the current version of Sparkling Water will lead to a number of ClassCastExceptions when using Strings (it will try to cast them to a UTF8String which is the internal String implementation).

Adapt H2OContext for usage in Spark 1.4.0+

---

core/src/main/scala/org/apache/spark/h2o/DefaultSource.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/H2ORelation.scala
core/src/main/scala/org/apache/spark/h2o/H2OSchemaUtils.scala
core/src/main/scala/org/apache/spark/sql/H2OSQLContextUtils.scala
py/pysparkling/context.py

@mklechan observed slow down of `select count(*) from h2oFrame` query after `asDataFrame` call during handling larger datasets.
The slow down was caused by Spark querying metadata which we attached during transformation
of H2OFrame to Dataset.
The fix introduces an additional option for asDataFrame call to control transfer
of metadata from H2OFrame to DataFrame.

[SW-168] a flag to control transfer of metadata from H2OFrame to DataFrame

---

core/src/main/scala/org/apache/spark/rdd/H2ORDD.scala

Unused fields `jc`, `cs, `ccr` were removed.

[SW-174] Cleanup of H2ORDD - duplicated fields removed.

---

repl/src/main/scala/org/apache/spark/repl/h2o/H2OIMain.scala
repl/src/main/scala/org/apache/spark/repl/h2o/H2OInterpreter.scala

This PR cleans REPL a little bit.
The initialization piece of code does not have to have session id as part of it's name. It is just used to test wheter the compiler has been successfully initialised. We don't therefore have to change the initialization code and thus can remove it. ( the interpreter test runs anyway )
Also the code in `setupClassNames` was simplified. This change also allows us to use the same code in this method among all spark versions for scala 2.10 and 2.11. 
Also remove unnecessary setting of classpath since it's always overriden in `createInterpreter` method.

[SW-177] REPL simplification

---

core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/main/scala/org/apache/spark/listeners/H2OSparkListener.scala

**Why the fix:**
CDH added a new method to `SparkListener` (which was added in Spark2.0) https://github.com/cloudera/spark/blob/cdh5.7.1-release/core/src/main/scala/org/apache/spark/scheduler/SparkListener.scala#L245 We're getting an `AbstractMethodError` when running on CDH5.7.1 since the trait against which we're compiling (Spark 1.6) doesn't have `onExecutorAdded`.
Adding the `onExecutorAdded` has to be done in a separate trait/class, adding it on the anonymous class won't work due to how Scala compiles it. 
**How this was tested:**
Manually ran `./sparkling-shell --num-executors 2 --executor-memory 6g --driver-memory 6g --master yarn-client --conf spark.dynamicAllocation.enabled=false`:
```
import org.apache.spark.h2o._
val hc = H2OContext.getOrCreate(sc) …
```

[SW-176] Adds a missing method from the CDH SparkListener trait.

---

core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDDLike.scala

This PR fixed problem in H2ODataFrame where we are not allowed to use methods requiring H2O backend since in future external cluster mode, h2o is not running in a spark executor.
Tests are passing.
@mmalohlava Pls let me know if it looks good to you.

[SW-185] Post-refactorization and post-integration fixes

---

.travis.yml

This solve travis issue-5227 - bufferflow in getHostname by
seting short hostname (<64characters).
See:
- ISSUE-5227: https://github.com/travis-ci/travis-ci/issues/5227
- https://docs.travis-ci.com/user/hostname

[BUILD] Fix in travis build file.

---

examples/build.gradle
examples/flows/index.list

Is this enough? The [Jira](https://0xdata.atlassian.net/browse/SW-128) mentioned something about integrating into github but they were already in github? 
The flows are now packaged with the core jar and show up in the FlowUI `Help > examples` together with core H2O examples when running SW.

[SW-128] Move flows into core so they are shown in flowui

---

core/src/test/scala/org/apache/spark/h2o/utils/SparkTestContext.scala

Previously used `InetAddress.getLocalHost.getHostAddress` as client IP can return an IP address which is not supported by an H2O node since it internally goes through a nameserver and H2O supports only IPs from network interfaces.
This is a setting depending on where it runs so I think system property isn't a bad idea, thoughts?

[MINOR] Client IP fetched from system properties.

---

core/src/test/scala/water/api/ScalaCodeHandlerSuite.scala
repl/src/main/scala/org/apache/spark/repl/h2o/H2OInterpreter.scala

Right now this package is not imported and for example when specifying saving mode in datasource api using`SaveMode.Append `
it doesn't know the class SaveMode.
It's more convenient for the user not having to import this package.

[SW-192] Add org.apache.spark.sql._ to packages imported by default in REPL

---

ml/src/main/resources/META-INF/services/water.api.RestApi

Without this the `hex.Register` class won't be found by `ServiceLocator`

[MINOR] Adds the services file in ml module for RestAPI interface

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedH2OConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendConf.scala
core/src/main/scala/water/util/LogUtil.scala

The [Jira](https://0xdata.atlassian.net/browse/SW-71) mentioned adding them on `H2OContext` but setting those values on those instances will have no effect after `init()` so I added them to the config classes.
Thoughts?

[SW-71] Added setLogLevel on H2O internal config

---

core/src/main/scala/water/support/DeepLearningSupport.scala
core/src/main/scala/water/support/GBMSupport.scala
core/src/main/scala/water/support/H2OFrameSupport.scala

Methods in `water.support` classes should be defined as `def method[T <: Frame](fr: T)` instead of `def method(fr: H2OFrame)`

[SW-201] Methods in water.support classes should be defined using new api

---

py/README.rst

Made a number of typo/grammar and name changes in the PySparkling README file.

Updated PySparkling docs: fixed typos and naming conventions

---

ml/src/main/scala/org/apache/spark/ml/spark/ProgressListener.scala
ml/src/main/scala/org/apache/spark/ml/spark/models/svm/SVM.java

Not 100% but close. SVM has one main spark job that is ran in a for loop for the number of iterations specified by the user (default 100) - it's called `treeAggregate`. There are a few other jobs that run before (3-5) that's why it's not 100% accurate but I think it's close enough to leave it as it is - otherwise we'd have to find all the jobs spark uses for SVM and keep track of all the changes they do to them.
I'm using RDD info to update a job only when a job is submitted on the appropriate RDD (we can have multiple models being built at the same time).
Thoughts?

[SWPRIVATE-18] Progress bar update for SVM

---

py/pysparkling/context.py

This PR fixes the problem of getting wrong output from `__str__` method on h2o context. 
The check for `has_attr` always returned false since it was called on `self` and field `is_initialized` was set on h2o, so the field weren't available in all cases.
This fixes the problem by setting the` is_initialized` attribute on `h2o_context` instance

[SW-196] Fix wrong output of __str__ on H2OContext

---

gradle/scala.gradle

Gradle is deprecating use of ant-based compiler and options connected to it.
`scalaCompileOptions.useCompileDaemon` is now set to false automatically and will be completely removed in Gradle 3.0
`scalaCompileOptions.useAnt` is also automatically set to false ( trying to assign it will trigger the deprecation warning ) and will also be removed in Gradle 3.0

[SW-212] Fix deprecation warning in gradle build system

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/converters/DatasetConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDDLike.scala
core/src/main/scala/org/apache/spark/h2o/utils/CrossScalaShared.scala
core/src/main/scala_2.10/org/apache/spark/h2o/utils/CrossScalaUtils.scala
core/src/main/scala_2.11/org/apache/spark/h2o/utils/CrossScalaUtils.scala

This PR fixes deprecation warnings by introducing desired meta-annotaions.
This PR also introduces new trait and object. New trait `CrossScalaShared` is used to specify methods which each scala-version specific implementation should have and `CrossScalaUtils` is object implemented for each scala version with implementation tailored for specific scala.
This way we can utilities functions which will work on both scala versions and won't produce deprecations warnings/other problems in both cases.

[SW-169] Fix deprecation warnings

---

py/build.gradle
py/setup.py

This PR does exactly what it says. All temporary artefacts created during assembling python package and the output artefacts are put inside `build` directory.

[SW-208] Generate all temporary and output artefacts into build dir

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/SpreadRDDBuilder.scala

Right now the wrong `SparkConf` was used in `SpreadRDDBuilder` in sparkling water for Spark 1.5.
This PR fixes this problem by passing the builder `sparkConf` from h2oContext instead of from sparkContext. It is because we set additional properties to `sparkConf` in h2o context and we need to have these fields available.

[SW-207] Use correct spark conf in SpreadRDDBuilder

---

bin/pysparkling
bin/run-example.sh
bin/run-python-script.sh
bin/run-sparkling.sh
bin/sparkling-env.sh
bin/sparkling-shell

This PR implements 2 things:
- Don't fail immediately if SPARK_HOME isn't set: Sometimes the Spark is installed via package manager, or some other means, like, Cloudera parcells.  In this case the `SPARK_HOME` isn't set explicitly, but `spark-shell` & `spark-submit` are available in the `PATH`.  This patch adds for this case, and fail only if both `SPARK_HOME` isn't set, and `spark-submit` isn't available in the `PATH`.  It also fixes explicit use of `FAT_JAR` variable instead of using `FAT_JAR_FILE` that points to the full path to `FAT_JAR`;
- Don't change current directory in scripts: Sometimes you need to run the `spark-shell` or other command from some directory with data, etc., but all scripts right now change directory to the `TOP_DIR`.

Improve shell scripts

---

r/rsparkling/R/h2o_context.R
r/rsparkling/tests/test_h2o_name.R

*Right now `as_h2o_frame` creates the name of the frame as "frame_rdd_xxx" but it should allow the user to pass actual name of frame: as_h2o_frame(table, "myTable").
*This PR solves this issue.

[SW-219] RSparkling: as_h2o_frame should properly name the frame

---

r/rsparkling/DESCRIPTION

Fix for a NOTE on invalid url
```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Erin LeDell <erin@h2o.ai>’
New submission
Non-FOSS package license (file LICENSE)
Found the following (possibly) invalid URLs:
URL: https://jira.h2o.ai
From: DESCRIPTION
Status: Error
Message: libcurl error code 7
Failed to connect to jira.h2o.ai port 443: Connection timed out
```
we do have ssl on our jira, but not on jira.h2o.ai, so it cannot be used here

[SW-232] rsparkling: fix CRAN note on invalid url

---

bin/sparkling-env.cmd
bin/sparkling-shell2.cmd

This commit fixes several problems in windows scripts
- find instead of findstr was used to find string
- gradle.properties has linux line ending, by using type command we print the result on screen first with correct line endings
and then it can be processed later
- scala version wasn't detected ( it tried to get scala version from sparkVersion field)

[SW-230] Fix windows scripts

---

core/build.gradle
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala
core/src/test/scala/org/apache/spark/h2o/utils/SharedSparkTestContext.scala
gradle/sparkTest.gradle
ml/build.gradle
ml/src/main/java/hex/schemas/SVMV3.java
ml/src/main/java/org/apache/spark/ml/spark/models/svm/SVM.java
ml/src/main/java/org/apache/spark/ml/spark/models/svm/SVMParameters.java
ml/src/main/scala/org/apache/spark/ml/FrameMLUtils.scala
ml/src/main/scala/org/apache/spark/ml/spark/models/MissingValuesHandling.java
ml/src/main/scala/org/apache/spark/ml/spark/models/svm/SVMModel.scala
ml/src/test/scala/org/apache/spark/ml/FrameMLUtilsTest.scala
ml/src/test/scala/org/apache/spark/ml/spark/models/svm/SVMModelTest.scala

- added NA value handling for SVM: mean imputation, skip, not allowed (old variant with an error message)
- means are calculated via RDD as H2OFrame.means() doesn't support enum columns
- changed the SVM model scoring/pojo generation to include column means when running in MeanImputation mode
- refactored tests a bit (frame creation now supports multi column frames)

[SWPRIVATE-16] NA handling for Spark algorithms

---

r/rsparkling/R/h2o_context.R
r/rsparkling/man/as_spark_dataframe.Rd

Some of our users expected a friendly default name once they convert their h2o frames back to spark data frames with `as_spark_dataframe`. Consider setting the default name to the name of the variable `x` which is what `sparklyr` does during `copy_to` and similar methods.

consider adding name parameter to as_spark_dataframe

---

r/examples/example_rsparkling.R
r/rsparkling/R/h2o_context.R
r/rsparkling/R/package.R
r/rsparkling/man/as_h2o_frame.Rd
r/rsparkling/man/as_spark_dataframe.Rd
r/rsparkling/man/h2o_context.Rd
r/rsparkling/tests/testthat.R
r/rsparkling/tests/testthat/test_aaa_install_spark.R
r/rsparkling/tests/testthat/test_transforms.R

rsparkling tests are now portable and _escaped on CRAN_, few minor fixes had been made to pass R check, also additional argument `strict_version_check` was added to make tests working (they can eventually be removed when we improve handling `h2o_context` in rsparkling.
I also added few comments in-line for clarify the changes.
To run unit tests we need to, should run on your local machine.
```sh
R CMD build r/rsparkling
export NOT_CRAN="true"
R CMD check rsparkling_0.1.0.tar.gz
```
To change spark/sw version use env vars:
```sh
export SPARKLINGWATER_VERSION="1.6.7"
export SPARK_VERSION="1.6.2"
export SPARKLINGWATER_VERSION="2.0.0"
export SPARK_VERSION="2.0.1"
```
other values has not been tested, if software in specific version is missing it will be installed (if valid).

making tests portable, and fixes to pass R check, closes SW-259

---

r/rsparkling/R/h2o_context.R
r/rsparkling/man/h2o_flow.Rd

* This PR adds a `strict_version_check` parameter to `h2o_flow`.
* This is needed to invoke H2O flow from a rsparkling instance if H2O versions do not match via the `h2o.init()` call.

Add strict version check to h2o_flow()

---

r/rsparkling/DESCRIPTION

rsparkling passed tests on h2o 3.8.3.3, which is closest available on CRAN for currently stated h2o dep. There is new rsparkling job _*-h2o-oldrel_ that also runs tests on v3.8.3.3, this will help to maintain support for stated dependency.

upgrade h2o dep to next available on CRAN, closes SW-240

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedH2OConf.scala
core/src/main/scala/org/apache/spark/network/Security.scala

---
<a name="Security"></a>
Both Spark and H2O support basic node authentication and data
encryption.
To enable it in Spark please check [their
documentation](http://spark.apache.org/docs/latest/security.html).
Security for H2O nodes can be enabled manually by generating all
necessary files, distributing them to all worker nodes as described in
[H2O's
documentation](https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/security.rst)
and passing the "spark.ext.h2o.internal_security_conf" to spark submit:
::
```
bin/sparkling-shell /
--conf "spark.ext.h2o.internal_security_conf=ssl.properties"
```
We also provide a utility method which will automatically generate all
files and enable security on all H2O nodes:
::
```
import org.apache.spark.network.Security
import …
```

[SWPRIVATE-12] Config for SSL and utility class for key creation

---

assembly/build.gradle

The H2O is using old version of Jetty (because of Java6) which is not compatible
with DBC Jetty (prepended on Spark classpath).

[SW-268] Relocation of Jetty classes into `ai.h2o` package

---

py/pysparkling/initializer.py

The problem was that `SparkContext#addJar` method improperly
register given path (representing `sparkling_water_assembly.jar` from egg file) in file server.
The problematic part of code:
```scala
if (master == "yarn" && deployMode == "cluster") {
val fileName = new org.apache.hadoop.fs.Path(uri.getPath).getName()
try {
env.rpcEnv.fileServer.addJar(new File(fileName))
} catch {
// ...
```
The code in fact register given file location under current directory (because of `new File(Path.getName())`).
Big warning - the fix use internal Spark API. For "yarn/cluster" mode it re-registers `sparkling_water_assembly.jar`
key under its original location provided by egg file.
Change:
- Use abs path to point to resource

[SW-272] Fix deployment issue of Sparkling Water on Azure/CDH

---

bin/sparkling-env.sh

Spark version detection was failing if GREP_OPTIONS were configured (for example, `GREP_OPTIONS=--color=always`).
The fix ignore grep options.

[SW-274] Ignore grep options

---

assembly-h2o/build.gradle

On case insensitive systems (such as MacOS X) there's a conflict when sending the `h2odriver_extended.jar` to Hadoop: `META-INF/LICENSE` (a license file) and `META-INF/license` (a folder containing some licenses). It makes the whole job fail to run.
Other solution would be to rename `license` folder to `licenses` but the uber jar also contains `META-INF/LICENSE.txt` which seems like the same content (Apache 2.0 license).
Similar, old, issue in Mahout for reference: https://issues.apache.org/jira/browse/MAHOUT-780

Fix extended SW uber jar

---

assembly-h2o/build.gradle

Running `./gradlew extendJar -x check -PdownloadH2O=cdh5.4` without that option fails because of our zip being too large.

Adds zip64 to assembly-h2o

---

core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/utils/ReflectionUtils.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala

Basic `DecimalType` support since Spark 2.x seems to use it in places where Spark 1.6 used `DoubleType`.

[FIXES] SW-303 adds support for Spark's DecimalType

---

core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/converters/DatasetConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/LabeledPointConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/PrimitiveRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/ProductRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala
repl/src/main/scala/org/apache/spark/h2o/H2OLogging.scala
repl/src/main/scala/org/apache/spark/repl/h2o/BaseH2OInterpreter.scala

CDH 5.9 rewrote the Logging class used by Spark (and us), changing some method signature, this PR adds those methods to a new trait and uses the new trait for logging instead.

Adds missing method to Spark's 1.6.2 Logging required by CDH

---

core/src/main/java/org/apache/spark/h2o/ui/SparklingWaterFlowPage.scala
core/src/main/java/org/apache/spark/h2o/ui/SparklingWaterUITab.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

The tab is attached after start of H2OContext.
The tab contains runtime info about Sparkling Water (for example, IP of Flow UI),
but also H2O build information.

[SW-327] Attach a Sparkling Water tab into Spark UI

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/network/Security.scala
gradle.properties

This this is the only change needed in SW as the actual encryption/decryption is done on the H2O core side. This will need an H2O core version bump to work properly (with actual encryption, as it is now it should still work but the data between Spark nodes and H2O nodes won't be encrypted).
EDIT: this PR needs changes from https://github.com/h2oai/h2o-3/pull/727 to be fully functional, without them it will be working fine except for external SSL mode.

[SW-316] Encryption support to newly created H2O external clusters

---

.travis.yml
README.md
core/src/main/scala/org/apache/spark/SparkSessionUtils.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala
dist/index.html
gradle.properties
py/README.rst

Includes:
- Spark dependency upgraded to Spark 2.1.0
- Documentation updated
- Test fixed: Added a parameter in the test to specify whether we allow plain (non-primitive) values to be nullable. A new version of Spark seems to suddenly decide that thay are nullable by default.

[SW-302] Upgrade Spark dependency to Spark 2.1.0

---

bin/sparkling-env.sh

This is Spark 2.1 specific fix, since the code used to detect Spark version was confused by reported Scala version:
```
➜  sparkling-water git:(master) ✗ $SPARK_HOME/bin/spark-submit --version 2>&1 | grep version | sed -e "s/.*version //" | sed -e "s/\([0-9][0-9]*.[0-9][0-9]*\).*/\1/"
2.1
2.11
```

[SW-342][SPARK-2.1] Fixed detection of Spark version.

---

README.md

Based on discussion:
http://apache-spark-developers-list.1001551.n3.nabble.com/spark-2-0-issue-with-yarn-td17440.html
https://issues.apache.org/jira/browse/SPARK-15343
the property `spark.hadoop.yarn.timeline-service.enabled=false` needs to be configured.
This change documents the resolution.

[SW-347] Launching SW on HDP Yarn cluster fails

---

core/src/main/java/org/apache/spark/h2o/ui/SparklingWaterUITab.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

This change:
- attach tags with created H2O job cluster:
- "h2o/sparkling-water"
- "sparkling-water/spark/<spark_job_app_id>"
- change name of create H2O Yarn job to `H2O_via_SparklingWater_<spark_job_app_id>`

[SW-333] Reporting via yarn resource manager UI

---

py/pysparkling/initializer.py

Zeppelin and other platforms bring additional ClassLoader on top of
Spark MutableURLClassLoader. That causes PySparkling to fail on missing `addURL` method.
The patch introduces code which finds the right Spark classloader in active thread classloader
chain. It does not do any error recovery if the classloader is not found.

[SW-357] Find the right ClassLoader to register SW jar

---

assembly-h2o/build.gradle

This is required for automating the creation of extended jar without hardcoding the supported hadoop versions

[SW-367 ] Add task to which prints all available hadoop versions

---

assembly-h2o/build.gradle

This change also removes the part where we parse version in format x.y from hadoop distro as the parsing is no longer needed. The distributions have always name like that

[SW-389] Print extended JAR  task every time when extendJar is called

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalReadConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2OFrameFromRDDProductBuilder.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDDLike.scala
core/src/main/scala/org/apache/spark/h2o/converters/LabeledPointConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/PrimitiveRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/ReadConverterCtxUtils.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
gradle.properties
py/pysparkling/conf.py

When timeout is reached, the exception is thrown. It is not catched on purpose since the spark will stop the job on the current executor and restart it. That should fix several intermittent issues together with  the problem of a few jobs never finishing ( the problem appeared and the confirmation never appeared)

[SW-398] Specify timeout for reading/writing confirmation

---

bin/run-python-script.sh

This seems like the easiest and the cleanest option. Spark will fail if the file doesn't exist, so we don't need to check for that.

[SW-431] Allow to pass additional arguments to run-python-script.sh

---

build.gradle

This version fixes several issues which are not affecting us, but it's good to be up-to-date,
see https://github.com/johnrengelman/shadow/releases

[SW-435] Upgrade shadow jar plugin to 2.0.0

---

core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala

Minor fix to my previous PR. If fields had some attribute VectorAssembler would squash them to Array[Attribute] rather than numAttribute. Need to use size method: https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/attribute/AttributeGroup.scala#L80 - that would handle all cases to get num of attributes.

[SW-453] [Minor] Use size method to get attr num

---

py/setup.py

The list of run-time dependencies was deprecated. Verified by running tests.

[SW-459] Update run-time dependencies for PySparkling

---

bin/get-extended-h2o.sh
bin/launch-spark-cloud.sh
bin/pysparkling
bin/run-example.sh
bin/run-python-script.sh
bin/run-sparkling.sh
bin/sparkling-env.sh
bin/sparkling-shell
make-dist.sh

Wanted to do this for a long time already
There is no semantic change except in the `run-example` where I removed the unnecessary condition. The deploy mode should be specified in all cases. It has effect only when running on yarn and spark properly handles the MASTER and DEPLOY_MODE configurations since some are not valid.

[SW-456] Make shell scripts safe

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/network/Security.scala

- Also use user suplied spark context in case of deprecated methods with spark context argument

[SW-470] Make H2OContext and Security API's consistent.

---

bin/pysparkling2.cmd
bin/run-example2.cmd

Clean up some parts of windows scripts. Removing the condition inside run-example as it's not necessary.
Also, no need to put jar files on class-path when running pysparkling since it's already handled by --py-files ( the same is done in sparkling-shell )

[SW-457] Clean up windows scripts

---

make-dist.sh

It was moved to doc/CHANGELOG.rst which is already collected by: `$(find doc -type f)`

[SW-479] Fix CHANGELOG location in make-dist.sh

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendConf.scala
doc/configuration/configuration_properties.rst
py/pysparkling/conf.py

This is just technical task which brings nothing new, just makes all the setters and getters consistent amongst scala and python
- allow to get and set all properties at run-time at Scala API
- allow to get and set all properties at run-time at Python API
- remove set_flatfile option in python which isn't defined anywhere in Scala backend
- sort definition of configuration properties everywhere in the same order
- This change does not change names of existing configuration so all existing configuration works just fine

[SW-407] Make Configuration consistent

---

.travis.yml

Related issues:
- https://github.com/travis-ci/travis-ci/issues/7476
- https://github.com/travis-ci/travis-ci/issues/7884
- cause by http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

[SW-505] Fix Java7 problem

---

core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/ui/SparklingWaterInfoPage.scala
core/src/main/scala/org/apache/spark/h2o/ui/SparklingWaterListener.scala
core/src/main/scala/org/apache/spark/network/Security.scala
doc/configuration/configuration_properties.rst
doc/tutorials/security.rst
py/pysparkling/conf.py

Propagate ssl.properties and ssl key files through Spark mechanisms instead of YARN.
To try:
1) run master branch to make sure it fails, `sparkling-shell --master yarn`
```
import org.apache.spark.network.Security
import org.apache.spark.h2o._
Security.enableSSL(spark)
val hc = H2OContext.getOrCreate(spark)
```
Should fail complaining about no `ssl.properties` file.
2) Run the above with this branch. H2O cluster should start, there should be mentions of `ssl.properties` in H2O logs and `ssl.properties` and `h2o-internal.jks` should be in temp files of each container (location can be found at the beginning of H2O logs).

[SW-501] Propagate all security related files.

---

assembly/build.gradle
build.gradle
core/build.gradle
core/src/main/scala/org/apache/spark/h2o/H2OContextImplicits.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2OFrameFromRDDProductBuilder.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/MLLibVectorConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/MLVectorConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/PrimitiveRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/ProductRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SupportedRDDConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala
core/src/test/scala/org/apache/spark/h2o/H2OSchemaUtilsTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala
core/src/test/scala/org/apache/spark/h2o/converters/SW516StandaloneApp.scala
core/src/test/scala/org/apache/spark/h2o/converters/SupportedRDDConverterTest.scala
core/src/test/scala/org/apache/spark/h2o/testdata/TestData.scala
core/src/test/scala/org/apache/spark/h2o/utils/ExternalBackendTestHelper.scala
core/src/test/scala/org/apache/spark/h2o/utils/H2OAsserts.scala
examples/src/scriptsTest/scala/water/sparkling/scripts/ScriptsTestSuite.scala
gradle.properties

SparkDataFrameConverter refactored. Now we first create flat dataframe in spark to simplify handling on sw side. 
The refactoring was needed in order to separate handling of vectors.
An improvement of this solution would be to drop the flag whether the vector is sparse or dense and make it part of the expected types
This change requires https://github.com/h2oai/h2o-3/pull/1348

[SW-449] Support for Sparse Vectors and Upgrade to H2O 3.14.0.2

---

Jenkinsfile
assembly-h2o/build.gradle
core/build.gradle
core/src/integTest/scala/water/sparkling/itest/local/H2OContextLocalSuite.scala
core/src/test/scala/org/apache/spark/h2o/H2OConfTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/KnownSparkIssues.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala
examples/build.gradle
ml/src/test/scala/org/apache/spark/ml/spark/models/H2OMojoModelTest.scala

- Also fixes bug with h2odriver name ( caused by SW-423 ) - the generated extended h2o jars need to have unique names
- Fix H2OConfTestSuite under external cluster
- Remove extended and download jars to have clean working environment. The downloaded jars are cached and it was possible that old one would be used
- Add missing libraries required for `RefineDateColum` into extended jar on class on external cluster

[SW-532] Make auto mode in external cluster default for tests in jenkins

---

py/pysparkling/context.py
py/pysparkling/initializer.py

This bug fix introduce back the cache which @mmalohlava wrote a while ago. However it also changes the python egg cache path for tests so the tests always uses the correct latest artefact ( this was source of issues and also reason why the cache was removed ).
Also when testing SNAPSHOT versions locally on different sparkling-water we make sure to use temporary cache for python eggs, again to be sure we run on the latest code.
The cache is fine if it's used by the users on the released versions.

[SW-539] Fix bug when pysparkling is executed in parallel on the same node

---

.travis.yml
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterBenchTest.scala
core/src/test/scala/org/apache/spark/h2o/testdata/TestData.scala
core/src/test/scala/org/apache/spark/h2o/utils/BenchUtils.scala
core/src/test/scala/water/api/SupportAPISuite.scala

The benchmark measures time of transfering ultra wide Spark sparse
vectors to H2O Frame representation.
Results for 3k x 50k (rows x cols), sparse vector, 0.2 sparsity (20% of
non-zeros), single Spark partition transfered to a single H2O chunk:
```
Mean           Stdev        Min           Max            Unit
39452.800781 ± 1380.934204 (37205.000000, 40707.000000) (msec)
```
Results for 10 x 11 matrics, sparse vector with a single non-zero
element (matrix has a single zero column):
```
Mean        Stdev     Min        Max         Unit
64.500000 ± 8.669871 (56.000000, 80.000000)  (msec)
```

[SW-553] Benchmark suite to measure performance of sparse transfers.

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtx.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterBenchTest.scala
core/src/test/scala/org/apache/spark/h2o/testdata/TestData.scala
core/src/test/scala/org/apache/spark/h2o/utils/BenchUtils.scala
core/src/test/scala/water/api/SupportAPISuite.scala

The change writes only non-zero parts of sparse vectors, keep track of
zero parts in vertical dimension and write them into Chunk via addZero()
method.
Preliminary benchmarks shows speed up for dataset 3,000x50,000 (50k is
represented by Sparse vector with sparsity 0.2) from 40seconds to 18
seconds locally.
Results for 3k x 50k (rows x cols), sparse vector, 0.2 sparsity (20% of
non-zeros), single Spark partition transfered to a single H2O chunk:
```
Mean           Stdev        Min           Max            Unit
39452.800781 ± 1380.934204 (37205.000000, 40707.000000) (msec) (BEFORE
CHANGE)
13518.599609 ± 663.543762 (12781.000000, 14495.000000)  (msec)
```
Results for 10 x 11 matrics, sparse vector with a single non-zero
element (matrix has a single zero column):
```
Mean        Stdev …
```

[SW-553] Improve Sparse vector handling for internal cluster

---

core/src/test/scala/org/apache/spark/h2o/converters/RDDToDataFrameViaH2OFrameTest.scala

Note: this will fail till the patched H2O version is used (see https://github.com/h2oai/h2o-3/pull/1661)

[SW-559] Test for missing 0-len chunks

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
doc/configuration/configuration_properties.rst
py/pysparkling/conf.py

The web remains opened on the client node, therefore this change should not be breaking change. We expose the ip:port of the client node

[SW-562] Disable web on external H2O nodes in external cluster mode

---

README.rst
build.gradle
dist/index.html
doc/tutorials/use_as_spark_package.rst
package/build.gradle
settings.gradle

The motivation for this is to improve user experience. Right now, SW provides 4 modules with complex dependencies which need to be often hot-fixed (like  SW-475).
The goal of this improvement is to provide a single uber Sparkling Water package which can be used as input for Spark submit option `--packages`.
This package is being published into maven central and can be used with Spark submit:
```
$SPARK_HOME/bin/spark-submit --packages ai.h2o:sparkling-water-package_2.11:2.1.12 --class org.apache.spark.examples.h2o.CraigslistJobTitlesStreamingApp /dev/null
```
Note: right now it also provides a fixed for [SW-475]

[SW-504] Provides uber Sparkling Water Spark package

---

py/pysparkling/initializer.py

change to file:/// to initialize the H2OConf. /// is understood by all according to https://en.wikipedia.org/wiki/File_URI_scheme (including windows shell)

[SW-593] H2OConf initialization exception on windows

---

jenkins/Jenkinsfile-external
jenkins/Jenkinsfile-external_nightly
jenkins/Jenkinsfile-internal
jenkins/Jenkinsfile-internal_nightly
jenkins/sparklingWaterPipeline.groovy

Testing against h2o nightly.
We build and test sw against latest H2O nightly and upload the results into S3.
I think that we don't have to generate also all extended jars for external cluster as if we need to get them, we can just download the distribution and call script `./get-extended-h2o`. What do you think @mmalohlava ?

[SW-600] Proper Sparkling Water Nightly

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala

We would like to have INFO logs for H2O client instead of default WARN.

[SW-610] Change of default client log level to INFO

---

py/MANIFEST.in
py/build.gradle

Ugly, but we need to handle the case when we access the h2o version files from zip.
this is not h2o business as it's not deployed in zip files and therefore we need to handle that on sparkling water side

[SW-620] Fix obtaining version from bundled h2o inside pysparkling

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala
doc/tutorials/pysparkling_azure_dbc.rst
doc/tutorials/rsparkling_azure_dbc.rst
doc/tutorials/sw_azure_dbc.rst

We are using internal Spark API available inside package `org.spark_project.jetty` to register new tabs, however this API(class) is not available on Databricks - they are using regular jetty for this in `org.eclipse.jetty` (this is even more complicated by the fact that we are shadowing the jetty)
We have several options here:
1) Add also `org.spark_project.jetty` to assembly jar and Sparkling Water core dependencies so it's available on the Databricks and in https://github.com/h2oai/sparkling-water/blob/0c19d249345dd1a01c89e25d71ba2a17fecdb148/core/src/main/scala/org/apache/spark/h2o/ui/SparklingWaterInfoPage.scala#L171 create actually 2 variants of methods attachHandler where one would use the method from regular jetty and one from spark jetty and they would be invoked based on the …

[SW-683] Fix starting H2OContext on Databricks

---

doc/src/site/sphinx/about.rst
doc/src/site/sphinx/deployment/backends.rst
doc/src/site/sphinx/index.rst
doc/src/site/sphinx/rsparkling.rst
doc/src/site/sphinx/tutorials/tutorials.rst
py/README.rst

- Added an “About Sparkling Water” section (and updated the index’s “Overview” in the process)
- Added a small overview section about Sparkling and a link to the RSparkling repo
- Changed “An Introduction to PySparkling” to just “PySparkling.” Added small introductory text with this update.
- Added ellipsis to the “How to” section.

[SW-697] Additional updates to Sparkling Water help system

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
py/pysparkling/conf.py

the client is informed about the cluster being killed, but for example,
if the cloud is killed for memory reasons by YARN, we don't get such
messages and the client hangs forever

[SW-701] Kill client when the external H2O cluster disappears. Normally

---

examples/scripts/tests/pysparkling_ml_import_overrides_spark_test.py
py/pysparkling/ml/algo.py
py/tests/tests_integ_local.py

We can't use `SparkSession.builder.getOrCreate` in `@keyword_only` annotated methods.

[SW-706] Fix pysparkling.ml import for non-interactive sessions

---

doc/src/site/sphinx/tutorials/change_default_port.rst
doc/src/site/sphinx/tutorials/tutorials.rst
py/README.rst

- Added a new topic describing how to change the default port value
that’s used when starting H2O on Spark.
- Driveby fix: In Python readme, indented some code samples for
consistency and to ensure that text that follows is not included in the
code.

[SW-753] - In UG, adding "How To" topic for changing default port value

---

py/tests/tests_unit_conversions.py

test: reproduction of problem with columns of wide data frames in pyspark, that affected 
till the commit id:
f50dd728281d11f9a2ab3cdaeb994644b892d65a
(included)
This test describes the problem and helps to prevent against it in future commits.
Sponsored by fingerprints.digital

[SW-793] test: reproduction of problem with columns of wide data frames in pyspark

---

ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OMOJOPipelineModelParams.scala
ml/src/test/scala/org/apache/spark/ml/spark/models/H2OMOJOPipelineModelTest.scala
py/py_sparkling/ml/models.py

The columns are now properly typed as double. Also, we currently store
the prediction output in an array for each row, loosing the information
about the name of the output column.
This has been fixed as well, however the behaviour is disabled by
default. It will be enabled by default in Spark 2.4

[SW-851] Properly type and name output columns of mojo pipeline

---

doc/src/site/sphinx/deployment/rsparkling_on_windows.rst
r/README.rst

- In the R Readme, fixed the link for Troubleshooting RSparkling on Windows. This topic was moved from Tutorials to Deployment.
- Fixed a link to the Main RSparkling Documentation. This pointed to a local rst file rather than the HTML file, resulting in a broken link.

[SW-1018] Updates to R documentation files

---

dist/index.html
doc/build.gradle
doc/src/site/sphinx/index.rst
doc/src/site/sphinx/install/install_and_start.rst
doc/src/site/sphinx/pysparkling.rst
examples/README.rst

- Added a new topic, "Installing and Starting"
- Included new topic in the index
- Added an anchor to the PySparkling topic
Driveby fixes:
- Fixed broken links in the Examples/readme.rst file
- Fixed Run on Hadoop installation step 4 on the download page.

[SW-1083] Docs: Adding Install instructions to UG

---

ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala

We always need internally use models from py_sparkling submodule to be able to load them in PySparkling

[SW-1136] Fix bug affecting loading pipeline in python when stored in scala

---

core/src/main/scala/org/apache/spark/h2o/converters/MLLibVectorConverter.scala
core/src/test/scala/org/apache/spark/h2o/converters/SupportedRDDConverterTest.scala
core/src/test/scala/org/apache/spark/h2o/utils/H2OAsserts.scala

Fixes:
-> Wrong conversion between RDD[SparseVector] -> H2OFrame
-> Wrong conversion between RDD[Vector] in case the vector had different number of elements

[SW-1138] Fix several cases in spark vector -> h2o conversion

---

py/pysparkling/context.py

When running `hc.stop()` there is an error: `NameError: global name 'exit' is not defined`. The `exit()` is not correct refering its source package, change to `sys.exit()`.

[SW-1150] Change exit() to sys.exit()

---

bin/run-sparkling.sh
bin/sparkling-shell

There is no need to additionally pass this configuration to CLI as Spark reads the spark-defaults.conf file

[SW-1186] No need to pass properties defined in spark-defaults.conf to cli

---

ml/src/main/scala/org/apache/spark/ml/h2o/algos/H2OGridSearch.scala

Sparkling Water 2.1 on Scala 2.10 was failing to compile as it required more strict type variables. Sparkling Water compiles well on Scala 2.11 with the current code, but it does not hurt to be consistent and provide the types also on Scala 2.11.
That is why I'm applying this change on to master and later we should cherry-pick to all rel-2.1, rel-2.2, rel-2.3 and rel-2.4 branches

[SW-1189] Fix Sparkling Water 2.1.x compile on Scala 2.10

---

py/tests/generic_test_utils.py
py/tests/integ_test_utils.py
py/tests/tests_hadoop_smoke.py
py/tests/tests_integ_local.py
py/tests/tests_integ_yarn.py
py/tests/tests_unit_conf.py
py/tests/tests_unit_mojo_pipeline.py
py/tests/tests_unit_mojo_predictions.py

No semantic changes -> just clicked on reformat code in Idea in test utilities and tests files themselfs

[SW-1204] Fix formating in python tests

---

bin/sparkling-env.sh

Previously, the version check was failing on cases like this:
the min version is 0.3.9, the installed version is 0.4.1

[SW-1270] Fix version check in PySpakrling shell

---

ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala

Another step towards consistency with Spark.
H2OMOJOPipelineModel is already using `prediction` as default value for prediction column

[SW-1299] Warn user that default value of predictionCol on H2OMOJOModel will change in the next major release to 'prediction'

---

doc/src/site/sphinx/tutorials/ssl.rst

UDP transfer mode was removed from H2O long time ago, we don't need to mention it in the doc anymore

[SW-1319] Remove mention of H2O UDP from user documentation

---

core/build.gradle
core/src/bench/scala/ai.h2o.sparkling.bench/DataFrameConverterBenchSuite.scala
core/src/main/scala/org/apache/spark/h2o/converters/RowConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/utils/DatasetShape.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OSchemaUtils.scala
core/src/test/scala/org/apache/spark/h2o/H2OSchemaUtilsTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModelBase.scala
ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOPipelineModel.scala
ml/src/test/scala/org/apache/spark/ml/spark/models/H2OMojoModelTest.scala

Original performance:
```
Measure performance of conversion to H2OFrame on a flat data frame: 1021.000000 ± 448.612305 (526.000000, 1512.000000)
Measure performance of conversion to H2OFrame on a data frame with nested structs: 1318.199951 ± 299.074738 (1013.000000, 1774.000000)
Measure performance of conversion to H2OFrame on a data frame with flat arrays: 4314.600098 ± 1080.290405 (3613.000000, 6139.000000)
Measure performance of conversion to H2OFrame on a data frame with wide sparse vectors: 44770.800781 ± 3306.025635 (41178.000000, 49193.000000)
Measure performance of conversion to H2OFrame on a data frame with wide dense vectors: 8320.400391 ± 385.206177 (7841.000000, 8870.000000)
Measure performance of conversion to H2OFrame on a matrix 10x11 represented by sparse vectors: …
```

[SW-1412] Integrate generic conversion logic to data frame conversion to H2O frames

---

ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParams.scala
ml/src/main/scala/org/apache/spark/ml/h2o/param/H2OAlgoParamsHelper.scala
ml/src/test/scala/org/apache/spark/ml/h2o/param/H2OAlgoParamsHelperTest.scala
ml/src/test/scala/org/apache/spark/ml/spark/models/H2OMojoModelTest.scala
py/py_sparkling/ml/algos.py
py/py_sparkling/ml/util.py
py/pysparkling/ml/params.py

So far just on single parameter, just as a prototype. Once we have approved solution, we can apply the deprecation to rest of the code.
The benefit is simpler usage of API( no need to reference different namespaces) + simple code on both, scala + python side -> Which can lead to simpler code generation once we start generation these APIs for Python & R

[SW-1439] [Prototype] Switch to using String value on the setters & getters in the ml API ( just on distribution param so far)

---

py/ai/h2o/sparkling/ml/algos/H2OAutoML.py
py/ai/h2o/sparkling/ml/params/H2OAutoMLParams.py
py/ai/h2o/sparkling/ml/params/H2OCommonParams.py
py/ai/h2o/sparkling/ml/params/H2OTypeConverters.py

Also fixes bug in H2OAutoML constructor. `ClassSamplingFactors` was not converted to double values

[SW-1489] Use TypeConverters on AutoML pysparkling wrapper

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala
py/ai/h2o/sparkling/ml/algos/H2OAutoML.py
py/ai/h2o/sparkling/ml/algos/H2OAutoMLExtensions.py

This change has more actually multiple motivations:
- Immutability -> don't change user specified value on the estimator
- Keep all the logic in Scala wrapper, have PySparkling just as dummy client. 
- Keep the client simply and generic so we can later generate all algos with the same generator
- Move special methods which need to be on H2OAutoML to Extension class. The generator can check if the extension class exists and make sure the Algo, in this case H2OAutoML, will extend from it. The Extensions methods can't be generated so that is why I extracted them.

[SW-1490] Immutable projectName on H2OAutoML

---

py/ai/h2o/sparkling/Initializer.py

This directory is also automatically deleted when the Spark JVM shuts down

[SW-1499] Extract zip file into temp directory owned and configured by Spark

---

templates/src/terraform/aws/modules/emr/variables.tf
templates/src/terraform/aws/variables.tf

from https://aws.amazon.com/emr/pricing/:
m5.xlarge (current generation)
- Amazon EC2 Price: $0.192 per Hour 
- Amazon EMR Price: $0.048 per Hour
m3.xlarge (previous generation)
- Amazon EC2 Price: $0.266 per Hour 
- Amazon EMR Price: $0.07 per Hour

[SW-1549] Upgrade default instances in terraform templates to M5.xlarge

---

assembly-h2o/build.gradle

The version suffix was newly added even though we explicitly set `version = null`. To overcome this, we explicitly configure the full jar name instead of it's separate components.

[SW-1551] Fix path to external jars generated by ./gradlew extendJar

---

jenkins/build.gradle
jenkins/docker/regular-tests/Jenkinsfile-build-docker

Talked to @honzasterba and @michal-raska . A lot of fixes have been done since version 58 so it's possible the upgrade might help is with hang of hadoop infra in docker.
Note: After merging this, the BUILD_DOCKER job needs to be triggered in jenkins and sw docker image number incremented after successful run

[SW-1567] Upgrade version of h2o docker image from 58 to the 64

---

py/src/ai/h2o/sparkling/ml/algos/H2OAutoML.py
py/src/ai/h2o/sparkling/ml/algos/H2ODRF.py
py/src/ai/h2o/sparkling/ml/algos/H2ODeepLearning.py
py/src/ai/h2o/sparkling/ml/algos/H2OGBM.py
py/src/ai/h2o/sparkling/ml/algos/H2OKMeans.py
py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py

H2OGLM has it added as part of https://github.com/h2oai/sparkling-water/pull/1493/files

[SW-1583] Add missing namedMojoOutputParameter to PySparkling Algo constructors

---

py/src/ai/h2o/sparkling/Initializer.py

The issue was the addUrl method can be also protected, therefore not accessible from py4j by default.
Manually tested on Zeppeling with previous SW (could replicate) and with this fix, where the issue was resolved

[SW-1580] importing pysparkling in Zeppelin fails

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAnomaly.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAutoEncoder.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionDimReduction.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionWordEmbedding.scala

The other algos have it deprecated already. Starting from next release, the predicted column will contain the most important prediction output, the rest will be in detailed_prediction

[SW-1598] Deprecate cases in H2OMojoPrediction where the prediction column does not directly contain the predicted value.

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala

`calibrateClassProbabilities` expects an array of size 3, but its pasing in an array of size 2 for `supportsCalibratedProbabilities`, this causes an `java.lang.ArrayIndexOutOfBoundsException: 2` error when trying to score a mojo that was trained with the calibration option enabled.

[SW-1600] Fix IIOB when using calibrated probabilities on MOJO

---

doc/build.gradle
doc/src/site/sphinx/deployment/terraform_emr.rst

- Spark 2.1, 2.2 -  JupyterHub available in EMR only with versions Spark 2.3+
- Livy 0.6 supporting Spark 2.2-2.4 - Only available in the EMR version with Spark 2.4

[SW-1597] Add a note informing that terraform template is available only for Spark 2.4

---

benchmarks/src/main/terraform/aws/modules/emr_benchmarks_deployment/main.tf
benchmarks/src/main/terraform/aws/modules/emr_benchmarks_deployment/variables.tf
benchmarks/src/main/terraform/aws/variables.tf

- In case of a jenkins pipeline gets shooted down
- Tested locally with a timeout set to 10 minutes

[SW-1616] Benchmarks: Automatic Cluster Shutdown after Timeout

---

benchmarks/run_benchmarks.sh

Since SW is a bit unstable on EMR, it would be nice if benchmarks were marked on jenkins as failed when their execution goes wrong.

[SW-1617] Benchmarks: Report Failure if Execution Goes Wrong

---

examples/scripts/hamOrSpam.script.scala
examples/src/main/scala/org/apache/spark/examples/h2o/HamOrSpamDemo.scala

The failing tests has to ensure that frame updates are inside **withLockAndUpdate** block

[SW-1623]  Fix tests causing intermittent NPE in PySparkling with rollups on external backend

---

core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
examples/src/integTest/scala/water/sparkling/itest/local/PubDev928Suite.scala
gradle/conf/scalastyle-config.xml

This one is finally fixing the missing chunk issue (EDIT, not yet :( )
Explanation here https://0xdata.atlassian.net/browse/PUBDEV-6904, I have put the fix into H2O so it can again receive and confirm empty chunks but also ensured that we do not send empty chunks for conversions as there is no value in that.

[SW-1642] Prevent sending empty partitions when converting Spark Data frame to H2OFrame

---

gradle-spark2.3.properties

After this change is merged, we need to trigger build of a new docker image and update the version in both master and rel branch to ensure our tests are using the docker with the upgraded spark.

[SW-1619]    Upgrade Spark 2.3 to 2.3.4

---

doc/src/site/sphinx/index.rst
doc/src/site/sphinx/migration_guide.rst
doc/src/site/sphinx/tutorials/sw_drf.rst

Migration guide between major SW versions. I have included changes which goes to next major 3.28 and are breaking the code. It would be great if every change going to major rel which is altering the current API has also short description in this document

[SW-1628] Create migration guide document with breaking changes so far added to 3.28

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

Currently, in manual cluster mode, it is optional to specify the H2OCluster endpoint. If it is not specified, H2O tries to find the cluster using broadcast search. In rest API based solution, we always need  to know the endpoint of the cluster.
This change accomplishes that, but also in the client based solution, not just rest api based to ensure unified behaviour. In my opinion it is better to be more explicit in manual mode. Anyway, we are planning to make Scala also rest API based at some point.
What we just need to do is to deprecate the behaviour and warn the users that endpoint will be always required. After we discuss this, I can create JIRA in our Major release which would accomplish this deprecation so we don't forget about that.

[SW-1655] Always require IP:Port of the external cluster in manual start mode.

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOBaseCache.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPrediction.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAnomaly.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAutoEncoder.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionClustering.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionDimReduction.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionWordEmbedding.scala

@mmalohlava: Please can you have a quick look on:
H2OMOJOPredictionAnomaly.scala
H2OMOJOPredictionAutoEncoder.scala
H2OMOJOPredictionBinomial.scala
H2OMOJOPredictionClustering.scala
H2OMOJOPredictionMultinomial.scala
There were conflicts.

[SW-1658][rel-3.26] Figure out better way of caching MOJOs (v1 & v2)

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
gradle/conf/scalastyle-config.xml

This PR requires https://github.com/h2oai/h2o-3/pull/3931 to be a part of a released version of H2O-3 for successful build.

[SW-1667] Enable Users to Specify Block Size of Communication in External Backend

---

core/src/test/scala/org/apache/spark/h2o/H2OConfTestSuite.scala

The issue was that H2OContext is now abstract class. However H2OConfTestSuite does not need started H2OContext, it is supposed to test H2OConf

[SW-1654] Fix H2OConf test suite

---

doc/src/site/sphinx/migration_guide.rst

These 2 changes are already merged into master (3.28) but we forgot to document them in migration guide

[SW-1684] Migration guide was missing several changes which are already resolved in 3.28

---

doc/build.gradle
doc/src/site/sphinx/deployment/sw_azure_dbc.rst
doc/src/site/sphinx/migration_guide.rst
gradle.properties
gradle/release.gradle
jenkins/Jenkinsfile-release
jenkins/sparklingWaterPipeline.groovy
py/build.gradle
py/src/ai/h2o/sparkling/VersionComponents.py
py/tests/unit/simple/test_version_components.py

Versions will be:
Normal: 3.26.0.9-1-2.4
where 3.26.0.9 is H2O version, -1 is iteration within the single h2o version and -2.4 is spark version.
For nightlies, the format is: 3.26.0.9-1.1-2.4, where almost everything is same as ^ except the `1.1` represents the iteration and the nightly build number after the dot.

[SW-1681] Change sw version to include also patch within one h2o version

---

kubernetes/build.gradle

Previously, we replaced the jars folder by the sparkling water zip file, this way we copy the file to the folder

[SW-1688] Fix docker image generation for Scala Sparkling Water in Kuberntes Environment

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

Replace remaining places where we use H2O logging in H2OContext.
Ultimately, after we have one backend where driver does not use H2O, we need to use Spark logging everywhere 
See https://0xdata.atlassian.net/browse/SW-1699

[SW-1699] Replace H2O Logging by Spark Logging in H2OContext

---

benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/Runner.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/SparklingBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/SpreadRDDBuilder.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ODataFrame.scala
core/src/main/scala/org/apache/spark/h2o/converters/H2ORDD.scala
core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
core/src/test/scala/org/apache/spark/h2o/backends/SharedBackendUtilsTestSuite.scala
py/src/ai/h2o/sparkling/H2OContext.py

-> Better `conf` on H2OContext -> fixes bug where we were setting wrong conf instance on ExternalH2OBackend which was leading to error when obtaining cluster details via rest api as the clusterEndpoint was empty even though set before
-> Avoid unnecessary complexity in classes related to backends, simplify and unify them
This change does not introduce any breaking behaviour
The tests for rest api solution still fails due to missing conversions but fails as expected. Before this change we failed with exception whilst getting connection to the cluster

[SW-1713] Refactor internal & external backend utils to have the same structure

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala

PySparkling has method download_h2o_logs which needs to work also in the client-less approach
After this, the conversions should be the last bit to do for the first stage of the client less approach(without the algo api)

[SW-1714] Ensure download_h2o_logs works in the client-less approach

---

bin/build-kubernetes-images.sh
bin/sparkling-env.sh
dist/build.gradle
kubernetes/build.gradle

Dockerfiles are created as part of the distribution and we provide the script for the users to build themselves the docker image for kubernetes from the downloaded distribution ( no requirement for using gradle)
Later, we can reuse this script for some automation and publishing the images to public docker hub, but for now I think it's enough

[SW-1690] Create script to generate kubernetes docker images

---

core/build.gradle

Depends on the upgrade to H2O 3.26.0.11
The dependency is in the assembly automatically as we include all transitive dependencies

[SW-1706] Put h2o-security package into sparkling water assembly

---

py/src/ai/h2o/sparkling/ml/params/H2OTargetEncoderParams.py

Not causing any problems, but we are adding multiple args instead of one documentation. Should be wrapped in `"""`

[SW-1739] Fix target encoder multiline doc descriptions

---

py/build.gradle

Right now clientless tests are also running in internal backend, causing test failures

[SW-1743] Run rest api client tests only in external backend mode

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/SparklingBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
py/examples/scripts/H2OContextInitDemo.py
py/src/ai/h2o/sparkling/H2OContext.py

Depends on https://github.com/h2oai/h2o-3/pull/4110 (H2O 3.26.0.12)
No need for hacky stopping, tested on YARN in both internal & external backend

[SW-1732] Implement shutdown hook to ensure H2O will go down on normal stop of Spark

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ProxyStarter.scala

The discovered port might get occupied between the check and server start, which leads to BindException.

[SW-1791] Make ProxyStarter more robust

---

py/src/ai/h2o/sparkling/H2OContext.py

These parameters were added because of initial Steam integration but Steam is not using it anymore

[SW-1792] Remove extra pre_create_hook and h2o_connect_hook parameters from H2OContext on PySparkling

---

core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
doc/src/site/sphinx/configuration/configuration_properties.rst

The end-user should not observe any difference as this is all automatically handled

[SW-1870] Use internal secure connections by default

---

core/src/main/scala/org/apache/spark/h2o/backends/external/RestCommunication.scala

I think we should log these in `logDebug` as in normal app there will be huge amount of requests, WDYT?

[SW-1881] Fix typo in RestCommunication

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
py/src/ai/h2o/sparkling/H2OConf.py

Deprecate so we can remove in 3.28.1.1 as this option won't be necessary anymore

[SW-1884] Deprecate externalWriteConfirmationTimeout option

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
py/src/ai/h2o/sparkling/ml/algos/H2OGridSearch.py

After discussing with @michalkurka grid search should use sequential model building by default as parallel building requires more memory (and might require additional tweaking)

[SW-1901] Sequential grid search should be default

---

bin/sparkling-env.sh

We should use Spark values actually. It will be easier to find logs as default spark log dir is in $SPARK_HOME/work

[SW-1902] Remove SPARK_LOG_DIR, SPARK_WORKER_DIR and SPARK_LOCAL_DIRS and use default Spark values

---

dist/build.gradle
dist/src/index.html
doc/src/site/sphinx/deployment/backends.rst
doc/src/site/sphinx/install/install_and_start.rst

I have discovered that all documentation mentions that location of extension assembly jar is in the root of distribution archive, however the file is being copied into `sparkling-water-extensions/build/lib` which is a bug.
I have tried to fix the doc + copy the file into newly created `jars` folder to avoid complicated directory structure inside the sw distribution. I would like to put there also the original assembly jar, but created another JIRA for it https://0xdata.atlassian.net/browse/SW-1915

[SW-1914] Copy extension jar to jars folder in distribution archive

---

bin/sparkling-env.sh
dist/build.gradle

@bilcus From major release 3.28.1.1 the location of assembly jar will be in `jars` folder directly, not sure if steam depends on this location so just making sure you know about it in advance :)

[SW-1915] Put sparkling water assembly jar into jars folder in the distribution archive instead into assembly/build/libs

---

core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala

This check does not bring any additional value as we already check the cluster size in `      ExternalH2OBackend.startH2OClient(hc, nodes)`

[SW-1943] Remove unnecessary ExternalH2OBackend.verifyH2OClientCloudUp(conf, nodes) check

---

core/src/main/scala/ai/h2o/sparkling/frame/H2OChunk.scala
core/src/main/scala/ai/h2o/sparkling/frame/H2OFrame.scala
core/src/main/scala/ai/h2o/sparkling/utils/H2OContextUtils.scala
core/src/main/scala/ai/h2o/sparkling/utils/RestApiUtils.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
core/src/main/scala/org/apache/spark/h2o/backends/external/ProxyStarter.scala
core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OKMeans.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OSupervisedAlgorithm.scala

Refactoring ->
-> Split RestApiUtils and move the methods where they actually belong and avoiding bloating of this class
-> Move RestApiUtils to ai.h2o.sparkling package
-> Rename getCloudInfo -> getClusterInfo to reflect H2O terminology

[SW-1937] Move RestAPIUtils to ai.h2o.sparkling package

---

ml/src/main/scala/ai/h2o/sparkling/ml/params/HasQuantileAlpha.scala

This PR should remove the below compiler warning:
```
.../HasQuantileAlpha.scala:20: imported `DoubleParam' is permanently hidden by definition of object DoubleParam in package paramsimport org.apache.spark.ml.param.{DoubleParam, Params}
```

[SW-1959] Remove Compiler Warning in HasQuantileAlpha.scala

---

r/src/tests/testthat/testConversions.R

See https://github.com/sparklyr/sparklyr/issues/1984
It makes sense that it is timeout issue as when it fails, it always does so on the first test

[SW-1966] Fix intermittent error coming from SparklyR in our tests

---

core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/shared/SharedBackendConf.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
py/src/ai/h2o/sparkling/InternalBackendConf.py
py/src/ai/h2o/sparkling/SharedBackendConf.py

I propose to move this property since it's used only by the internal backend.

[SW-1975] Move spark.ext.h2o.hdfs_conf Property among Properties of Internal Backend

---

core/src/main/scala/ai/h2o/sparkling/backend/converters/SparkDataFrameConverter.scala
core/src/main/scala/ai/h2o/sparkling/backend/converters/SupportedRDD.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendWriter.scala
core/src/main/scala/ai/h2o/sparkling/backend/shared/SecurityUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/shared/SharedBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/main/scala/water/api/DataFrames/DataFramesHandler.scala
core/src/main/scala/water/api/H2OFrames/H2OFramesHandler.scala
core/src/main/scala/water/api/RDDs/RDDsHandler.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OKMeans.scala
ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoder.scala
ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala
py/src/ai/h2o/sparkling/H2OContext.py
repl/src/main/scala/ai/h2o/sparkling/repl/BaseH2OInterpreter.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOBaseCache.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOLoader.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOReader.scala
utils/src/main/scala/ai/h2o/sparkling/utils/SparkSessionUtils.scala

This change ensures we always use active SparkSession.
The SparkSession passed to H2OContext is basically ignored now, which is correct. I plan to create the parameter-less methods for H2OContext getOrCreate in different JIRA to keep this one smaller https://0xdata.atlassian.net/browse/SW-1977.
The final deprecation of the getOrCreate with spark/sc parameter will be done again in follow-up to  https://0xdata.atlassian.net/browse/SW-1977 in https://0xdata.atlassian.net/browse/SW-1970

[SW-1969] Respect SparkSession of a current environment

---

core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/JavaH2OContext.java
doc/src/site/sphinx/migration_guide.rst
macros/src/main/scala/ai/h2o/sparkling/macros/DeprecatedMethodMacro.scala
py/src/ai/h2o/sparkling/H2OConf.py
py/src/ai/h2o/sparkling/H2OContext.py
r/src/R/ai/h2o/sparkling/H2OConf.R
r/src/R/ai/h2o/sparkling/H2OContext.R

Final stage of simplification of the getOrCreate method. On purpose I would like to remove the original methods in 2 major releases time to get users more time to migrate as this is the most exposed method

[SW-1970] Deprecate sparkSession and sparkContext argument of H2OContext.getOrCreate()

---

core/src/main/scala/ai/h2o/sparkling/backend/shared/SharedBackendConf.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/migration_guide.rst
doc/src/site/sphinx/tutorials/secured_flow.rst
py/src/ai/h2o/sparkling/H2OContext.py
py/src/ai/h2o/sparkling/SharedBackendConf.py
r/src/R/ai/h2o/sparkling/H2OConf.R
r/src/R/ai/h2o/sparkling/H2OContext.R

See https://0xdata.atlassian.net/browse/SW-1988 for more details

[SW-1988] Deprecate passing arguments via kwargs method in getOrCreate in PySparkling

---

core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendH2ODataFrame.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendH2ORDD.scala

There is speedup after removing
OLD:
H2OFrameToDataFrameConversionBenchmark results for the dataset 'random01Int4':
time: 30014 milliseconds
H2OFrameToDataFrameConversionBenchmark results for the dataset 'random01Int40':
time: 53403 milliseconds
H2OFrameToDataFrameConversionBenchmark results for the dataset 'random01Int400':
time: 308676 milliseconds
NEW:
H2OFrameToDataFrameConversionBenchmark results for the dataset 'random01Int4':
time: 15342 milliseconds
H2OFrameToDataFrameConversionBenchmark results for the dataset 'random01Int40':
time: 32885 milliseconds
H2OFrameToDataFrameConversionBenchmark results for the dataset 'random01Int400':
time: 273107 milliseconds

[SW-1962] Remove materialization of iterator in asSparkFrame conversion

---

py/src/ai/h2o/sparkling/ml/params/H2OXGBoostParams.py

I would like to follow on the comment https://github.com/h2oai/sparkling-water/pull/1878#pullrequestreview-364090922 and complete the removal.

[SW-1872][FOLLOWUP] Remove deprecated nEstimators getter and setter H2OXGBoost Python API

---

build.gradle
core/build.gradle
core/src/main/scala/ai/h2o/sparkling/backend/external/RestCommunication.scala
core/src/main/scala/water/api/RestAPIManager.scala
doc/src/site/sphinx/devel/build.rst
examples/build.gradle
examples/src/scriptsTest/scala/ai/h2o/sparkling/ScriptTestHelper.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/stacktrace/StackTraceCollector.scala
macros/build.gradle
ml/build.gradle
repl/build.gradle
repl/src/main/scala/ai/h2o/sparkling/repl/BaseH2OInterpreter.scala
repl/src/main/scala/ai/h2o/sparkling/repl/H2OInterpreter.scala
repl/src/main/scala/ai/h2o/sparkling/repl/PatchUtils.scala

Enable users to build Sparkling Water with Scala 2.12. 
Manually tested that it compiles and tests unit pass fine with Scala 2.12
Just updated code so it can build on Scala 2.11 and Scala 2.12. 
Note: We do not publish artifacts for non-default Scala for given Spark at this moment. So no tests on purpose at this stage. Just to give developers the ability to start building SW with Scala 2.12 and give us feedback.
Also upgrade to Spark. 3.0 will be easier as we now know that our code is agnostic to Scala version (at least when considering 2.11 and 2.12). We can just specify the scalaBaseVersion on sparkProperties level, not on the global gradle.properties level.

[SW-1846] Be able to compile Sparkling Water with Scala 2.12

---

dist/build.gradle

Also verified that the rest of artifacts are named correctly

[SW-2000] Fix distribution artifact name

---

py/src/ai/h2o/sparkling/H2OContext.py
r/src/R/ai/h2o/sparkling/H2OContext.R

We have introduced the ``_isClientConnected()`` in order to ensure that when the backend restarts, the same H2OContext in python will recognize the change and call internally h2o.connect again. Previously, it would not call h2o.connect again as `_is_initialized` was already to True.
However we also removed the _is_initialized flag which was a bug. We need to keep that flag enabled as well because, for example, user can call the H2OContext.getOrCreate in different python notebook, but the java backend already tells us that the client is connected so we won't call h2o.connect, but we do need to run connect in this case

[SW-2004] Two notebooks in Databricks can't both connect to same H2O cluster

---

r/src/R/ai/h2o/sparkling/H2OContext.R

Users should see:
```
Sparkling Water Context:
* Sparkling Water Version: 3.30.0.1-1-2.4
* H2O name: kuba
* cluster size: 1
* list of used nodes:
(executorId, host, port)
------------------------
(0,192.168.43.22,54321)
------------------------
Open H2O Flow in browser: http://localhost:54322 (CMD + click in Mac OSX)
```
when they call hc <- H2OContext.getOrCreate. This is done in all other clients

[SW-2007] Call print(hc) during first creation of H2OContext.r as in H2OContex.py

---

core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala

The client ip configuration has now only effect when we run in the original client approach. 
This change is reflecting that. We do not need to do the search for client ip in rest API mode as we don't use client anyway.
Also this way we keep the code related to client connection close and separated from rest of the code

[SW-2009] No need to search for client ip in rest api mode

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

Calling H2OContext.getOrCreate should provide all the warnings, such as:
```
20/02/28 16:11:55 WARN ExternalH2OBackend: To avoid non-deterministic behavior of Spark broadcast-based joins,
we recommend to set `spark.sql.autoBroadcastJoinThreshold` property of SparkSession to -1.
E.g. spark.conf.set("spark.sql.autoBroadcastJoinThreshold", -1)
We also recommend to avoid using broadcast hints in your Spark SQL code.
20/02/28 16:11:55 WARN ExternalH2OBackend: Increasing 'spark.locality.wait' to value 30000
20/02/28 16:11:55 WARN ExternalH2OBackend: To avoid non-deterministic behavior of Spark broadcast-based joins,
we recommend to set `spark.sql.autoBroadcastJoinThreshold` property of SparkSession to -1.
E.g. spark.conf.set("spark.sql.autoBroadcastJoinThreshold", -1)
We also recommend to avoid …
```

[SW-2023] Avoid repeated log messages

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OKMeans.scala
ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoder.scala
ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala

The motivation for this started when I was testing the algo api, I was running code:
```
from pyspark.sql.functions import log, col, min, max, mean, lit
dataset = spark.read.csv("file:///Users/kuba/devel/repos/sparkling-water/examples/smalldata/insurance.csv", header=True, inferSchema=True).withColumn("Offset", log(col("Holders")))
from pysparkling.ml import H2OGBM
gbm = H2OGBM(ntrees=2, seed=42, distribution="bernoulli", labelCol="capsule")
model = gbm.fit(dataset)
```
You can see that I do not call `H2OContext.getOrCreate()`. H2OContext is in this case created automatically inside the `fit` method on Scala. 
In Python & R implementation of H2OContext, we are now setting option `spark.ext.h2o.rest.api.based.client=true` (https://github.com/h2oai/sparkling-water/blob/14cfdcdb7712d9386444e7 …

[SW-2022] Start H2OContext on python side if the user didn't explicitly ask for it

---

core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/RestCommunication.scala
core/src/main/scala/ai/h2o/sparkling/frame/H2OChunk.scala
core/src/test/scala/org/apache/spark/h2o/ConfigurationPropertiesTestSuite.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ChunkServlet.scala
py/src/ai/h2o/sparkling/ExternalBackendConf.py
r/src/R/ai/h2o/sparkling/H2OConf.R
utils/build.gradle
utils/src/main/scala/ai/h2o/sparkling/utils/Compression.scala

**Benchmark results on EMR** 
Compression `NONE`:
```
DataFrameToH2OFrameConversionBenchmark results for the dataset 'random01Int4':
time: 8964 milliseconds
DataFrameToH2OFrameConversionBenchmark results for the dataset 'random01Int40':
time: 49782 milliseconds
DataFrameToH2OFrameConversionBenchmark results for the dataset 'random01Int400':
time: 428360 milliseconds
```
Compression `SNAPPY`:
```
DataFrameToH2OFrameConversionBenchmark results for the dataset 'random01Int4':
time: 8915 milliseconds
DataFrameToH2OFrameConversionBenchmark results for the dataset 'random01Int40':
time: 48033 milliseconds
DataFrameToH2OFrameConversionBenchmark results for the dataset 'random01Int400':
time: 413359 milliseconds
```
Compression `DEFLATE`:
```
DataFrameToH2OFrameConversionBenchmark results for the …
```

[SW-1995] Enabling Compression for REST API Conversions

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGLM.scala
py/src/ai/h2o/sparkling/ml/algos/H2OGLM.py
py/src/ai/h2o/sparkling/ml/params/H2OGLMParams.py

This parameter does not have any effect in H2O + will be removed from H2O codebase in 3.30

[SW-2033] Deprecate exactLambdas param on H2OGLM

---

core/src/main/scala/ai/h2o/sparkling/backend/shared/SharedBackendConf.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
py/src/ai/h2o/sparkling/SharedBackendConf.py

This PR tries to get the naming conventions of of the setter with `setNodeBasePort()` and `clientBasePort`

[SW-2035] Rename the 'setClientPortBase' on H2OConf to 'setClientBasePort'

---

core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConf.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/migration_guide.rst
py/src/ai/h2o/sparkling/ExternalBackendConf.py

This PR tries to get naming conventions of the setter aligned with its getter `clusterInfoFile` and property `spark.ext.h2o.cluster.info.name`.

[SW-2036] Rename 'setClusterConfigFile' on H2OConf to 'setClusterInfoFile'

---

utils/src/main/scala/org/apache/spark/expose/Logging.scala

Just tiny cleanup to avoid warning in the build.
On newer Spark versions the `org.apache.spark.internal.Logging` does not exist, so treat it just as string

[SW-2040] Fix doc warning: Could not find any member to link for org.apache.spark.internal.Logging

---

doc/src/site/sphinx/migration_guide.rst
py/src/ai/h2o/sparkling/ml/algos/H2OGridSearch.py

This should also be last place where we had inconsistencies between Scala & Python client.
All methods should be in sync now ( except in Python & R we have method ``hc.asSparkFrame`` but in Scala we have ``hc.asDataFrame``) -> we need to rename the method on Scala side, but that is scope of another PR https://0xdata.atlassian.net/browse/SW-2044)

[SW-2043] Deprecate get_grid_models, get_grid_models_params and get_grid_models_metrics params on H2OGridSearch

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OXGBoost.scala
py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py
py/src/ai/h2o/sparkling/ml/params/H2OXGBoostParams.py

Replacing setters and getters right away as this is internal H2O argument anyways

[SW-2045] Deprecate initial_score_interval on H2OXGBoost as it's only H2O's internal argument

---

gradle/wrapper/gradle-wrapper.properties

Not affecting us, but a critical bug was fixed in 6.2.2 https://github.com/gradle/gradle/releases

[SW-2049] Upgrade to Gradle 6.2.2

---

core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
core/src/test/scala/org/apache/spark/h2o/ConfigurationPropertiesTestSuite.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/migration_guide.rst
py/src/ai/h2o/sparkling/InternalBackendConf.py
py/tests/unit/with_runtime_clientless_sparkling/clientless_test_utils.py
r/src/R/ai/h2o/sparkling/InternalBackendConf.R

I have checked and actually these options are not used anywhere in the Sparkling Water, so wen user was specifying them, they did not have any effect & REST API was always open. Nevertheless, we should deprecate properly and remove in 3.30

[SW-2047] Deprecate options for disabling or enabling REST api on H2O worker nodes. It needs to be on because of REST client

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OXGBoost.scala
py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py
py/src/ai/h2o/sparkling/ml/params/H2OXGBoostParams.py

Same as _initial_score_interval. Internal argument only, should have never been exposed.
(discovered via training algos via rest)

[SW-2051] Deprecate _score_interval argument as it's only H2O's internal argument

---

core/src/main/scala/ai/h2o/sparkling/frame/H2OChunk.scala
core/src/test/scala/ai/h2o/sparkling/backend/external/RestApiUtilsTestSuite.scala
core/src/test/scala/org/apache/spark/h2o/converters/DataFrameConverterTest.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ChunkServlet.scala

This PR proposes to solve the problem via changing GET mehtod for downloading chunks to POST. Another way how to solve the problem could be to extend size limit of requests/headers. The chosen approach seems to give us no restrictions.

[SW-2064] asDataFrame/asSparkFrame Conversion Function Throws Exception on Wide Datasets

---

core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala

`setH2OCluster()` method on h2oConf has a side effect and internally calls `setExternalClusterMode()`

[SW-2071] InternalH2OBackend Shouldn't Call setH2OCluster

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

Getting `main` and `rel-3.28.1` synchronized before setting H2OCluster always to UTC

Revert "[SW-2069] Set H2O Cluster Time Zone only via REST (#1943)"

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtilsTestSuite.scala

The columns produced by DAI transformers was causing H2O algorithms to
fail since the name was not found in Spark logical plan.
Fixes https://0xdata.atlassian.net/browse/SW-2076

[SW-2076] Missing column sanitization when selecting columns

---

core/src/main/scala/ai/h2o/sparkling/backend/H2OAwareBaseRDD.scala
core/src/main/scala/ai/h2o/sparkling/backend/H2OAwareEmptyRDD.scala
core/src/main/scala/ai/h2o/sparkling/backend/H2OAwareRDD.scala
core/src/main/scala/ai/h2o/sparkling/backend/H2ODataFrame.scala
core/src/main/scala/ai/h2o/sparkling/backend/H2OFrameRelation.scala
core/src/main/scala/ai/h2o/sparkling/backend/H2ORDD.scala
core/src/main/scala/ai/h2o/sparkling/backend/NodeDesc.scala
core/src/main/scala/ai/h2o/sparkling/backend/Reader.scala
core/src/main/scala/ai/h2o/sparkling/backend/SparklingBackend.scala
core/src/main/scala/ai/h2o/sparkling/backend/Writer.scala
core/src/main/scala/ai/h2o/sparkling/backend/converters/SparkDataFrameConverter.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/LogUtil.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/ReflectionUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/RestApiUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/SharedBackendUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/SupportedTypes.scala
core/src/main/scala/ai/h2o/sparkling/frame/H2OChunk.scala
core/src/main/scala/ai/h2o/sparkling/frame/H2OFrame.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/H2ORpcEndpoint.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/test/scala/ai/h2o/sparkling/backend/utils/SupportedTypesTest.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoParamsHelper.scala

The reason why I'm moving the classes to ai.h2o.sparkling package is to have all internal classes in the `backend` package and so we can restrict access to all of them for the users. Since we will start creating Scala API I would like to have clear distinction.

[SW-2086] Move classes from org.apache.spark.h2o.utils to ai.h2o.sparkling

---

core/build.gradle

Last minor fix before going to bed :)

[SW-2126] Fix deprecation warning about duplicate paths in because of overwriting scala-editor.css file in Sparkling Water

---

core/src/main/scala/org/apache/spark/h2o/package.scala
core/src/main/scala/water/support/ModelMetricsSupport.scala
core/src/main/scala/water/support/ModelSerializationSupport.scala
doc/src/site/sphinx/deployment/load_mojo.rst
doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala

This was last support class in SW which is somehow referencing client

[SW-2139] Deprecate ModelSerializationSupport

---

doc/src/site/sphinx/pysparkling.rst
py/src/setup.py

I'm limiting this change to minimum. 
We could also remove the test dependency on pyspark in py/build.gradle and use the already downloaded spark distribution, but that just improves tests and would require new docker image. Will do that in another PR.
For more info please see the jira

[SW-2144] Don't setup dependency on pyspark & numpy

---

README.rst

Link for new contributor issues is non-existent so directed to SW project.

[SW-2165] Fix link to jira in README

---

doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/deployment/backends.rst

It seems that this property is only relevant to the external backend with the automatic start.

[SW-2170] Update description of spark.ext.h2o.external.cluster.size in SW Documentation

---

py/src/ai/h2o/sparkling/Initializer.py

In this case the pyspark version is actually version of databricks runtime.
According to DBC docs pyspark needs to be uninstalled and databricks-connect library installed ( which installs pyspark with the incompatible version) -> so we should not see any collisions for existing users

[SW-2174] Don't do version check in case user is using databricks-connect

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala

Calls like:
```
scala> val uri = new URI("http://127.0.0.1/mypath/")
scala> val url = uri.resolve("/3/CloudLock").toURL
url: java.net.URL = http://127.0.0.1/3/CloudLock
```
or
```
scala> val uri = new URI("http://127.0.0.1/mypath")
scala> val url = uri.resolve("3/CloudLock").toURL
url: java.net.URL = http://127.0.0.1/3/CloudLock
```
cause unwanted behavior.
The proposed solution tries to enforce the below case under all circumstances:
```
scala> val uri = new URI("http://127.0.0.1/mypath/")
scala> val url = uri.resolve("3/CloudLock").toURL
url: java.net.URL = http://127.0.0.1/mypath/3/CloudLock
```

[SW-2177] Context Path is Erased From Rest Calls

---

assembly/build.gradle

We should shadow the AWS libraries used in SW

[SW-2168] The AWS java sdk s3 in SW throws the exception: java.lang.IllegalStateException: Socket not created by this factory.

---

benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/H2OFrameToDataFrameConversionBenchmark.scala
core/src/integTest/scala/ai/h2o/sparkling/IntegrationTestSuite.scala
core/src/integTest/scala/ai/h2o/sparkling/internal/H2OContextConversionOnSubsetExecutors.scala
core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
core/src/main/scala/ai/h2o/sparkling/backend/api/h2oframes/H2OFramesHandler.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
core/src/main/scala/org/apache/spark/h2o/JavaH2OContext.java
core/src/test/scala/ai/h2o/sparkling/ConfigurationPropertiesTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/H2OFrameTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/backend/api/dataframes/DataFramesHandlerTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/backend/api/scalainterpreter/ScalaCodeHandlerTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataExchangeTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/SupportedRDDConverterTestSuite.scala
doc/src/site/sphinx/deployment/use_on_zeppelin.rst
doc/src/site/sphinx/devel/integ_tests.rst
doc/src/site/sphinx/migration_guide.rst
doc/src/site/sphinx/tutorials/shap_values.rst
doc/src/site/sphinx/tutorials/spark_h2o_conversions.rst
doc/src/site/sphinx/tutorials/sw_automl.rst
doc/src/site/sphinx/tutorials/sw_drf.rst
doc/src/site/sphinx/tutorials/sw_kmeans.rst
doc/src/site/sphinx/tutorials/sw_target_encoder.rst
doc/src/site/sphinx/tutorials/sw_xgboost.rst
ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala
py/src/ai/h2o/sparkling/H2OContext.py
r/src/R/ai/h2o/sparkling/H2OContext.R

To be fully consistent with our Python and R APIs

[SW-2044] Introduce method asSparkFrame on H2OContext.scala and deprecate asDataFrame

---

assembly/build.gradle

After the original fix the s3 support was broken. We also need to shade http client library to ensure our AWS support is working. Our AWS version is compatible with the specific http client library. 
As a side effect this fixes benchmarks

[SW-2168][FollowUp] The AWS java sdk s3 in SW throws the exception: java.lang.IllegalStateException

---

core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

No need to even mention SPARK_HOME, it is not required for the version chck. In case of embedded applications it might be confusing to see error that SPARK_HOME is not set.

[SW-502] SW Runtime is complaining about missing SPARK_HOME during version check

---

bin/sparkling-env.sh

We need to respect Spark python environment even for the python libraries checks

[SW-1569] Sparkling water fails to detect newer version of colorama

---

core/src/test/scala/ai/h2o/sparkling/ConfigurationPropertiesTestSuite.scala
core/src/test/scala/ai/h2o/sparkling/SharedH2OTestContext.scala

As our tests our running in client-less mode in Scala as well, we no longer need this hack as H2O never calls System.exit on Spark driver.
As the side-effect the time of our unit tests after removing this is lowered by around 20 minutes 🎉

[SW-2234] Remove System.exit hack used in tests 

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/SharedBackendUtils.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
doc/src/site/sphinx/migration_guide.rst

I'm not moving out of the client section on the documentation as https://github.com/h2oai/sparkling-water/pull/2114 removes the section

[SW-2240] Ensure flow dir is specified also on worker nodes

---

py/tests/integration/integ_test_utils.py

Leftovers after the parameter deprecations

[SW-2251] Remove usage of deprecated properties in Python integration tests

---

core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala

The migration guide already contains the information, I just forgot to the the deprecation as part of that change

[SW-2255] Deprecate H2OConf and H2OContext in package org.apache.spark

---

doc/src/site/sphinx/devel/integ_tests.rst
doc/src/site/sphinx/tutorials/import_export_s3.rst
doc/src/site/sphinx/tutorials/shap_values.rst
doc/src/site/sphinx/tutorials/sw_automl.rst
doc/src/site/sphinx/tutorials/sw_drf.rst
doc/src/site/sphinx/tutorials/sw_kmeans.rst
doc/src/site/sphinx/tutorials/sw_target_encoder.rst
doc/src/site/sphinx/tutorials/sw_xgboost.rst

Missing updates after updating to ai.h2o.sparkling.H2OContext. Need to switch to ai.h2o.sparkling.H2OFrame api.

[SW-2259] Replace old H2OFrame api mentions in docs

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala

@mn-mikke I decided for different approach, deprecate in 3.32 and change in 3.34 instead of supporting two paths in the code.

[SW-2264] Warn user of upcomming change in grid search in 3.32

---

doc/src/site/sphinx/tutorials/hive_support.rst

User on gitter was confused as he wanted to use hive in non-kerberized env but our doc mention just usage with Kerberos. Trying to make it a bit clearer

[SW-2267] Document hive support in non-kerberized environments

---

.gitignore
py/tests/pytest.ini

Doing some small improvements whilst testing kubernetes

[SW-2275] Ensure pytest cache is generated into build directory

---

doc/src/site/sphinx/tutorials/shap_values.rst
doc/src/site/sphinx/tutorials/sw_automl.rst
doc/src/site/sphinx/tutorials/sw_drf.rst
doc/src/site/sphinx/tutorials/sw_kmeans.rst
doc/src/site/sphinx/tutorials/sw_target_encoder.rst
doc/src/site/sphinx/tutorials/sw_xgboost.rst

Reading data via `H2OFrame(new Uri(...))` seems to doesn't work on master anymore.

[SW-2280] Fix Reading of Spark DataFrames in SW Tutorials

---

core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala

Right join has been fixed as part of https://0xdata.atlassian.net/browse/PUBDEV-7362 and we can use H2O implementation

[SW-2283] Switch inner join implementation to use H2O

---

doc/src/site/sphinx/tutorials/shap_values.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
ml/src/test/scala/ai/h2o/sparkling/ml/ParameterSetters.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/BinomialPredictionTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2ODRFTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/RegressionPredictionTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OSupervisedMOJOModelTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OTreeBasedSupervisedMOJOModelTestSuite.scala
py/src/ai/h2o/sparkling/ml/algos/H2OAutoML.py
py/src/ai/h2o/sparkling/ml/algos/H2ODRF.py
py/src/ai/h2o/sparkling/ml/algos/H2ODeepLearning.py
py/src/ai/h2o/sparkling/ml/algos/H2OGBM.py
py/src/ai/h2o/sparkling/ml/algos/H2OGLM.py
py/src/ai/h2o/sparkling/ml/algos/H2OKMeans.py
py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py
py/src/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.py
py/src/ai/h2o/sparkling/ml/models/H2OMOJOSettings.py
py/src/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.py
py/src/ai/h2o/sparkling/ml/params/H2OCommonParams.py
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.R
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOSettings.R
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOSettings.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/PredictionWithContributions.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.scala

I've tried to expose contributions as `StructType`. To achieve that, we would have to change the whole concept  using udfs during scoring and to use case classes in prediction traits. IMHO, it's not good approach to do such a change in fix release. I think there is opportunity to do it for one of the major release and also reconsider existence of the current map types (probabilities, etc.)

[SW-1668] Structure Contributions in the 'detailed_prediction' Colums as MapType

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala

Got this intermittent error on master nightly: https://sparkling-jenkins.h2o.ai/job/NIGHTLY_H2O_BRANCH/job/master/47/
```
ai.h2o.sparkling.backend.exceptions.RestApiNotReachableException: External H2O node 172.17.0.2:54321 is not reachable.
Please verify that you are passing ip and port of existing cluster node and the cluster
is running with web enabled.
at ai.h2o.sparkling.backend.utils.RestCommunication$class.throwRestApiNotReachableException(RestCommunication.scala:319)
at ai.h2o.sparkling.backend.utils.RestCommunication$class.readURLContent(RestCommunication.scala:277)
at ai.h2o.sparkling.backend.utils.RestApiUtils$.readURLContent(RestApiUtils.scala:115)
at ai.h2o.sparkling.backend.utils.RestCommunication$class.request(RestCommunication.scala:167)
at …
```

[SW-2289] Fix java.lang.IllegalArgumentException: requirement failed: The auto-closable resource can't be null

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtilsTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OKMeansTestSuite.scala

@mn-mikke promised this change a while ago. As you suggested, we can check the validity even before we start the training

[SW-2062] Verify that training frame has all columns constants using Spark instead of H2O error

---

doc/build.gradle

The options `useDoctreeCache` and `doctreeCacheDirectory ` of  [`sphinx-gradle-plugin`](https://trustin.github.io/sphinx-gradle-plugin/configuration.html) seem to not have any effect.

[SW-2297] Exclude Content of site/.doctrees from SW Distribution Archive

---

api-generation/build.gradle
py/build.gradle

Diff before master and rel before fix:
```
516,522c516
< |    +--- ai.h2o:mojo2-runtime-impl:2.3.0 (*)
< |    \--- project :sparkling-water-api-generation
< |         +--- org.scala-lang:scala-library:2.11.12
< |         +--- ai.h2o:h2o-algos:3.30.0.4 (*)
< |         +--- ai.h2o:h2o-automl:3.30.0.4 (*)
< |         +--- ai.h2o:h2o-ext-xgboost:3.30.0.4 (*)
< |         \--- project :sparkling-water-utils (*)
---
> |    \--- ai.h2o:mojo2-runtime-impl:2.3.0 (*)
742,747c736
< |    +--- ai.h2o:mojo2-runtime-impl:2.3.0 (*)
< |    \--- project :sparkling-water-api-generation
< |         +--- ai.h2o:h2o-algos:3.30.0.4 (*)
< |         +--- ai.h2o:h2o-automl:3.30.0.4 (*)
< |         +--- ai.h2o:h2o-ext-xgboost:3.30.0.4 (*)
< |         \--- project :sparkling-water-utils (*)
---
> |    \--- …
```

[SW-2304] Avoid putting scala-lib to shadowJar

---

gradle/wrapper/gradle-wrapper.properties

Since we need to build a new docker image because of https://github.com/h2oai/sparkling-water/pull/2179, now it's a good time to also upgrade Gradle to the latest version

[SW-2309] Upgrade Gradle to 6.5

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/IgnoredParameters.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/ParameterNameConverter.scala

The output parameter are `randLink` and `randFamily`. I'm just wondering whether we shouldn't rename them to `randomLink` and `randomFamily`

[SW-2318] Expose rand_link and rand_family on GLM

---

core/src/main/scala/ai/h2o/sparkling/H2OContext.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala

We use the code for both backends so avoid wording which is specific just for external backend and might confuse some users

[SW-2319] Replace 'External H2O Node' with just 'H2O Node' as the code is now used in both backends

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/RestApiUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/H2ORpcEndpoint.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
core/src/test/scala/ai/h2o/sparkling/H2OContextTestSuite.scala

This change ensures that the REST API communicates with the leader node from the beginning.
In Internal backend, we can first report IP & port of some node which might not be a leader and we reassign it later. However, calls for the cloud lock and verification calls such for version and web open are done before this and therefore communicate with the non-leader node.
This is relevant only to the internal backend as in the external cluster, in the auto cluster start we provide automatically leader IP and port and in manual cluster start the users need to provide leader node IP.

[SW-2317] Use leader node from the beginning of Rest API communication

---

py/tests/unit/with_runtime_sparkling/test_mojo.py

H2O exposed a new parameter h2o-core/src/main/java/hex/Model.java which leads to failure of this test

[SW-2344] Fix mojo test -> H2O added a new parameter and therefore number of parameters does not match now

---

core/src/test/scala/ai/h2o/sparkling/backend/api/scalainterpreter/ScalaInterpreterServletTestSuite.scala
repl/src/main/scala/ai/h2o/sparkling/repl/BaseH2OInterpreter.scala

Oldtimer JIRA. Implemented while waiting for the K8s tests to finish.
See https://0xdata.atlassian.net/browse/SW-352 for more details

[SW-352] Flow UI Scala Repl: use paste mode to interpret commands passed through Flow UI

---

bin/build-kubernetes-images.sh
kubernetes/build.gradle

Last from K8S related PRs.
For official releases we depend on H2O images, but since we build our own h2o in nightly tests, we also need to create such docker image from scratch

[SW-2294] Base non-nightly external-backend k8s image on h2o image

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/ProblemType.scala

family
- negativebinomial - https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/glm.html#negative-binomial-models
distribution
- ordinal - assume it will the same as for family
- modified_huber- from h2o-code: https://github.com/h2oai/h2o-3/blob/ba26fe89fb81c50fd60d386017a33fc02a31f79e/h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java#L196

[SW-1407][FOLLOWUP] Add missing mappings for family and distribution

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
core/src/main/scala/water/webserver/jetty9/SparklingWaterJettyHelper.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
py/src/ai/h2o/sparkling/SharedBackendConf.py
r/src/R/ai/h2o/sparkling/SharedBackendConf.R

Increase the default value to 5 minutes and make it configurable as well

[SW-2356] Fix timeout on long running Rest API commands through Proxy

---

r/build.gradle

I discovered that after fixing the intermittent issues with R tests, our tests suite does not fail when there is a failing test. Verified locally and should be ok with this change.

[SW-2360] R tests do not fail in gradle when there is failed test

---

core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/SpreadRDDBuilder.scala
doc/src/site/sphinx/configuration/configuration_properties.rst
ml/src/main/scala/ai/h2o/sparkling/ml/algos/ProblemType.scala
py/src/ai/h2o/sparkling/InternalBackendConf.py
r/src/R/ai/h2o/sparkling/InternalBackendConf.R

[SW-2372] Expose option used for waiting before the clouding starts in internal backend

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OXGBoostParams.scala
py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py
py/src/ai/h2o/sparkling/ml/params/H2OXGBoostParams.py

H2O has removed ``minSumHessianInLeaf`` and ``minDataInLeaf`` and our build on rel-3.30.1 started to fail as the we still refer to them

[SW-2381] Deprecate removed XGBoost options

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/ProblemType.scala

[This commit](https://github.com/h2oai/h2o-3/commit/848e9d5d97df897a405130ed391d99a20b9ff68f) to H2O-3 codebase added these two options.

[SW-2399] Missing mappings for 'negativebinomial' and 'fractionalbinomial' in ProblemType.distributionToProblemType

---

ci/Jenkinsfile-release

Verified and the generated release notes have the same format as before. 
We are now able to mark a JIRA by a special tag which ensures that it will not be included in the release notes. This may be helpful for some technical tasks which do not have any effect on users.
By not setting the field, the JIRA will be included in the release notes, so the default behaviour is not changing

[SW-1366] Be able to annotate jira with flag indicating the change should not be mentioned in release notes

---

doc/src/site/sphinx/ml/sw_drf.rst
ml/src/test/scala/ai/h2o/sparkling/ml/PipelinePredictionTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/StreamingPipelinePredictionTestSuite.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
py/tests/unit/with_runtime_sparkling/test_H2O_GBM_estimator.py

The `detailed_predictions` column needs to be removed in release branch since `Map` type can't be used except operations.

[SW-2406][FOLLOWUP] Remove detailed_predictions from DataFrame comparision

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/IgnoredParameters.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OSupervisedAlgorithm.scala

I have also a question about two parameters which are not included in the [MOJO json file](https://gist.github.com/mn-mikke/8177b9503bcffb124131c5b8e15b5b46#file-kmeans-model-json). The parameters are:
- `max_categorical_levels` - This parameter is mentioned in [H2O-3 documentation](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/k-means.html). So shouldn't be included in MOJO as well?
- `weights_column` - Is there any plan to implement this parameter on Kmeans. Or it doesn't make sence for KMeans at all?

[SW-2423] Remove Irrelevant Parameters from Kmeans API

---

doc/src/main/scala/ai/h2o/sparkling/doc/generation/ParametersTemplate.scala

H2OWord2VecTokenizer has no default value for input column and documentation generation fails.
H2OWord2VecTokenizer will be removed as part of the Word2Vec but before that, this commit ensures the CI is green

[SW-2427] Fix parameter generation in doc

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/IgnoredParameters.scala
py/tests/unit/with_runtime_sparkling/test_mojo.py

There is no need to ignore the `max_hit_ratio_k` parameter during API generation since it has been removed from H2O-3 codebase by https://github.com/h2oai/h2o-3/pull/4926.

[SW-2442] Remove "max_hit_ratio_k" from the List of Deprecated Parameters

---

extensions/src/main/scala/water/fvec/H2OFrame.scala
ml/src/test/scala/ai/h2o/sparkling/ml/models/MOJOParameterTestSuite.scala
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py

The method was removed by this commit https://github.com/h2oai/h2o-3/commit/96ac0bfcd5c6fa4150b39089add644c03c8de90d#diff-d63531c6c93a765957616530e4121ef1 in H2O-3.

[SW-2445] Add logic of FrameUtils.guessParserSetup to Sparkling Water

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AutoMLIgnoredParameters.scala

The parameter will be exposed in a different PR, just need to make SW build green again. Related PR: https://github.com/h2oai/h2o-3/pull/4927

[SW-2453] Newly Introduced Parameter 'preprocessing' Broke SW API Generation

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AlgorithmConfigurations.scala
doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/DeprecatedDistribution.scala
py/src/ai/h2o/sparkling/ml/params/DeprecatedDistribution.py

The `distribution` parameter was exposed in past, but there is no equivalent for the parameter in H2O-3 API.

[SW-2433] Deprecate 'distribution' Parameter on H2OGLM

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/RestApiUtils.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala

The goal of this PR is to remove ping messages in spark-shell by default:
```
10-08 07:32:27.385 10.159.129.72:54321   #2488   Thread-62  INFO ai.h2o.sparkling.backend.utils.RestApiUtils: H2O node http://10.159.129.70:54321/3/Ping successfully responded for the GET.
10-08 07:32:37.389 10.159.129.72:54321   #2488   Thread-62  INFO ai.h2o.sparkling.backend.utils.RestApiUtils: H2O node http://10.159.129.70:54321/3/Ping successfully responded for the GET.
10-08 07:32:47.393 10.159.129.72:54321   #2488   Thread-62  INFO ai.h2o.sparkling.backend.utils.RestApiUtils: H2O node http://10.159.129.70:54321/3/Ping successfully responded for the GET.
10-08 07:32:57.397 10.159.129.72:54321   #2488   Thread-62  INFO ai.h2o.sparkling.backend.utils.RestApiUtils: H2O node http://10.159.129.70:54321/3/Ping …
```

[SW-2463] Move Ping Messages to Debug Logging Level

---

core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterCategoricalTestSuite.scala

the test fails on   spark 2.2 - 2.4 due to too big computation task. ingnoring for now

[SW-2449][FOLLOWUP] Ignore test with more than 10M unique values in one partition

---

dist/build.gradle

The PR https://github.com/h2oai/sparkling-water/pull/2277 moved compiled pdf from `booklet/build` to `booklet/build/src` which broke publishing of the pdf.

[SW-2467] Fix Publishing of SW Booklet

---

py/build.gradle
py/tests/unit/with_runtime_sparkling/conftest.py

The goal of this PR is to enable execution of individual tests. E.g.:
```./gradlew :sparkling-water-py:test -Ptests="tests/unit/with_runtime_sparkling/test_target_encoder.py"```
This should help to speed up development of Python related features in Sparkling Water.

[SW-2468] Enable to Run Python Tests with SW Runtime Individually

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

Already replace by `logLevel` and `setLogLevel`

[SW-2232] Remove deprecated setH2OClientLogLevel, setH2ONodeLogLevel, h2oClientLogLevel, h2oNodeLogLevel

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

Already replaced by `basePort`, `setBasePort`

[SW-2243] Remove deprecated setClientBasePort, setNodeBasePort, clientBasePort, nodeBasePort

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala

Already replaced by `spark.ext.h2o.flow.dir`

[SW-2241] Remove Deprecated spark.ext.h2o.client.flow.dir Option

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala

Already replaced by `icedDir` and `setIcedDir`

[SW-2230] Remove deprecated setClientIcedDir, setNodeIcedDir, clientIcedDir and nodeIcedDir

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

already replaced by `logDir` and `setLogDir`.

[SW-2238] Remove deprecated setH2OClientLogDir, setH2ONodeLogDir, h2oClientLogDir, h2oNodeLogDir

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

Already replaced by `extraProperties` and `setExtraProperties`

[SW-2245] Remove deprecated setClientExtraProperties, setNodeExtraProperties, clientExtraProperties, nodeExtraProperties

---

core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterCategoricalTestSuite.scala
extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/ConvertCategoricalToStringColumnsTask.java
extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/LocalNodeDomains.java
extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/UpdateCategoricalIndicesTask.java

[`UpdateCategoricalIndicesTask`](https://github.com/h2oai/sparkling-water/blob/68a8a90d4e3c9242fb5109d58be3585da2da89ea/extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ImportFrameHandler.scala#L62) used to work with the original local domains even if the column was converted to a string column due to too exceeding the maximum of categorical levels.

[SW-2470] Fails to Convert Categorical Columns on Big Dataset and Identity Column

---

extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ImportFrameHandler.scala

Possible error:
```
{
"__meta":{
"schema_version":3,
"schema_name":"H2OErrorV3",
"schema_type":"H2OError"
},
"timestamp":1604442830105,
"error_url":"/3/FinalizeFrame",
"msg":"\n\nERROR MESSAGE:\n\nDistributedException from 37b2c4d0bd01/172.17.0.2:54323: 'null'\n\n",
"dev_msg":"\n\nERROR MESSAGE:\n\nDistributedException from 37b2c4d0bd01/172.17.0.2:54323: 'null'\n\n",
"http_status":500,
"values":{
},
"exception_type":"water.util.DistributedException",
"exception_msg":"\n\nERROR MESSAGE:\n\nDistributedException from 37b2c4d0bd01/172.17.0.2:54323: 'null'\n\n",
"stacktrace":[
"DistributedException from 37b2c4d0bd01/172.17.0.2:54323: 'null', caused by java.lang.NullPointerException",
"    water.RPC.result(RPC.java:240)",
"    water.RPC.get(RPC.java:256)",
" …
```

[SW-2469][FOLLOWUP] Unlocking of H2O Frame Could Throw NPE

---

core/build.gradle
gradle/bench.gradle
gradle/itest.gradle
gradle/scala.gradle
gradle/sparkTest.gradle

The current state:
```
ai.h2o.sparkling.DataSourceTestSuite > Reading H2OFrame using key option FAILED
org.scalatest.exceptions.TestFailedException at DataSourceTestSuite.scala:41
```
After this change:
```
ai.h2o.sparkling.DataSourceTestSuite > Reading H2OFrame using key option FAILED
org.scalatest.exceptions.TestFailedException: 1 equaled 1 Number of columns should match
at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1560)
at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:503)
at ai.h2o.sparkling.DataSourceTestSuite.$anonfun$new$1(DataSourceTestSuite.scala:41)
at …
```

[SW-2479] Show Stack Trace of Exceptions in Failed Tests

---

ci/commons.groovy

The publishing of nightly images is failing on installing docker.io:
```
[2020-11-08T23:14:55.251Z] + sudo apt -y install docker.io
[2020-11-08T23:14:55.251Z] 
[2020-11-08T23:14:55.251Z] WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
[2020-11-08T23:14:55.251Z] 
[2020-11-08T23:14:56.615Z] Reading package lists...
[2020-11-08T23:14:56.615Z] Building dependency tree...
[2020-11-08T23:14:56.615Z] Reading state information...
[2020-11-08T23:14:56.615Z] The following additional packages will be installed:
[2020-11-08T23:14:56.615Z]   apparmor bridge-utils cgroupfs-mount containerd dns-root-data dnsmasq-base
[2020-11-08T23:14:56.615Z]   iptables libapparmor-perl libnetfilter-conntrack3 libnfnetlink0 pigz runc
[2020-11-08T23:14:56.615Z]   ubuntu-fan …
```

[SW-2480] Fix Publishing of Nightly Build Images to DockerHub

---

ci/aws/terraform/modules/jenkins/scripts/init.sh

The repository key has changed: https://www.jenkins.io/doc/book/installing/linux/#long-term-support-release

[SW-2483] Fix Deployment of Sparkling Water Testing Infrastructure

---

ci/Jenkinsfile-databricks
ci/Jenkinsfile-kubernetes
ci/sparklingWaterPipeline.groovy

Error on rel-3.32:
```
[2020-11-16T16:55:55.487Z] Step 5/11 : COPY h2o.tar.gz /opt/spark/R/lib/h2o.tar.gz
[2020-11-16T16:56:21.978Z]  ---> 86804565af88
[2020-11-16T16:56:21.978Z] Step 6/11 : RUN cd /opt/spark/R/lib && R CMD INSTALL h2o.tar.gz
[2020-11-16T16:56:28.512Z]  ---> Running in 1f1be0eff554
[2020-11-16T16:56:38.449Z] Error in untar2(tarfile, files, list, exdir, restore_times) : 
[2020-11-16T16:56:38.449Z]   incomplete block on file
[2020-11-16T16:56:38.449Z] The command '/bin/sh -c cd /opt/spark/R/lib && R CMD INSTALL h2o.tar.gz' returned a non-zero code: 1
[2020-11-16T16:56:38.449Z] Done!
```
Building of R nightly images failed since curl downloaded R H2O package from non-existing location. Local build of H2O-3 build should be picked up instead. 
Decision logic: …

[SW-2480][FOLLOWUP] Fix Publishing of R Nightly Images to DockerHub

---

core/build.gradle
gradle.properties

Upgrade is needed because of running DAI big data recipe on Sparkling Water.

[SW-2486] Upgrade MOJO runtime to 2.5.3

---

ml/src/test/scala/ai/h2o/sparkling/ml/models/MOJOParameterTestSuite.scala
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py

Thanks to the fix in  https://github.com/h2oai/h2o-3/pull/5136 SW can test `getInteractionConstraints()` on `H2OXGboostMOJOModel`.

[SW-2482][FOLLOWUP] Test Propagation of Interactions Constraints to MOJO Model

---

booklet/src/sections/kubernetes.tex
doc/src/site/sphinx/deployment/kubernetes.rst
kubernetes/build.gradle
kubernetes/src/r/initTest.R

This PR should fix R tests on K8s.
More details in https://github.com/sparklyr/sparklyr/issues/2832

[SW-2489] Downgrade Sparklyr to 1.3.1 due to Problems with K8s Deployment

---

ci/sparklingWaterPipeline.groovy

The build docker images were just untagged not deleted. 
```
[2020-11-29T20:32:01.676Z] + docker rmi h2oai/sparkling-water-python:latest-nightly-2.4
[2020-11-29T20:32:01.676Z] Untagged: h2oai/sparkling-water-python:latest-nightly-2.4
[2020-11-29T20:32:01.676Z] Untagged: h2oai/sparkling-water-python@sha256:0fe7ec838c4325e8adeeee86dda5a8ce9c858be71bc3e77df0de1d214afab23d
```
From documentation https://docs.docker.com/engine/reference/commandline/rmi/: 
```If an image has multiple tags, using this command with the tag as a parameter only removes the tag. If the tag is the only one for the image, both the image and the tag are removed.```

[SW-2493] Proper Removal of Sparkling Water Images from Local Docker Registry

---

ci/sparklingWaterPipeline.groovy

All branches share the same tag for nightly builds `latest-nightly`. This tag randomly contains builds from `rel-3.32` or `master`.

[SW-2494] Add Branch Name to Nightly Artefact on DockerHub

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOReader.scala
utils/src/main/scala/ai/h2o/sparkling/utils/SparkSessionUtils.scala

Jira ticket: https://h2oai.atlassian.net/browse/SW-2491
Reported problem: https://github.com/h2oai/sparkling-water/issues/2344
`Paths.get(path, H2OMOJOProps.serializedFileName)` removes the second slash from the path and produces: 
```
s3:/marek-test2/target_encodingpipeline/stages/0_H2OTargetEncoder_01b1058521ed/mojo_model
```
new Path(path, H2OMOJOProps.serializedFileName) is used internally in Spark for path concatenation and will produce:
```
s3://marek-test2/target_encodingpipeline/stages/0_H2OTargetEncoder_01b1058521ed/mojo_model
```
Tested the fix manually on EMR.

[SW-2491] Loading of Pipeline Containing SW Stage Throws NPE

---

ci/Jenkinsfile-kubernetes
kubernetes/src/r/initTest.R

Some K8s test are failing due to referencing wrong pod names:
```
+ kubectl run -n default -i --tty sparkling-water-app --restart=Never --labels spark-driver-selector=sparkling-water-app --image=524466471676.dkr.ecr.us-east-2.amazonaws.com/sw_kubernetes_repo/sparkling-water:scala-3.32.0.3-1-2.4 -- /opt/spark/bin/spark-submit --conf spark.kubernetes.container.image=524466471676.dkr.ecr.us-east-2.amazonaws.com/sw_kubernetes_repo/sparkling-water:scala-3.32.0.3-1-2.4 --conf spark.kubernetes.driver.pod.name=driver-scala --conf spark.scheduler.minRegisteredResourcesRatio=1 --master k8s://https://A6560DFE7DC91C583A6AA479DB047E03.yl4.us-east-2.eks.amazonaws.com --deploy-mode client --name test --conf spark.ext.h2o.backend.cluster.mode=external --conf spark.ext.h2o.external.start.mode=auto --conf …
```

[SW-2490] Rename Driver Pods to Fix K8s Tests in Client Mode

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala

In automatic external backend of K8s deployment, cloud locking may fail since H2O headless service may route a call to a non leader node during its initialization phase.

[SW-2498] Try to Lock Cloud Multiple Times

---

core/src/main/scala/ai/h2o/sparkling/H2OContext.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/AzureDatabricksUtils.scala
core/src/main/scala/org/apache/spark/h2o/ui/H2OClusterInfo.scala
core/src/main/scala/org/apache/spark/h2o/ui/SparklingWaterInfoPage.scala
core/src/main/scala_spark_others/org/apache/spark/h2o/SparkSpecificUtils.scala

There are two problems.
- Databricks chanced base address which is not easy to resolve since contains a random number which is not stored anywhere on the driver or in the environment properties. The problem is solved via resolving base address in the web browser.
More details on: ```https://docs.microsoft.com/en-us/azure/databricks/workspace/per-workspace-urls```
- The `UIUtils.headerSparkPage` method in   Databricks Spark has more parameters than Apache Spark. I solved the problem via reflection call.
Databricks: ```
request: javax.servlet.http.HttpServletRequest,
title: String,content: => Seq[scala.xml.Node],
activeTab: org.apache.spark.ui.SparkUITab,
helpText: Option[String],
showVisualization: Boolean,
useDataTables: Boolean,
supportScreenshot: Boolean```
Apache: ```
request: …
```

[SW-2496] Fix the Flow link for Databricks Azure

---

py/tests/unit/with_runtime_sparkling/test_isolation_forest.py

Broken test:
```
[2020-12-19T19:21:23.165Z] 	     def testExplicitValidationFrameOnIsolationForest(spark, prostateDataset):
[2020-12-19T19:21:23.165Z] 	         validationDatasetPath = "file://" + os.path.abspath("../examples/smalldata/prostate/prostate_anomaly_validation.csv")
[2020-12-19T19:21:23.165Z] 	         validatationDataset = spark.read.csv(validationDatasetPath, header=True, inferSchema=True)
[2020-12-19T19:21:23.165Z] 	     
[2020-12-19T19:21:23.165Z] 	         algo = H2OIsolationForest(seed=1, validationDataFrame=validatationDataset, validationLabelCol="isAnomaly")
[2020-12-19T19:21:23.165Z] 	         model = algo.fit(prostateDataset)
[2020-12-19T19:21:23.165Z] 	         metrics = model.getValidationMetrics()
[2020-12-19T19:21:23.165Z] 	     
[2020-12-19T19:21:23.165Z] 	 > …
```

[SW-2506] Fix Python Isolation Forest Test after H2O-3 Changes

---

core/src/main/scala/ai/h2o/sparkling/backend/utils/ProxyStarter.scala

Updated `ProxyStarter.scala`. so that when tries to bind on a port it uses the address `0.0.0.0`
The problem description: https://github.com/h2oai/sparkling-water/issues/2414

[SW-2503] Tried using port 54321 for Flow proxy, but port was already occupied

---

ml/src/test/scala/ai/h2o/sparkling/ml/algos/AnomalyPredictionTestSuite.scala

Tests randomly fail:
```
[2020-12-23T11:40:38.708Z]     org.scalatest.exceptions.TestFailedException: 4.64 equaled 4.64
[2020-12-23T11:40:38.708Z]         at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
[2020-12-23T11:40:38.708Z]         at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
[2020-12-23T11:40:38.708Z]         at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1560)
[2020-12-23T11:40:38.708Z]         at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:503)
[2020-12-23T11:40:38.708Z]         at ai.h2o.sparkling.ml.algos.AnomalyPredictionTestSuite.$anonfun$new$3(AnomalyPredictionTestSuite.scala:62)
[2020-12-23T11:40:38.709Z]         at …
```

[SW-2507] Set Seed in AnomalyPredictionTestSuite

---

ci/Jenkinsfile-kubernetes

After everything is finished. Spark driver pod remains in a running state for several minutes. This PR helps tests to be always green. The issue will be definitely fixed after rewriting automatic external backend to H2O K8s operator.

[SW-2509] Increase Limit of K8s Tests for Automatic External Backend

---

ci/Jenkinsfile-release

H2O-3 doesn't run on 32-bit architecture anyway.

[SW-2513] Stop Publishing 32bit Artifacts to Conda Repository

---

py-scoring/src/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.py
py/tests/unit/with_runtime_sparkling/test_target_encoder.py

A similar logic for the detections of a training dataset is in the [Scala backend](https://github.com/h2oai/sparkling-water/blob/e876be3dfdfc6192fe5b558403a0c8227523f360/ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala#L86). Since the Spark [Pipeline](https://github.com/apache/spark/blob/master/python/pyspark/ml/pipeline.py#L29) class has no java backend, the [logic](https://github.com/h2oai/sparkling-water/compare/mn/SW-2515?expand=1#diff-a9c840719ab642a05309990ed6049281fc5c16d0e9727feb30449f1c76cfb577R29) must in the Python wrapper as well.

[SW-2515] Fix TargetEncoder for Usage in Python Pipeline

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderMOJOModel.scala

Eech executor has to call get `mojoGetter()` method independently to get [the local path of each executor](https://github.com/h2oai/sparkling-water/blob/master/scoring/src/main/scala/ai/h2o/sparkling/ml/models/HasMojo.scala#L52).

[SW-2517] Fix TargetEncoder MOJO for Distributed Environment

---

bin/sparkling-env.sh
booklet/src/sections/deployment.tex
booklet/src/sections/productionazing.tex

Pysparkling package was moved inside SW zip file from `py/build/dist` to `py` during introduction of the python scoring package.

[SW-2504][FOLLOWUP] Fix Bootstrap of Pysparkling

---

ml/src/test/scala/ai/h2o/sparkling/ml/algos/AnomalyPredictionTestSuite.scala

The random error in nightly builds:
```
[2021-01-19T19:09:56.562Z] ai.h2o.sparkling.ml.algos.AnomalyPredictionTestSuite > predictionCol content FAILED
[2021-01-19T19:09:56.562Z]     org.scalatest.exceptions.TestFailedException: 6.28 equaled 6.28
[2021-01-19T19:09:56.562Z]         at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
[2021-01-19T19:09:56.562Z]         at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
[2021-01-19T19:09:56.562Z]         at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
[2021-01-19T19:09:56.562Z]         at ai.h2o.sparkling.ml.algos.AnomalyPredictionTestSuite$$anonfun$1.apply$mcV$sp(AnomalyPredictionTestSuite.scala:46)
[2021-01-19T19:09:56.562Z]         at …
```

[SW-2519] Fix Flaky Test in AnomalyPredictionTestSuite

---

py/build.gradle

The error is caused by the creation of scoring packaning and moving test files under the `build` folder:
```
Task :sparkling-water-py:integTestPython FAILED
[2021-01-24T18:56:07.319Z] [python] /home/jenkins/.gradle/python/3.6.10/2.3.4/bin/python /home/jenkins/workspace/NIGHTLY_H2O_BRANCH_master-spark-2.3-external/py/build/tests/test_runner.py '/home/jenkins/workspace/NIGHTLY_H2O_BRANCH_master-spark-2.3-external/py/build/tests/integration --ignore=/home/jenkins/workspace/NIGHTLY_H2O_BRANCH_master-spark-2.3-external/py/build/tests/integration/external_only' /home/jenkins/workspace/NIGHTLY_H2O_BRANCH_master-spark-2.3-external/py/build/dist/h2o_pysparkling_2.3-3.34.0.1-1-2.3.zip spark.testing=true spark.ext.h2o.backend.cluster.mode=external …
```

[SW-2504][FOLLOWUP] Fix Execution of Integration Tests in Nightly Builds

---

README.rst

The image link is invalid, so I decided to remove completely. Documentation is self-hosted and readme.md contains links to documentation pages for a given spark version.

[SW-2523] Remove Documentation Badge From Redme.md

---

booklet/src/sections/productionazing.tex
doc/src/site/sphinx/migration_guide.rst
py-scoring/src/ai/h2o/sparkling/ml/params/H2OMOJOModelParams.py
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala

The method can't be removed since it's utilized by `H2OGridSearch` and there is not alternative in R API.

[SW-2447] Remove Deprecation of `getTrainingParams` on H2OMOJOModel

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OGridSearchTestSuite.scala

jira: https://h2oai.atlassian.net/jira/software/c/projects/SW/issues
issue for getGridModelsMetrics(): https://github.com/h2oai/sparkling-water/issues/2468
I've noticed getGridModelsParams() has the same problem while fixing getGridModelsMetrics().

[SW-2538] The getGridModelsMetrics() and getGridModelsParams() Methods Do Not Name Columns Correctly

---

core/src/integTest/scala/ai/h2o/sparkling/H2OContextFlowSSLTestSuite.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala
doc/src/site/sphinx/tutorials/secured_flow.rst

This PR introduces new configuration option `spark.ext.h2o.internal.rest.verify_ssl_certificates` and renames the unreleased property `spark.ext.h2o.verify_ssl_hostnames` to `spark.ext.h2o.internal.rest.verify_ssl_hostnames`.

[SW-2539] Disable SSL Certificate Verification in Python Client and Spark Instances Separately

---

ci/Jenkinsfile-release

```
[2021-03-18T15:06:17.814Z] + . /envs/****_env_python3.6/bin/activate
[2021-03-18T15:06:17.814Z] + [  = /home/jenkins/workspace/RELEASE_rel-3.32-spark-3.0/py/build/pkg@tmp/durable-e5f03771/script.sh ]
[2021-03-18T15:06:17.814Z] + deactivate nondestructive
[2021-03-18T15:06:17.814Z] + unset -f pydoc
[2021-03-18T15:06:17.814Z] + [ -z  ]
[2021-03-18T15:06:17.814Z] + [ -z  ]
[2021-03-18T15:06:17.814Z] + [ -n  ]
[2021-03-18T15:06:17.814Z] + [ -n  ]
[2021-03-18T15:06:17.814Z] + [ -z  ]
[2021-03-18T15:06:17.814Z] + unset VIRTUAL_ENV
[2021-03-18T15:06:17.814Z] + [ ! nondestructive = nondestructive ]
[2021-03-18T15:06:17.814Z] + VIRTUAL_ENV=/envs/****_env_python3.6
[2021-03-18T15:06:17.814Z] + [  = cygwin ]
[2021-03-18T15:06:17.814Z] + [  = msys ]
[2021-03-18T15:06:17.814Z] + export VIRTUAL_ENV …
```

 [HOTFIX] setuptools Cannot Be Found during Publishing Artifacts to PyPi

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala

This reverts commit 0d25269d in rel-3.32.1 (forked from master)

Revert "[SW-2230] Remove deprecated setClientIcedDir, setNodeIcedDir, clientIcedDir and nodeIcedDir (#2370)"

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

This reverts commit 6fa2759c in rel-3.32.1 (forked from master).

Revert "[SW-2232] Remove deprecated setH2OClientLogLevel, setH2ONodeLogLevel, h2oClientLogLevel, h2oNodeLogLevel (#2369)"

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

This reverts commit b410f560 in rel-3.32.1 (forked from master).

Revert "[SW-2238] Remove deprecated setH2OClientLogDir, setH2ONodeLogDir, h2oClientLogDir, h2oNodeLogDir (#2371)"

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

This reverts commit 9cb3974a in rel-3.32.1 (forked from master)

Revert "[SW-2243] Remove deprecated setClientBasePort, setNodeBasePort, clientBasePort, nodeBasePort (#2372)"

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

This reverts commit 44c96ef3 in rel-3.32.1 (forked from master)

Revert "[SW-2245] Remove deprecated setClientExtraProperties, setNodeExtraProperties, clientExtraProperties, nodeExtraProperties (#2373)"

---

core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConf.scala

This reverts commit 17f6f954 in rel-3.32.1 (forked from master)

Revert "[SW-2340] Remove deprecated mapperXmx getter an setter in favor of externalH2OMemory (#2367)"

---

doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
py-scoring/src/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.py
py-scoring/src/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.py
py-scoring/src/ai/h2o/sparkling/ml/params/H2OCommonParams.py
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.R
scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.scala

This PR follows the discussion in https://github.com/h2oai/sparkling-water/pull/2457.

[SW-2543] Extend Deprecation of withDetailedPredictionCol to 3.36

---

README.rst
core/src/main/scala/ai/h2o/sparkling/backend/converters/TimeZoneConversions.scala
examples/README.rst
gradle-spark3.1.properties
gradle.properties
py/README.rst
r/README.rst

* Add Spark 3.1 required gradle properties and change default Spark version
* update documentation links
* Use `ZoneId.systemDefault` instead of `DateTimeUtils.defaultTimeZone.getID` (see [commit in spark repository](https://github.com/apache/spark/commit/17a5007fd8b9249593a703ba7659847ec09be2e8))

[SW-2537] Add support for Spark 3.1

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala

Error when stacked ensemble become the best (selected) model :
```
[2021-04-16T17:44:53.130Z]     	at water.fvec.Frame.checksum_impl(Frame.java:577)
[2021-04-16T17:44:53.130Z]     	at water.Keyed.checksum(Keyed.java:108)
[2021-04-16T17:44:53.130Z]     	at water.api.schemas3.ModelMetricsBaseV3.fillFromImpl(ModelMetricsBaseV3.java:78)
[2021-04-16T17:44:53.130Z]     	at water.api.schemas3.ModelMetricsBinomialV3.fillFromImpl(ModelMetricsBinomialV3.java:50)
[2021-04-16T17:44:53.130Z]     	at water.api.schemas3.ModelMetricsBinomialV3.fillFromImpl(ModelMetricsBinomialV3.java:10)
[2021-04-16T17:44:53.130Z]     	at water.api.schemas3.ModelMetricsBinomialGLMV3.fillFromImpl(ModelMetricsBinomialGLMV3.java:26)
[2021-04-16T17:44:53.130Z]     	at …
```

[SW-2552] Delete Train and Validation Frame after MOJO Model is Downloaded inside H2OAutoML.fit()

---

ci/Jenkinsfile-from-h2o-branch
ci/commons.groovy
core/build.gradle
examples/build.gradle
ml/build.gradle
py/tests/unit/with_runtime_sparkling/test_gcs_import.py

Spark 2.2 - 2.4 has hadoop-client 2.6.5 as a dependency. This dependency is incompatible with guava  17+.
Error:
```
[2021-04-20T17:44:34.936Z]     java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
[2021-04-20T17:44:34.936Z]         at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:312)
[2021-04-20T17:44:34.936Z]         at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
[2021-04-20T17:44:34.936Z]         at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
[2021-04-20T17:44:34.936Z]         at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
[2021-04-20T17:44:34.936Z]         at …
```

[SW-2537][FOLLOWUP] Fix "guava" Dependency Collision on Spark 2.2-2.4

---

ci/Jenkinsfile-release
ci/build.gradle
gradle.properties

Databricks tests fails because of setuptools incompatibility. Release pipeline setuptools in each run.

[SW-2556] Upgrade "setuptools" during the build of testing docker image

---

ci/build.gradle
gradle.properties

Since dbplyr is fixed 1.4.2 and it's not compatible with Sparklyr 1.6.2, R tests fail.
```
13:06:39  Failed to connect to localhost port 54323: Connection refused
13:06:39  Backtrace:
13:06:39    1. dplyr::collect(mojo$transform(sdf)) testMojo.R:54:2
13:06:39   25. h2o:::.h2o.__remoteSend(...)
13:06:39   26. h2o:::.h2o.__checkConnectionHealth()
```

[SW-2558] Upgrade dbplyr in SW Testing Docker Image

---

ci/Jenkinsfile-release

`params.commons.getSupportedPythonVersions(params.spark)` can' be called inside `dir(packageDetails.path) {}`, otherwise gradle properties are read at wrong location:
```/home/jenkins/workspace/RELEASE_rel-3.32.1-spark-2.4/py/build/conda/gradle-spark2.4.properties```
The correct path is: 
```/home/jenkins/workspace/RELEASE_rel-3.32.1-spark-2.4/gradle-spark2.4.properties```

[SW-2537][FOLLOWUP] Fix Conda Stages in Release Pipeline

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AlgorithmConfigurations.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/ParameterNameConverter.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/ParameterSubstitutionContext.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/AlgorithmTemplateBase.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/MOJOModelTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/MOJOModelTemplate.scala
booklet/src/sections/productionazing.tex
doc/src/site/sphinx/deployment/load_mojo.rst
doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportances.scala
py-scoring/src/ai/h2o/sparkling/ml/params/H2OMOJOModelParams.py
py-scoring/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
py-scoring/src/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportances.py
py-scoring/src/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportancesOnMOJO.py
py/tests/unit/with_runtime_sparkling/test_mojo.py
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModel.R
r/src/tests/testthat/testMojo.R
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportancesOnMOJO.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/NullableDataFrameParam.scala

Jira ticket: https://h2oai.atlassian.net/browse/SW-2559

[SW-2559] Expose Scoring History and Variable Importances on H2OMOJOModel

---

doc/src/site/sphinx/ml/sw_coxph.rst

Fixes JIRA: https://h2oai.atlassian.net/browse/SW-2567
Current example fails for 
```
org.apache.spark.sql.AnalysisException: cannot resolve '`label`' given input columns: [start, transplant, stop, age, event, year, id, surgery];;
'Project [start#2305, stop#2306, event#2307, age#2308, year#2309, surgery#2310, transplant#2311, id#2312, 'label]
+- Relation[start#2305,stop#2306,event#2307,age#2308,year#2309,surgery#2310,transplant#2311,id#2312] csv
```
need to add parameters that are needed for CoxPH

[SW-2567] Fix CoxPH docs example for Scala and Python

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala

JIRA: https://h2oai.atlassian.net/browse/SW-2569

[SW-2569] Added example for spark.ext.h2o.flow.extra.http.headers

---

bin/build-kubernetes-images.sh

The signature of repo `http://cloud.r-project.org/bin/linux/debian buster-cran35/` has changed.
Error:
```
[2021-07-12T20:59:36.896Z] Hit:1 http://security.debian.org/debian-security buster/updates InRelease
[2021-07-12T20:59:36.896Z] Get:2 http://cloud.r-project.org/bin/linux/debian buster-cran35/ InRelease [4375 B]
[2021-07-12T20:59:36.896Z] Hit:3 https://deb.debian.org/debian buster InRelease
[2021-07-12T20:59:36.896Z] Hit:4 https://deb.debian.org/debian buster-updates InRelease
[2021-07-12T20:59:36.896Z] Err:2 http://cloud.r-project.org/bin/linux/debian buster-cran35/ InRelease
[2021-07-12T20:59:36.896Z]   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FCAE2A0E115C3D8A
[2021-07-12T20:59:38.077Z] Reading package lists... …
```

[SW-2577] Fix Building of RSparkling Docker Images

---

ci/build.gradle
gradle-spark3.0.properties
gradle.properties

This PR also fixes a problem with missing colorama dependency in rel-3.32.1 branch

[SW-2575] Upgrade Spark in Testing Docker Image to 3.0.3

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/MOJOModelTemplate.scala
py-scoring/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py

The inner arrays were represented as java objects of py4j.

[SW-2573] Fix interactionConstraints on H2OXGBoostMOJOModel in Python

---

core/src/main/scala/ai/h2o/sparkling/backend/converters/SparkDataFrameConverter.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala

In such a cases, the column names are converted to `null` which leads to following errors.:
```
ERROR water.default: 
java.lang.NullPointerException
at water.parser.ParseDataset.logParseResults(ParseDataset.java:1068)
at ai.h2o.sparkling.extensions.rest.api.ImportFrameHandler.finalize(ImportFrameHandler.scala:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at water.api.Handler.handle(Handler.java:60)
at water.api.RequestServer.serve(RequestServer.java:470)
at water.api.RequestServer.doGeneric(RequestServer.java:301)
at …
```

[SW-2580] Conversion Method ash2oframe Throws Exception When an Input Contains a Column Named "na" or "Null"

---

ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala

The setter was accidentally removed during the implementation of `H2OAutoEncoder` (see https://github.com/h2oai/sparkling-water/commit/3c726991238c54e50c5c625a3cb8ceaf17a72042#diff-21d18931af889cef1b94b7b3ce9204d123d9942a3eade6bc7f12773b905956e9L113)

[SW-2562][FOLLOWUP] Add missing setConvertInvalidNumbersToNa back

---

py/tests/unit/with_runtime_sparkling/test_mojo.py
r/src/tests/testthat/testMojo.R
scoring/src/main/scala/ai/h2o/sparkling/ml/internals/H2OMetric.java

I've tested the feature manually:

[SW-2595] Add 'mean_per_class_error' to model trainings map

---

py/tests/unit/with_runtime_sparkling/test_gridsearch.py
scoring/src/main/scala/ai/h2o/sparkling/ml/internals/H2OMetric.java

The new feature was tested manually: 
Both metrics are associated with the ordering `'smaller number -> better model'`.

[SW-2596] Add RMSLE and MAE to model metric maps

---

bin/sparkling-env.sh

The current check expects Java version to start with "1.x". This requirement doesn't go well with Java 11+ where the prefix `1.` is omitted.

[SW-2598] Fix Version Check in sparkling-env.sh Script

---

booklet/build.gradle

SW relese build for Spark 2.4 fails on the following error:
```
[2021-08-20T16:00:29.351Z] 
[2021-08-20T16:00:29.351Z] > Task :sparkling-water-booklet:generateConfiguration FAILED
[2021-08-20T16:00:29.351Z] Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
[2021-08-20T16:00:29.351Z] 	at ai.h2o.sparkling.booklet.generation.ConfigurationRunner$.main(ConfigurationRunner.scala:36)
[2021-08-20T16:00:29.351Z] 	at ai.h2o.sparkling.booklet.generation.ConfigurationRunner.main(ConfigurationRunner.scala)
[2021-08-20T16:00:29.351Z] Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
[2021-08-20T16:00:29.351Z] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2021-08-20T16:00:29.352Z] 	at …
```

[SW-2602][HOTFIX] Fix booklet build for Spark 2.4

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/IgnoredParameters.scala

From [H2O documentation](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/deep-learning.html?highlight=autoencoder):
>Note: Cross-validation is not supported when autoencoder is enabled.

[SW-2603] Remove Cross-validation-related Parameters from H2OAutoEncoder

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/MOJOModelTemplate.scala

When `H2OMOJOModel` is loaded, it parsers training parameter values from mojo internals. When parsing of an individual parameter goes wrong, an error could be displayed in `sparkling-shell` and that's confusing for users.:
Since training parameter values are not the key functionality and  the model can be still used for scoring, I'm suggesting to change such errors to warnings.

[SW-2607] Change Error Caused by Setting MOJO Model Parameters to Warning

---

py/tests/unit/with_runtime_sparkling/test_automl.py

The other PR fails because of the change in AutoML. The number of StackEnsemble models was increased from 2 to 3.

[SW-2609] Update AutoML Tests to Consider 3 StackEnsamble Models in Leaderboard

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/MOJOModelAPIRunner.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/MetricsBaseTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/MetricsInitTemplate.scala
api-generation/src/main/scala/ai/h2o/sparkling/api/generation/python/ModelMetricsTemplate.scala
py-scoring/src/ai/h2o/sparkling/ml/params/H2OMOJOModelParams.py
py/tests/unit/with_runtime_sparkling/test_mojo.py
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala

Generated files:
[__init__.py.txt](https://github.com/h2oai/sparkling-water/files/7068576/__init__.py.txt)
[H2OAnomalyMetrics.py.txt](https://github.com/h2oai/sparkling-water/files/7068577/H2OAnomalyMetrics.py.txt)
[H2OAutoEncoderMetrics.py.txt](https://github.com/h2oai/sparkling-water/files/7068578/H2OAutoEncoderMetrics.py.txt)
[H2OBinomialGLMMetrics.py.txt](https://github.com/h2oai/sparkling-water/files/7068579/H2OBinomialGLMMetrics.py.txt)
[H2OBinomialMetrics.py.txt](https://github.com/h2oai/sparkling-water/files/7068580/H2OBinomialMetrics.py.txt)
[H2OClusteringMetrics.py.txt](https://github.com/h2oai/sparkling-water/files/7068581/H2OClusteringMetrics.py.txt)
[H2OCommonMetrics.py.txt](https://github.com/h2oai/sparkling-water/files/7068582/H2OCommonMetrics.py.txt) …

[SW-2588] Expose Model Metrics as Objects on H2OMOJOModel in Python API

---

ml/src/test/scala/ai/h2o/sparkling/ml/features/H2OPCATestSuite.scala
py/tests/unit/with_runtime_sparkling/test_pca.py

It happens time to time that one of the PCA tests fails with the following error:
```
[2021-09-15T12:29:48.534Z] ai.h2o.sparkling.ml.features.H2OPCATestSuite > A pipeline with a PCA model sourcing data from vector column transforms testing dataset without an exception FAILED
[2021-09-15T12:29:48.534Z]     org.scalatest.exceptions.TestFailedException: 1 was not greater than or equal to 2
[2021-09-15T12:29:48.534Z]         at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[2021-09-15T12:29:48.534Z]         at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6482)
[2021-09-15T12:29:48.534Z]         at ai.h2o.sparkling.ml.features.H2OPCATestSuite$$anonfun$6.apply$mcV$sp(H2OPCATestSuite.scala:159)
[2021-09-15T12:29:48.534Z]         at …
```

[SW-2030] Fix Intermittent Failure of PCA Tests

---

ci/build.gradle
gradle.properties

`openjdk:8-jdk-slim` used to be based on the buster (debian apt) repository:
```
/etc/apt/sources.list:# deb http://snapshot.debian.org/archive/debian/20210621T000000Z buster main
/etc/apt/sources.list:deb http://deb.debian.org/debian buster main
/etc/apt/sources.list:# deb http://snapshot.debian.org/archive/debian-security/20210621T000000Z buster/updates main
/etc/apt/sources.list:deb http://security.debian.org/debian-security buster/updates main
/etc/apt/sources.list:# deb http://snapshot.debian.org/archive/debian/20210621T000000Z buster-updates main
/etc/apt/sources.list:deb http://deb.debian.org/debian buster-updates main
```
now it's based on the bullseye (debian apt) repository:
```
/etc/apt/sources.list:# deb http://snapshot.debian.org/archive/debian/20210902T000000Z bullseye main …
```

[SW-2612] Change K8s Base Image for Spark 2.4 to openjdk:8-jdk-slim-buster

---

api-generation/build.gradle
build.gradle
dist/build.gradle

The [`sparkling-water-ml` project references](https://github.com/h2oai/sparkling-water/blob/master/ml/build.gradle#L29) `sparkling-water-api-generation` which is not currently published.

[SW-2616] Enable Publishing of api-generation Project

---

bin/build-kubernetes-images.sh

The default image openjdk:11-jre-slim used to be based on the buster (debian apt) repository. It has been recently changed to bullseye. This repository change causes failure of building spark-py docker image for the version 3.0 and 3.1. The newer repo is missing packages for python 2.7. This PR changes the base image for Spark 3.0 and 3.1 images to openjdk:11-jre-slim-buster. 
The change was manually verified on EKS cluster.

[SW-2615] Change K8s Base Image for Spark 3.0, 3.1 to openjdk:11-jre-slim-buster

---

py/tests/unit/with_runtime_sparkling/test_automl.py

The leaderboard from the current H2O-3 master:
```
+---+--------------------------------------------------------+------------------+------------------+------------------+--------------------+-------------------+-------------------+
|   |model_id                                                |auc               |logloss           |aucpr             |mean_per_class_error|rmse               |mse                |
+---+--------------------------------------------------------+------------------+------------------+------------------+--------------------+-------------------+-------------------+
|0  |GBM_2_AutoML_12_20211005_125025                         |0.8189505267823656|0.51098447144185  |0.7254775942015933|0.2210610658392717  |0.4099098864296385 |0.16802611499275913|
|1 …
```

[SW-2621] Fix Tests to Consider More Stacked Ensemble Models in AutoML Leaderborad

---

core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala
core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala

It seems that Databricks HC cluster doesn't allow ICMP echo requests to the address of eth0 worker interfaces. H2O nodes uses ICMP echo requests to check if the address and its interface is in the healthy state. The explicit setting of IP address should bypass this check which is in the context of SW unnecessary.

[SW-2640] InternalBackend Should Set IP Address Explicitly to H2O Node

---

core/src/test/scala/ai/h2o/sparkling/H2OConfTestSuite.scala

A new property was introduced in this PR (The PR was tested against the latest master): https://github.com/h2oai/sparkling-water/pull/2668

[SW-2642][FOLLOWUP] Increase Number of Properties in Tests for InternalBackendConf

---

gradle.properties

Upgrading to 2.5.12 for now. Upgrade to latest will be done in https://github.com/h2oai/sparkling-water/pull/2669 once we know the reason of differences.

[SW-2650] Upgrade MOJO runtime to 2.5.12

---

py-scoring/build.gradle
py/build.gradle

pypandoc is a dependency of pyspark and the current version 1.7.1 (1.7.0) doesn't support python 2.7

[SW-2660] Use pypandoc 1.6.4 during Execution of Tests

---

core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
doc/src/site/sphinx/migration_guide.rst

The items from `org.apache.spark.h2o` namespace will run thick H2O client (legacy and buggy), which hasn't been completely removed yet.

[SW-2669] Move Removal of Items from org.apache.spark.h2o Namespace too 3.38 

---

api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/AlgorithmConfigurations.scala
doc/src/site/sphinx/migration_guide.rst
ml/src/main/scala/ai/h2o/sparkling/ml/params/HasDeprecatedAutoencoder.scala
ml/src/main/scala/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportances.scala
py-scoring/src/ai/h2o/sparkling/ml/params/HasDeprecatedAutoencoder.py
py-scoring/src/ai/h2o/sparkling/ml/params/HasDeprecatedAutoencoderOnMOJO.py
py-scoring/src/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportances.py
py-scoring/src/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportancesOnMOJO.py
scoring/src/main/scala/ai/h2o/sparkling/ml/params/HasDeprecatedAutoencoderOnMOJO.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/HasDeprecatedVariableImportancesOnMOJO.scala

The parameters and methods were deprecated in `3.34.0.1-1` which was released 4 months ago. This time is not enough long  for all users to be notified about the change.

[SW-2668] Move Removal of Certain Deep Learning Parameters from 3.36 to 3.38

---

py/tests/unit/with_runtime_sparkling/test_gcs_import.py

the old file is no longer available and the test fails
that file is coming from some official public dataset and is not ideal as that's not a CSV but some other format and the resulting dataframe doesn't make much sense, but I think that's not that bad given that test just checks if some file coming from GCS can be used

[SW-2671] change GCS import test file

---

ci/Jenkinsfile-databricks

The databricks tests fails with the following error:
```
+ python setup.py bdist_wheel
/home/jenkins/miniconda/lib/python3.9/site-packages/setuptools/dist.py:501: UserWarning: The version specified ('3.36.0.1_1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
script returned exit code 1
```

[SW-2670] Fix Databricks Smoke Tests

---

core/src/main/scala/ai/h2o/sparkling/backend/Writer.scala
core/src/main/scala/ai/h2o/sparkling/backend/utils/ReflectionUtils.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala
doc/src/site/sphinx/design/spark_h2o_mapping.rst
doc/src/site/sphinx/migration_guide.rst
py/tests/unit/with_runtime_sparkling/test_Spark_to_H2O_conversions.py
r/src/tests/testthat/testConversions.R
scoring/src/main/scala/ai/h2o/sparkling/ml/models/RowConverter.scala

This change conversion aligned with storing spark data frame to a parquet file and reading with h2o.
```
>>> df = spark.range(100).select((col("id") % 2).cast("boolean").alias("b"))
>>> df.write.parquet("/Users/marek/testBoolean/b")
>>> hf = h2o.import_file(path="/Users/marek/testBoolean/b")
>>> hf.levels()
[['False', 'True']]
```
Side note: When Spark reads csv, it identifies columns with  boolean values as string columns:
```
booleans.csv
"numbers", "stringNumbers", "lowerBooleans", "capitalBooleans", "upperBooleans", "stringLowerBooleans", "stringCapitalBooleans", "stringUpperBooleans"
0, "0", false, False, FALSE, "false", "False", "FALSE"
1, "1", true, True, TRUE, "true", "True", "TRUE"
0, "0", false, False, FALSE, "false", "False", "FALSE"
1, "1", true, True, TRUE, "true", "True", …
```

[SW-2676] Change Domain Levels to "True" and "False" for Columns Originating in BooleanType

---

doc/src/site/sphinx/deployment/load_mojo.rst

See [this piece of code](https://github.com/h2oai/sparkling-water/blob/2a8edb271b4f7478e7bd2adee7cfe59b6a4c77ae/scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OAlgorithmMOJOModel.scala#L85) in `H2OAlgorithmMOJOModel`.

[SW-2681] Add Comment to Documentation about Contributions Support only in Binomial and Regression Models

---

core/build.gradle

Integration tests fails on compilation:
```
[2022-01-31T18:09:29.236Z] > Task :sparkling-water-core:compileIntegTestScala
[2022-01-31T18:09:36.216Z] [Error] /home/jenkins/workspace/NIGHTLY_H2O_BRANCH_rel-3.36-spark-2.2-internal/core/src/main/scala/ai/h2o/sparkling/backend/external/K8sExternalBackendClient.scala:21: object fabric8 is not a member of package io
[2022-01-31T18:09:36.216Z] [Error] /home/jenkins/workspace/NIGHTLY_H2O_BRANCH_rel-3.36-spark-2.2-internal/core/src/main/scala/ai/h2o/sparkling/backend/external/K8sExternalBackendClient.scala:27: not found: type DefaultKubernetesClient
[2022-01-31T18:09:36.216Z] [Error] /home/jenkins/workspace/NIGHTLY_H2O_BRANCH_rel-3.36-spark-2.2-internal/core/src/main/scala/ai/h2o/sparkling/backend/external/K8sHeadlessService.scala:24: object …
```

[SW-2684][FOLLOWUP] Add io.fabric8.kubernetes-client as dependecy to integration tests

---

ci/Jenkinsfile-databricks
ci/Jenkinsfile-release
ci/build.gradle
ci/sparklingWaterPipeline.groovy
gradle.properties

This PR also replaces usage of deadsnakes repository with conda environments since Ubuntu 16.04 is not supported anymory (https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa):
```
Supported Ubuntu and Python Versions
====================================
- Ubuntu 18.04 (bionic) Python2.3 - Python 2.6, Python 3.1 - Python 3.5, Python3.7 - Python3.11
- Ubuntu 20.04 (focal) Python3.5 - Python3.7, Python3.9 - Python3.11
- Note: Python2.7 (all), Python 3.6 (bionic), Python 3.8 (focal) are not provided by deadsnakes as upstream ubuntu provides those packages.
- Note: for focal, older python versions require libssl1.0.x so they are not currently built
The packages may also work on other versions of Ubuntu or Debian, but that is not tested or supported.
```

[SW-2688] Update Repository Key In Spark R Docker Files

---

ci/Jenkinsfile-release

the release pipeline fails on:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run
$ conda init <SHELL_NAME>
Currently supported shells are:
- bash
- fish
- tcsh
- xonsh
- zsh
- powershell
```

[SW-2692] Initialize Conda in Release Pipeline

---

ml/src/integTest/scala/ai/h2o/sparkling/ml/IntegrationTestSuite.scala

It seems that Spark 3.2 consumes more memory.

[SW-2691] Increase Memory on Scala Integration Tests

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala

Printing the warning to stdout since Spark logging might be uninitialized.

[SW-2655] Introduce a warning during the serialization of MOJO model

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala

After the change https://github.com/h2oai/h2o-3/pull/6113, The stacked ensemble models needs to be delete first. Otherwise, during a try to delete a stacked ensemble model, [this line](https://github.com/h2oai/h2o-3/pull/6113/files#diff-ad93828b9151a2ed49334d31e84b42bb51f128704c09cde92ced8a6da673db3cR64) will throw NPE since a base model has already been deleted.

[SW-2697] Fix Binary Model Cleaning in H2OAutoML

---

ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OStackedEnsemble.scala

This PR fixes a failing test on `master` branch:
```
[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/NIGHTLY_H2O_BRANCH/detail/master/2/pipeline#step-641-log-203)[2022-04-05T19:39:01.589Z] ai.h2o.sparkling.ml.models.BinaryModelTestSuite > Binary model is available in H2O after training StackedEnsemble in SW FAILED
[2022-04-05T19:39:01.589Z]     ai.h2o.sparkling.backend.exceptions.RestApiCommunicationException: H2O node http://172.17.0.2:54321/[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/NIGHTLY_H2O_BRANCH/detail/master/2/pipeline#step-641-log-204)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/NIGHTLY_H2O_BRANCH/detail/master/2/pipeline#step-641-log-205)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/NIGHTLY_H2O_BRANCH/detail/m …
```

[SW-1184][FOLLOWUP] Delete base binary models only when keepBinaryModels is set to false

---

py/tests/unit/with_runtime_sparkling/test_automl.py

The following python test is failing:
```
[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/TESTS_H2O_BRANCH/detail/master/1/pipeline/775/#step-780-log-244)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/TESTS_H2O_BRANCH/detail/master/1/pipeline/775/#step-780-log-245)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/TESTS_H2O_BRANCH/detail/master/1/pipeline/775/#step-780-log-246)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/TESTS_H2O_BRANCH/detail/master/1/pipeline/775/#step-780-log-247)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/TESTS_H2O_BRANCH/detail/master/1/pipeline/775/#step-780-log-248)[](https://sparkling-jenkins.h2o.ai/blue/organizations/jenkins/TESTS_H2O_BRANCH/detail/master/1/pipeline/775/#step-780-log- …
```

[SW-2699] Fix Failing AutoML Test

---

core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
core/src/main/scala/ai/h2o/sparkling/backend/external/K8sH2OStatefulSet.scala

The behavior after the change:
Default value of `spark.ext.h2o.nthreads`
```
$SPARK_HOME/bin/spark-shell \
--master "k8s://$K8S_MASTER" \
--deploy-mode client \
--conf spark.scheduler.minRegisteredResourcesRatio=1 \
--conf spark.kubernetes.container.image=marekh2o/sparkling-water-scala:3.38.0.1-1-3.1c \
--conf spark.executor.instances=1 \
--conf spark.driver.host=sparkling-water-app \
--conf spark.kubernetes.driver.pod.name=sparkling-water-app \
--conf spark.ext.h2o.backend.cluster.mode=external \
--conf spark.ext.h2o.external.start.mode=auto \
--conf spark.ext.h2o.external.auto.start.backend=kubernetes \
--conf spark.ext.h2o.external.cluster.size=2 \
--conf spark.ext.h2o.external.memory=2G \
--conf spark.ext.h2o.external.k8s.docker.image=marekh2o/sparkling-water-external-backend:3.38.0.1- …
```

[SW-2701] Add Ability to Specify Number of Cores with Automatic External Backend on K8s

---

scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.scala

Don't evaluate deprecated method within a cycle as it leads to excessive logging.

[SW-2707] Deprecated method causes slow down because of excessive logging.

---

r/src/tests/testthat/testConversions.R

It seems that PR https://github.com/h2oai/h2o-3/pull/5107 introduced type attributes on data of H2OFrame.  `expect_equal` method looks also at attributes during value comparison by default. That's the reason why we are getting failures since the expected constants don't have any attributes. This PR proposes to use`expect_equal`  with  the parameter `ignore_attr` set to `TRUE` in order to  compare just values.

[SW-2713] Fix Failing R Tests

---

core/src/test/scala/ai/h2o/sparkling/SparkTestContext.scala
core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterFullCategoricalTestSuite.scala

Jenkins workers have been upgraded from t2.xglarge to t2.2xlarge due to kubernetes tests. One of the tests started failing on external backend:
```
ai.h2o.sparkling.backend.converters.DataFrameConverterFullCategoricalTestSuite > DataFrame[String] with only unique values with in 100 partitions to H2OFrame[T_STR] and back FAILED
[2022-06-27T17:10:47.541Z]     ai.h2o.sparkling.backend.exceptions.RestApiCommunicationException: H2O node http://172.17.0.2:54321/ responded with
[2022-06-27T17:10:47.541Z]     Status code: 500 : Server Error
[2022-06-27T17:10:47.542Z]     Server error: {"__meta":{"schema_version":3,"schema_name":"H2OErrorV3","schema_type":"H2OError"},"timestamp":1656349834337,"error_url":"/3/FinalizeFrame","msg":"\n\nERROR MESSAGE:\n\nDistributedException from …
```

[SW-2722] Fix Failing Test on External Backend

---

ci/build.gradle
ci/sparklingWaterPipeline.groovy
gradle.properties

The new CI infrastructure sets `CI` environment variable in the testing docker image which causes H2O build [loading artifacts from local nexus](https://github.com/h2oai/h2o-3/blob/master/build.gradle#L6-L22).

[SW-2726][FOLLOWUP] Fix Builds Against H2O branch

---

doc/src/site/sphinx/tutorials/use_as_spark_package.rst

`--packages` downloads only jar artifacts from maven (not from PyPi or Conda)

[SW-2730] Remove False Statement from Sparkling Water Documentation

---

py/tests/unit/with_runtime_sparkling/test_Spark_to_H2O_conversions.py

The textual layout of Python `H2OFrame` on H2O-3 master branch has  changed from:
```
time
-------------------
2019-04-04 00:00:00
2020-01-01 00:00:00
2020-02-02 00:00:00
2020-03-03 00:00:00
[4 rows x 1 column]
```
to:
```
time
2019-04-04 00:00:00
2020-01-01 00:00:00
2020-02-02 00:00:00
2020-03-03 00:00:00
[4 rows x 1 column]
```

[SW-2734] Fix Time Conversion Tests in Python API

---

py/tests/unit/with_runtime_sparkling/test_mojo.py

https://h2oai.atlassian.net/browse/PUBDEV-8470 introduced new training parameters to gbm. the only one is not null by default.

[SW-2746] Fix GBM MOJO Test in Python

---

ml/src/test/scala/ai/h2o/sparkling/ml/models/MOJOParameterTestSuite.scala
py-scoring/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
py/tests/unit/with_runtime_sparkling/test_mojo_parameters.py
scoring/src/main/scala/ai/h2o/sparkling/ml/params/NullableBooleanArrayParam.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/params/ParameterConstructorMethods.scala

The parameter is introduced in auto-generated code of SW API. This PR introduces boolean array type for the new parameter since the first time that such a type is used in SW API.
Related PR to H2O-3 repository: https://github.com/h2oai/h2o-3/pull/6336
Genereted files:
- [H2OGAMParams.py](https://github.com/h2oai/sparkling-water/files/9756525/H2OGAMParams.py.txt)
- [H2OGAMParams.scala](https://github.com/h2oai/sparkling-water/files/9756556/H2OGAMParams.scala.txt)

[SW-2754] Expose splinesNonNegative parameter on H2OGAM

---

doc/src/site/sphinx/deployment/load_mojo_pipeline.rst
py-scoring/src/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.py
py-scoring/src/ai/h2o/sparkling/ml/models/H2OMOJOSettings.py
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.R
r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOSettings.R
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.scala
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOSettings.scala
utils/src/main/scala/org/apache/spark/sql/SWGenericRow.scala

Passing data to underlying mojo2 runtime library in form of MojoFrames of 1 record is not performant. After changing the logic and send data in MojoFrames of 1000 records, the scoring is 10x faster.

[SW-2758] Improvement in overall scoring performance for DAI mojo's

---

ci/Jenkinsfile-databricks

The thrown error:
```
+ conda activate sw_env_python3.6
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run
$ conda init <SHELL_NAME>
Currently supported shells are:
- bash
- fish
- tcsh
- xonsh
- zsh
- powershell
See 'conda init --help' for more information and options.
IMPORTANT: You may need to close and restart your shell after running 'conda init'.
script returned exit code 1
```

[SW-2767] Fix DBC tests

---

gradle.properties

[GH-5646] Avoid CVE-2019-10086 by upgrading MOJO2 lib

---

doc/CHANGELOG.rst

Extends #5637 
Migrate issues after the release.

[GH-5637][FOLLOWUP] Migrate Release Notes to GitHub Issues

---

py-scoring/README.rst
py/README.rst

[GH-5656] Add Documentation Link for Spark 3.4 to Python Package Description

---

bin/build-kubernetes-images.sh
ci/build.gradle
gradle.properties

[GH-5669] Fix Spark 3.4 Docker image building

---

gradle.properties

[GH-5674] Upgrade H2O to 3.44.0.1

---

build.gradle
gradle-spark3.0.properties
gradle-spark3.1.properties
gradle-spark3.2.properties
gradle-spark3.3.properties
gradle-spark3.4.properties
gradle.properties
py-scoring/build.gradle
py/build.gradle

closes #5676 closes #5679 closes #5619

[GH-5676][GH-5679][GH-5619] Add support for Python 3.10 & 3.11

---

README.rst
core/src/test/scala/ai/h2o/sparkling/TestUtils.scala
gradle-spark3.3.properties
gradle-spark3.5.properties
gradle.properties
py-scoring/README.rst
py/README.rst
scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.scala
utils/src/main/scala/ai/h2o/sparkling/ml/utils/SchemaUtils.scala
utils/src/main/scala_spark_3.0/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala
utils/src/main/scala_spark_3.1/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala
utils/src/main/scala_spark_3.2/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala
utils/src/main/scala_spark_3.3/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala
utils/src/main/scala_spark_3.4/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala
utils/src/main/scala_spark_3.5/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala
utils/src/main/scala_spark_3.5/ai/h2o/sparkling/sql/functions.scala
utils/src/main/scala_spark_3.5/org/apache/spark/sql/expose/SparkUserDefinedFunction.scala
utils/src/main/scala_spark_others/ai/h2o/sparkling/sql/catalyst/encoders/RowEncoder.scala

[GH-5670] Add Spark 3.5 support
